--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-125 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-125 [3/2+] 35.4922 (5) keV
Calculation of the allowed transition from the electron capture decay of I-125.

Transition energy: 150.28 (6) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.18981 (30)
PL2/PK =  0.004905 (14)
PM1/PK =  0.04344 (22)
PM2/PK =  0.0012299 (13)
PN1/PK =  0.00985 (10)
PN2/PK =  2.610E-4 (18)
PO1/PK =  0.001623 (28)
PO2/PK =  2.707E-5 (41)

L/K =  0.19472 (29)
M/K =  0.04467 (22)
N/K =  0.01011 (10)
O/K =  0.001650 (28)


------------------------------
Relative capture probabilities

PK  =  0.79926 (41)
PL1 =  0.15171 (16)
PL2 =  0.003920 (13)
PM1 =  0.03472 (16)
PM2 =  9.830E-4 (6)
PN1 =  0.00788 (8)
PN2 =  2.086E-4 (13)
PO1 =  0.001297 (21)
PO2 =  2.164E-5 (32)

K =  0.79926 (41)
L =  0.15563 (15)
M =  0.03571 (16)
N =  0.00808 (8)
O =  0.001319 (22)


------------------------------
Capture branch from input data

Iec =   100 %


---------------------
Capture probabilities

PK  =  0.79926 (41)
PL1  =  0.15171 (16)
PL2  =  0.003920 (13)
PM1  =  0.03472 (16)
PM2  =  9.830E-4 (6)
PN1  =  0.00788 (8)
PN2  =  2.086E-4 (13)
PO1  =  0.001297 (21)
PO2  =  2.164E-5 (32)

K =  0.79926 (41)
L =  0.15563 (15)
M =  0.03571 (16)
N =  0.00808 (8)
O =  0.001319 (22)


------------------------------------------------------------
Input log ft value (ec): 5.4

Log ft value (ec)    =  5.4502 (38)
with log f           =  -1.2601 (38)
or f-value           =  0.05495 (47)
and log partial T1/2 =  6.71021 (20)

