--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 77-Ir-192 [4+] g.s.  -->  Daughter nucleus: 76-Os-192 [3+] 690.3705 (4) keV
Calculation of the allowed transition from the electron capture decay of Ir-192.

Transition energy: 355.8 (23) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.2213 (8)
PL2/PK =  0.01461 (7)
PM1/PK =  0.05505 (34)
PM2/PK =  0.003977 (29)
PN1/PK =  0.01526 (14)
PN2/PK =  0.001081 (11)
PO1/PK =  0.003297 (40)
PO2/PK =  2.045E-4 (29)
PP1/PK =  2.661E-4 (36)

L/K =  0.2359 (9)
M/K =  0.05902 (37)
N/K =  0.01634 (15)
O/K =  0.003501 (43)
P/K =  2.661E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.7604 (8)
PL1 =  0.16829 (45)
PL2 =  0.011108 (41)
PM1 =  0.04186 (21)
PM2 =  0.003024 (18)
PN1 =  0.01160 (9)
PN2 =  8.22E-4 (8)
PO1 =  0.002507 (28)
PO2 =  1.555E-4 (20)
PP1 =  2.024E-4 (25)

K =  0.7604 (8)
L =  0.17940 (49)
M =  0.04488 (23)
N =  0.01243 (10)
O =  0.002663 (30)
P =  2.024E-4 (25)


------------------------------
Capture branch from input data

Iec =   3.969 (30) %


---------------------
Capture probabilities

PK  =  0.7604 (8)
PL1  =  0.16829 (45)
PL2  =  0.011108 (41)
PM1  =  0.04186 (21)
PM2  =  0.003024 (18)
PN1  =  0.01160 (9)
PN2  =  8.22E-4 (8)
PO1  =  0.002507 (28)
PO2  =  1.555E-4 (20)
PP1  =  2.024E-4 (25)

K =  0.7604 (8)
L =  0.17940 (49)
M =  0.04488 (23)
N =  0.01243 (10)
O =  0.002663 (30)
P =  2.024E-4 (25)


------------------------------------------------------------
Input log ft value (ec): 8.5

Log ft value (ec)    =  8.569 (9)
with log f           =  0.363 (8)
or f-value           =  2.304 (44)
and log partial T1/2 =  8.2061 (33)

