--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 77-Ir-192 [4+] g.s.  -->  Daughter nucleus: 76-Os-192 [4+] 580.2798 (8) keV
Calculation of the allowed transition from the electron capture decay of Ir-192.

Transition energy: 465.9 (23) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.19998 (49)
PL2/PK =  0.013201 (46)
PM1/PK =  0.04907 (23)
PM2/PK =  0.003547 (20)
PN1/PK =  0.01356 (10)
PN2/PK =  9.62E-4 (8)
PO1/PK =  0.002928 (31)
PO2/PK =  1.818E-4 (23)
PP1/PK =  2.363E-4 (28)

L/K =  0.2132 (5)
M/K =  0.05262 (25)
N/K =  0.01452 (11)
O/K =  0.003109 (33)
P/K =  2.363E-4 (28)


------------------------------
Relative capture probabilities

PK  =  0.7790 (6)
PL1 =  0.15579 (27)
PL2 =  0.010284 (28)
PM1 =  0.03823 (15)
PM2 =  0.002764 (14)
PN1 =  0.01056 (7)
PN2 =  7.49E-4 (6)
PO1 =  0.002281 (22)
PO2 =  1.416E-4 (17)
PP1 =  1.841E-4 (21)

K =  0.7790 (6)
L =  0.16607 (30)
M =  0.04099 (16)
N =  0.01131 (8)
O =  0.002422 (24)
P =  1.841E-4 (21)


------------------------------
Capture branch from input data

Iec =   0.686 (9) %


---------------------
Capture probabilities

PK  =  0.7790 (6)
PL1  =  0.15579 (27)
PL2  =  0.010284 (28)
PM1  =  0.03823 (15)
PM2  =  0.002764 (14)
PN1  =  0.01056 (7)
PN2  =  7.49E-4 (6)
PO1  =  0.002281 (22)
PO2  =  1.416E-4 (17)
PP1  =  1.841E-4 (21)

K =  0.7790 (6)
L =  0.16607 (30)
M =  0.04099 (16)
N =  0.01131 (8)
O =  0.002422 (24)
P =  1.841E-4 (21)


------------------------------------------------------------
Input log ft value (ec): 9.5

Log ft value (ec)    =  9.606 (9)
with log f           =  0.638 (6)
or f-value           =  4.34 (6)
and log partial T1/2 =  8.968 (6)

