[build-system]
requires = [
  "scikit-build-core>=0.12.2",
  "pybind11>=3.0",
  "pybind11-stubgen"
]
build-backend = "scikit_build_core.build"

[project]
name = "ggems"
version = "2.0.0"
readme = "README.md"
license = "GPL-3.0-or-later"
description="GPU Geant4-based Monte Carlo Simulations"
authors = [
  { name = "Didier BENOIT", email = "didier.benoit@inserm.fr" },
  { name = "Julien BERT",   email = "julien.bert@univ-brest.fr"}
]

[project.urls]
homepage = "https://ggems.fr"
repository = "https://github.com/GGEMS/ggems"
documentation = "https://doc.ggems.fr/v2.0"

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"
wheel.expand-macos-universal-tags = true
wheel.exclude = [
  "ggems/bindings_*.cc",
  "ggems/detail/**",
  "ggems/Release/**"
]
build.verbose = true


[[tool.scikit-build.overrides]]
if.state = "^editable$"
build-dir = "build"
