--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 55-Cs-134 [4+] g.s.  -->  Daughter nucleus: 54-Xe-134 [2+] 847.041 (23) keV
This 2nd forbidden non-unique transition from the electron capture decay of Cs-134 is calculated as 1st forbidden unique.

Transition energy: 386.3 (8) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.17145 (30)
PL2/PK =  0.004904 (43)
PL3/PK =  0.01897 (30)
PM1/PK =  0.03866 (21)
PM2/PK =  0.001174 (6)
PM3/PK =  0.004255 (49)
PN1/PK =  0.01007 (13)
PM4/PK =  1.174E-5 (11)
PN2/PK =  2.955E-4 (17)
PN3/PK =  9.61E-4 (9)
PO1/PK =  0.001686 (27)
PN4/PK =  2.52E-6 (6)
PO2/PK =  3.611E-5 (41)
PO3/PK =  9.10E-5 (17)

L/K =  0.19532 (28)
M/K =  0.0441 (2)
N/K =  0.01133 (14)
O/K =  0.001813 (29)


------------------------------
Relative capture probabilities

PK  =  0.79836 (33)
PL1 =  0.13688 (18)
PL2 =  0.003915 (34)
PL3 =  0.01514 (24)
PM1 =  0.03087 (16)
PM2 =  9.370E-4 (48)
PM3 =  0.003397 (39)
PN1 =  0.00804 (10)
PM4 =  9.37E-6 (8)
PN2 =  2.359E-4 (12)
PN3 =  7.67E-4 (7)
PO1 =  0.001346 (21)
PN4 =  2.010E-6 (49)
PO2 =  2.883E-5 (31)
PO3 =  7.27E-5 (13)

K =  0.79836 (33)
L =  0.15594 (22)
M =  0.03521 (15)
N =  0.00904 (11)
O =  0.001447 (23)


------------------------------
Capture branch from input data

Iec =   3.0E-4 (14) %


---------------------
Capture probabilities

PK  =  0.79836 (33)
PL1  =  0.13688 (18)
PL2  =  0.003915 (34)
PL3  =  0.01514 (24)
PM1  =  0.03087 (16)
PM2  =  9.370E-4 (48)
PM3  =  0.003397 (39)
PN1  =  0.00804 (10)
PM4  =  9.37E-6 (8)
PN2  =  2.359E-4 (12)
PN3  =  7.67E-4 (7)
PO1  =  0.001346 (21)
PN4  =  2.010E-6 (49)
PO2  =  2.883E-5 (31)
PO3  =  7.27E-5 (13)

K =  0.79836 (33)
L =  0.15594 (22)
M =  0.03521 (15)
N =  0.00904 (11)
O =  0.001447 (23)


------------------------------------------------------------
Input log ft value (ec): 13

Log ft value (ec)    =  12.76 (20)
with log f           =  -0.573 (6)
or f-value           =  0.2673 (37)
and log partial T1/2 =  13.34 (20)

