--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-54 [3+] g.s.  -->  Daughter nucleus: 24-Cr-54 [2+] 834.855 (3) keV
Calculation of the allowed transition from the electron capture decay of Mn-54.

Transition energy: 542.3 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11169 (29)
PL2/PK =  5.04E-4 (14)
PM1/PK =  0.01739 (10)
PM2/PK =  7.33E-5 (24)
PN1/PK =  0.001327 (26)

L/K =  0.11219 (31)
M/K =  0.01746 (11)
N/K =  0.001327 (26)


------------------------------
Relative capture probabilities

PK  =  0.88418 (34)
PL1 =  0.09875 (22)
PL2 =  4.46E-4 (12)
PM1 =  0.01538 (8)
PM2 =  6.48E-5 (21)
PN1 =  0.001174 (22)

K =  0.88418 (34)
L =  0.09920 (23)
M =  0.01544 (9)
N =  0.001174 (22)


------------------------------
Capture branch from input data

Iec =   99.9997 (3) %


---------------------
Capture probabilities

PK  =  0.88418 (34)
PL1  =  0.09875 (22)
PL2  =  4.46E-4 (12)
PM1  =  0.01538 (8)
PM2  =  6.48E-5 (21)
PN1  =  0.001174 (22)

K =  0.88418 (34)
L =  0.09920 (23)
M =  0.01544 (9)
N =  0.001174 (22)


------------------------------------------------------------
Input log ft value (ec): 6.17

Log ft value (ec)    =  6.1437 (39)
with log f           =  -1.2872 (39)
or f-value           =  0.05162 (46)
and log partial T1/2 =  7.430934 (42)

