--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-54 [3+] g.s.  -->  Daughter nucleus: 24-Cr-54 [0+] g.s.
Calculation of the 2nd forbidden unique transition from the electron capture decay of Mn-54.

Transition energy: 1377.2 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11207 (29)
PL2/PK =  5.06E-4 (14)
PL3/PK =  7.83E-4 (24)
PM1/PK =  0.01746 (10)
PM2/PK =  7.36E-5 (24)
PM3/PK =  1.003E-4 (36)
PN1/PK =  0.001332 (26)
PM4/PK =  1.076E-8 (11)
PM5/PK =  2.72E-10 (6)

L/K =  0.11336 (33)
M/K =  0.01763 (11)
N/K =  0.001332 (26)


------------------------------
Relative capture probabilities

PK  =  0.88314 (36)
PL1 =  0.09897 (22)
PL2 =  4.47E-4 (12)
PL3 =  6.91E-4 (21)
PM1 =  0.01542 (8)
PM2 =  6.50E-5 (21)
PM3 =  8.86E-5 (31)
PN1 =  0.001177 (22)
PM4 =  9.5E-9 (1)
PM5 =  2.399E-10 (48)

K =  0.88314 (36)
L =  0.10011 (25)
M =  0.01557 (9)
N =  0.001177 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  530 (10)
L1/b+ =  59.4 (13)
L2/b+ =  0.268 (13)
L3/b+ =  0.415 (21)
M1/b+ =  9.25 (24)
M2/b+ =  0.0390 (21)
M3/b+ =  0.0531 (30)
N1/b+ =  0.706 (28)
M4/b+ =  5.70E-6 (17)
M5/b+ =  1.44E-7 (6)

K/b+ =  530 (10)
L/b+ =  60.1 (14)
M/b+ =  9.34 (24)
N/b+ =  0.706 (28)

EC/b+ =  600 (12)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   3.E-4 (3) %   Iec =   3.E-4 (3) %   Ib+ =   5.7E-7 %
Iec      =   3.E-4 (3) % (input data kept)
Ib+      =   5.7E-7 % (input data kept)
Iec tot. =   3.E-4 (3) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88167 (36)
PL1  =  0.09881 (22)
PL2  =  4.46E-4 (12)
PL3  =  6.90E-4 (21)
PM1  =  0.01539 (8)
PM2  =  6.49E-5 (21)
PM3  =  8.84E-5 (31)
PN1  =  0.001175 (22)
PM4  =  9.48E-9 (10)
PM5  =  2.395E-10 (48)

K =  0.88167 (36)
L =  0.09995 (25)
M =  0.01554 (9)
N =  0.001175 (22)


------------------------------------------------------------
Input log ft value (ec & beta +): 13.9

Log ft value (ec)    =  14.20 (43)
with log f           =  1.2439 (41)
or f-value           =  17.53 (17)
and log partial T1/2 =  12.95 (43)

