--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 49-In-111 [9/2+] g.s.  -->  Daughter nucleus: 48-Cd-111 [7/2+] 416.6 keV
Calculation of the allowed transition from the electron capture decay of In-111.

Transition energy: 445.2 (46) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13333 (32)
PL2/PK =  0.00291 (10)
PM1/PK =  0.02844 (16)
PM2/PK =  6.45E-4 (29)
PN1/PK =  0.00637 (6)
PN2/PK =  1.33E-4 (7)
PO1/PK =  0.001016 (28)

L/K =  0.13624 (42)
M/K =  0.02909 (19)
N/K =  0.00650 (7)
O/K =  0.001016 (28)


------------------------------
Relative capture probabilities

PK  =  0.8526 (5)
PL1 =  0.11368 (20)
PL2 =  0.00248 (8)
PM1 =  0.02425 (12)
PM2 =  5.50E-4 (25)
PN1 =  0.005429 (48)
PN2 =  1.14E-4 (6)
PO1 =  8.66E-4 (24)

K =  0.8526 (5)
L =  0.11616 (28)
M =  0.02480 (14)
N =  0.00554 (5)
O =  8.66E-4 (24)


------------------------------
Capture branch from input data

Iec =   99.995 (5) %


---------------------
Capture probabilities

PK  =  0.8526 (5)
PL1  =  0.11368 (20)
PL2  =  0.00248 (8)
PM1  =  0.02425 (12)
PM2  =  5.50E-4 (25)
PN1  =  0.005429 (48)
PN2  =  1.14E-4 (6)
PO1  =  8.66E-4 (24)

K =  0.8526 (5)
L =  0.11616 (28)
M =  0.02480 (14)
N =  0.00554 (5)
O =  8.66E-4 (24)


------------------------------------------------------------
Input log ft value (ec): 5

Log ft value (ec)    =  5.040 (22)
with log f           =  -0.344 (22)
or f-value           =  0.453 (22)
and log partial T1/2 =  5.38445 (7)

