--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 49-In-111 [9/2+] g.s.  -->  Daughter nucleus: 48-Cd-111 [11/2-] 396.15 keV
This 1st forbidden non-unique transition from the electron capture decay of In-111 is calculated as allowed.

Transition energy: 465.6 (46) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1327 (3)
PL2/PK =  0.00289 (10)
PM1/PK =  0.02829 (15)
PM2/PK =  6.42E-4 (29)
PN1/PK =  0.00633 (6)
PN2/PK =  1.33E-4 (7)
PO1/PK =  0.001011 (28)

L/K =  0.1356 (4)
M/K =  0.02893 (18)
N/K =  0.00647 (7)
O/K =  0.001011 (28)


------------------------------
Relative capture probabilities

PK  =  0.85324 (49)
PL1 =  0.11323 (19)
PL2 =  0.00247 (8)
PM1 =  0.02414 (12)
PM2 =  5.47E-4 (25)
PN1 =  0.005404 (47)
PN2 =  1.13E-4 (6)
PO1 =  8.62E-4 (23)

K =  0.85324 (49)
L =  0.11570 (27)
M =  0.02469 (14)
N =  0.00552 (5)
O =  8.62E-4 (23)


------------------------------
Capture branch from input data

Iec =   0.005 (5) %


---------------------
Capture probabilities

PK  =  0.85324 (49)
PL1  =  0.11323 (19)
PL2  =  0.00247 (8)
PM1  =  0.02414 (12)
PM2  =  5.47E-4 (25)
PN1  =  0.005404 (47)
PN2  =  1.13E-4 (6)
PO1  =  8.62E-4 (23)

K =  0.85324 (49)
L =  0.11570 (27)
M =  0.02469 (14)
N =  0.00552 (5)
O =  8.62E-4 (23)


------------------------------------------------------------
Input log ft value (ec): 9

Log ft value (ec)    =  9.38 (43)
with log f           =  -0.303 (22)
or f-value           =  0.498 (24)
and log partial T1/2 =  9.69 (43)

