--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 58-Ce-139 [3/2+] g.s.  -->  Daughter nucleus: 57-La-139 [5/2+] 165.8576 (11) keV
Calculation of the allowed transition from the electron capture decay of Ce-139.

Transition energy: 104.1 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.285 (9)
PL2/PK =  0.00921 (32)
PM1/PK =  0.0705 (28)
PM2/PK =  0.00246 (10)
PN1/PK =  0.0183 (8)
PN2/PK =  6.19E-4 (29)
PO1/PK =  0.00355 (18)
PO2/PK =  1.01E-4 (5)
PP1/PK =  3.99E-4 (20)

L/K =  0.294 (10)
M/K =  0.0730 (29)
N/K =  0.0189 (9)
O/K =  0.00366 (18)
P/K =  3.99E-4 (20)


------------------------------
Relative capture probabilities

PK  =  0.719 (7)
PL1 =  0.2050 (47)
PL2 =  0.00663 (16)
PM1 =  0.0507 (15)
PM2 =  0.00177 (5)
PN1 =  0.01317 (47)
PN2 =  4.45E-4 (17)
PO1 =  0.00256 (10)
PO2 =  7.28E-5 (30)
PP1 =  2.87E-4 (11)

K =  0.719 (7)
L =  0.2117 (49)
M =  0.0525 (16)
N =  0.01362 (49)
O =  0.00263 (10)
P =  2.87E-4 (11)


------------------------------
Capture branch from input data

Iec =   99.9973 (27) %


---------------------
Capture probabilities

PK  =  0.719 (7)
PL1  =  0.2050 (47)
PL2  =  0.00663 (16)
PM1  =  0.0507 (15)
PM2  =  0.00177 (5)
PN1  =  0.01317 (47)
PN2  =  4.45E-4 (17)
PO1  =  0.00256 (10)
PO2  =  7.28E-5 (30)
PP1  =  2.87E-4 (11)

K =  0.719 (7)
L =  0.2117 (49)
M =  0.0525 (16)
N =  0.01362 (49)
O =  0.00263 (10)
P =  2.87E-4 (11)


------------------------------------------------------------
Input log ft value (ec): 5.42

Log ft value (ec)    =  5.532 (38)
with log f           =  -1.543 (38)
or f-value           =  0.0286 (25)
and log partial T1/2 =  7.07527 (6)

