--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 58-Ce-139 [3/2+] g.s.  -->  Daughter nucleus: 57-La-139 [7/2+] g.s.
This 2nd forbidden non-unique transition from the electron capture decay of Ce-139 is calculated as 1st forbidden unique.

Transition energy: 270 (3) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.2158 (17)
PL2/PK =  0.00696 (6)
PL3/PK =  0.0528 (17)
PM1/PK =  0.0522 (6)
PM2/PK =  0.001814 (24)
PM3/PK =  0.01288 (48)
PN1/PK =  0.01348 (24)
PM4/PK =  4.03E-5 (15)
PN2/PK =  4.55E-4 (9)
PN3/PK =  0.00291 (13)
PO1/PK =  0.00261 (6)
PN4/PK =  9.29E-6 (43)
PO2/PK =  7.44E-5 (17)
PO3/PK =  4.00E-4 (19)
PP1/PK =  2.93E-4 (6)
PO4/PK =  7.47E-8 (36)

L/K =  0.2757 (35)
M/K =  0.0669 (11)
N/K =  0.01685 (37)
O/K =  0.00309 (8)
P/K =  2.93E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.7338 (27)
PL1 =  0.1584 (7)
PL2 =  0.005110 (25)
PL3 =  0.0388 (11)
PM1 =  0.03827 (32)
PM2 =  0.001331 (12)
PM3 =  0.00945 (31)
PN1 =  0.00989 (14)
PM4 =  2.96E-5 (10)
PN2 =  3.34E-4 (5)
PN3 =  0.00213 (8)
PO1 =  0.001918 (34)
PN4 =  6.81E-6 (29)
PO2 =  5.46E-5 (10)
PO3 =  2.94E-4 (13)
PP1 =  2.153E-4 (37)
PO4 =  5.48E-8 (24)

K =  0.7338 (27)
L =  0.2023 (18)
M =  0.0491 (6)
N =  0.01237 (23)
O =  0.002266 (47)
P =  2.153E-4 (37)


------------------------------
Capture branch from input data

Iec =   0.008 %


---------------------
Capture probabilities

PK  =  0.7338 (27)
PL1  =  0.1584 (7)
PL2  =  0.005110 (25)
PL3  =  0.0388 (11)
PM1  =  0.03827 (32)
PM2  =  0.001331 (12)
PM3  =  0.00945 (31)
PN1  =  0.00989 (14)
PM4  =  2.96E-5 (10)
PN2  =  3.34E-4 (5)
PN3  =  0.00213 (8)
PO1  =  0.001918 (34)
PN4  =  6.81E-6 (29)
PO2  =  5.46E-5 (10)
PO3  =  2.94E-4 (13)
PP1  =  2.153E-4 (37)
PO4  =  5.48E-8 (24)

K =  0.7338 (27)
L =  0.2023 (18)
M =  0.0491 (6)
N =  0.01237 (23)
O =  0.002266 (47)
P =  2.153E-4 (37)


------------------------------------------------------------
Input log ft value (ec): 10.6

Log ft value (ec)    =  10.027 (23)
with log f           =  -1.145 (23)
or f-value           =  0.0716 (38)
and log partial T1/2 =  11.17217 (6)

