--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 24-Cr-51 [7/2-] g.s.  -->  Daughter nucleus: 23-V-51 [5/2-] 320.0835 (4) keV
Calculation of the allowed transition from the electron capture decay of Cr-51.

Transition energy: 432.54 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.10875 (27)
PL2/PK =  4.33E-4 (5)
PM1/PK =  0.01723 (11)
PM2/PK =  6.36E-5 (11)
PN1/PK =  4.91E-4 (6)

L/K =  0.10918 (27)
M/K =  0.01729 (12)
N/K =  4.91E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.88734 (31)
PL1 =  0.0965 (2)
PL2 =  3.845E-4 (43)
PM1 =  0.01529 (10)
PM2 =  5.65E-5 (9)
PN1 =  4.354E-4 (49)

K =  0.88734 (31)
L =  0.09688 (21)
M =  0.01534 (10)
N =  4.354E-4 (49)


------------------------------
Capture branch from input data

Iec =   9.91 (2) %


---------------------
Capture probabilities

PK  =  0.88734 (31)
PL1  =  0.0965 (2)
PL2  =  3.845E-4 (43)
PM1  =  0.01529 (10)
PM2  =  5.65E-5 (9)
PN1  =  4.354E-4 (49)

K =  0.88734 (31)
L =  0.09688 (21)
M =  0.01534 (10)
N =  4.354E-4 (49)


------------------------------------------------------------
Input log ft value (ec): 5.86

Log ft value (ec)    =  5.870 (7)
with log f           =  -1.513 (7)
or f-value           =  0.03069 (46)
and log partial T1/2 =  7.3830 (9)

