--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 81-Tl-201 [1/2+] g.s.  -->  Daughter nucleus: 80-Hg-201 [5/2-] 26.269 keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Tl-201.

Transition energy: 457 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.304 (8)
PL2/PK =  0.0232 (11)
PL3/PK =  0.0346 (43)
PM1/PK =  0.0774 (25)
PM2/PK =  0.00642 (34)
PM3/PK =  0.0092 (12)
PN1/PK =  0.0225 (8)
PM4/PK =  6.7E-5 (8)
PN2/PK =  0.00182 (10)
PN3/PK =  0.00242 (31)
PO1/PK =  0.00555 (20)
PN4/PK =  1.88E-5 (23)
PO2/PK =  4.10E-4 (24)
PO3/PK =  4.7E-4 (6)
PP1/PK =  5.25E-4 (25)
PO4/PK =  1.95E-6 (26)

L/K =  0.362 (14)
M/K =  0.093 (4)
N/K =  0.0267 (12)
O/K =  0.00643 (29)
P/K =  5.25E-4 (25)


------------------------------
Relative capture probabilities

PK  =  0.672 (8)
PL1 =  0.2043 (31)
PL2 =  0.0156 (5)
PL3 =  0.0233 (26)
PM1 =  0.052 (1)
PM2 =  0.00431 (17)
PM3 =  0.0062 (7)
PN1 =  0.01509 (31)
PM4 =  4.53E-5 (47)
PN2 =  0.00122 (5)
PN3 =  0.00163 (19)
PO1 =  0.00373 (9)
PN4 =  1.26E-5 (13)
PO2 =  2.76E-4 (12)
PO3 =  3.17E-4 (38)
PP1 =  3.53E-4 (12)
PO4 =  1.31E-6 (16)

K =  0.672 (8)
L =  0.243 (6)
M =  0.0625 (18)
N =  0.0179 (5)
O =  0.00432 (14)
P =  3.53E-4 (12)


------------------------------
Capture branch from input data

Iec =   0.23 %


---------------------
Capture probabilities

PK  =  0.672 (8)
PL1  =  0.2043 (31)
PL2  =  0.0156 (5)
PL3  =  0.0233 (26)
PM1  =  0.052 (1)
PM2  =  0.00431 (17)
PM3  =  0.0062 (7)
PN1  =  0.01509 (31)
PM4  =  4.53E-5 (47)
PN2  =  0.00122 (5)
PN3  =  0.00163 (19)
PO1  =  0.00373 (9)
PN4  =  1.26E-5 (13)
PO2  =  2.76E-4 (12)
PO3  =  3.17E-4 (38)
PP1  =  3.53E-4 (12)
PO4  =  1.31E-6 (16)

K =  0.672 (8)
L =  0.243 (6)
M =  0.0625 (18)
N =  0.0179 (5)
O =  0.00432 (14)
P =  3.53E-4 (12)


------------------------------------------------------------
Input log ft value (ec): 8.5

Log ft value (ec)    =  8.58 (8)
with log f           =  0.53 (8)
or f-value           =  3.4 (6)
and log partial T1/2 =  8.05796 (25)

