--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 56-Ba-133 [1/2+] g.s.  -->  Daughter nucleus: 55-Cs-133 [5/2+] 80.9979 (11) keV
This 2nd forbidden non-unique transition from the electron capture decay of Ba-133 is calculated as 1st forbidden unique.

Transition energy: 436.3 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.16825 (31)
PL2/PK =  0.0050 (6)
PL3/PK =  0.0147 (20)
PM1/PK =  0.03963 (21)
PM2/PK =  0.00126 (17)
PM3/PK =  0.00354 (49)
PN1/PK =  0.00993 (10)
PM4/PK =  1.03E-5 (16)
PN2/PK =  3.06E-4 (43)
PN3/PK =  7.7E-4 (11)
PO1/PK =  0.001777 (29)
PN4/PK =  2.30E-6 (38)
PO2/PK =  4.5E-5 (7)
PO3/PK =  9.4E-5 (15)
PP1/PK =  2.28E-4 (20)

L/K =  0.1879 (29)
M/K =  0.0444 (9)
N/K =  0.01100 (26)
O/K =  0.00192 (5)
P/K =  2.28E-4 (20)


------------------------------
Relative capture probabilities

PK  =  0.8029 (26)
PL1 =  0.13509 (32)
PL2 =  0.0040 (5)
PL3 =  0.0118 (15)
PM1 =  0.03182 (7)
PM2 =  0.00101 (13)
PM3 =  0.00284 (38)
PN1 =  0.00797 (5)
PM4 =  8.3E-6 (13)
PN2 =  2.46E-4 (33)
PN3 =  6.2E-4 (9)
PO1 =  0.001427 (18)
PN4 =  1.85E-6 (30)
PO2 =  3.6E-5 (5)
PO3 =  7.5E-5 (12)
PP1 =  1.83E-4 (15)

K =  0.8029 (26)
L =  0.1509 (18)
M =  0.0357 (6)
N =  0.00883 (18)
O =  0.001538 (36)
P =  1.83E-4 (15)


------------------------------
Capture branch from input data

Iec =   0.7 %


---------------------
Capture probabilities

PK  =  0.8029 (26)
PL1  =  0.13509 (32)
PL2  =  0.0040 (5)
PL3  =  0.0118 (15)
PM1  =  0.03182 (7)
PM2  =  0.00101 (13)
PM3  =  0.00284 (38)
PN1  =  0.00797 (5)
PM4  =  8.3E-6 (13)
PN2  =  2.46E-4 (33)
PN3  =  6.2E-4 (9)
PO1  =  0.001427 (18)
PN4  =  1.85E-6 (30)
PO2  =  3.6E-5 (5)
PO3  =  7.5E-5 (12)
PP1  =  1.83E-4 (15)

K =  0.8029 (26)
L =  0.1509 (18)
M =  0.0357 (6)
N =  0.00883 (18)
O =  0.001538 (36)
P =  1.83E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 10.9

Log ft value (ec)    =  10.342 (44)
with log f           =  -0.335 (44)
or f-value           =  0.462 (43)
and log partial T1/2 =  10.67680 (25)

