--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 85-At-211 [9/2-] g.s.  -->  Daughter nucleus: 84-Po-211 [9/2+] g.s.
This 1st forbidden non-unique transition from the electron capture decay of At-211 is calculated as allowed.

Transition energy: 785.4 (25) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.19890 (32)
PL2/PK =  0.01709 (6)
PM1/PK =  0.04964 (19)
PM2/PK =  0.004698 (8)
PN1/PK =  0.01417 (9)
PN2/PK =  0.0013305 (46)
PO1/PK =  0.003530 (41)
PO2/PK =  3.066E-4 (25)
PP1/PK =  5.89E-4 (10)
PP2/PK =  3.36E-5 (5)

L/K =  0.21599 (28)
M/K =  0.05434 (19)
N/K =  0.0155 (1)
O/K =  0.003837 (43)
P/K =  6.23E-4 (11)


------------------------------
Relative capture probabilities

PK  =  0.77502 (37)
PL1 =  0.15415 (17)
PL2 =  0.01324 (5)
PM1 =  0.03847 (13)
PM2 =  0.003641 (7)
PN1 =  0.01098 (7)
PN2 =  0.0010312 (30)
PO1 =  0.002736 (30)
PO2 =  2.376E-4 (18)
PP1 =  4.56E-4 (8)
PP2 =  2.608E-5 (40)

K =  0.77502 (37)
L =  0.16740 (14)
M =  0.04211 (12)
N =  0.01201 (7)
O =  0.002974 (32)
P =  4.82E-4 (8)


------------------------------
Capture branch from input data

Iec =   57.97 (8) %


---------------------
Capture probabilities

PK  =  0.77502 (37)
PL1  =  0.15415 (17)
PL2  =  0.01324 (5)
PM1  =  0.03847 (13)
PM2  =  0.003641 (7)
PN1  =  0.01098 (7)
PN2  =  0.0010312 (30)
PO1  =  0.002736 (30)
PO2  =  2.376E-4 (18)
PP1  =  4.56E-4 (8)
PP2  =  2.608E-5 (40)

K =  0.77502 (37)
L =  0.16740 (14)
M =  0.04211 (12)
N =  0.01201 (7)
O =  0.002974 (32)
P =  4.82E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 5.97

Log ft value (ec)    =  6.056 (6)
with log f           =  1.405 (6)
or f-value           =  25.41 (34)
and log partial T1/2 =  4.6514 (7)

