--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 3669.5 (10) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 1294 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11083 (20)
PL2/PK =  0.0011395 (20)
PM1/PK =  0.01862 (11)
PM2/PK =  1.830E-4 (6)
PN1/PK =  0.002817 (34)
PN2/PK =  1.638E-5 (18)

L/K =  0.11197 (20)
M/K =  0.01880 (11)
N/K =  0.002833 (34)


------------------------------
Relative capture probabilities

PK  =  0.88214 (27)
PL1 =  0.09777 (15)
PL2 =  0.0010052 (21)
PM1 =  0.01642 (10)
PM2 =  1.6144E-4 (44)
PN1 =  0.002485 (29)
PN2 =  1.445E-5 (15)

K =  0.88214 (27)
L =  0.09877 (15)
M =  0.01658 (10)
N =  0.002499 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  133 (20)
L1/b+ =  14.7 (22)
L2/b+ =  0.151 (23)
M1/b+ =  2.47 (36)
M2/b+ =  0.0242 (36)
N1/b+ =  0.37 (6)
N2/b+ =  0.00217 (32)

K/b+ =  133 (20)
L/b+ =  14.8 (22)
M/b+ =  2.49 (37)
N/b+ =  0.38 (6)

EC/b+ =  150 (23)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.74 (19) %   Iec =   0.73 (19) %   Ib+ =   0.005 (1) %
Iec      =   0.73 (19) % (input data kept)
Ib+      =   0.005 (1) % (input data kept)
Iec tot. =   0.74 (19) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8763 (9)
PL1  =  0.09712 (18)
PL2  =  9.986E-4 (23)
PM1  =  0.01631 (10)
PM2  =  1.6037E-4 (47)
PN1  =  0.002468 (29)
PN2  =  1.436E-5 (15)

K =  0.8763 (9)
L =  0.09812 (18)
M =  0.01647 (10)
N =  0.002483 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.9

Log ft value (ec)    =  6.93 (11)
with log f           =  0.031 (10)
or f-value           =  1.073 (24)
and log partial T1/2 =  6.90 (11)

