--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4328.7 (10) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 634 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11281 (25)
PL2/PK =  0.0011493 (25)
PM1/PK =  0.01899 (12)
PM2/PK =  1.850E-4 (6)
PN1/PK =  0.002875 (36)
PN2/PK =  1.656E-5 (19)

L/K =  0.11396 (25)
M/K =  0.01918 (13)
N/K =  0.002891 (36)


------------------------------
Relative capture probabilities

PK  =  0.88026 (32)
PL1 =  0.09930 (19)
PL2 =  0.0010117 (24)
PM1 =  0.01672 (10)
PM2 =  1.628E-4 (5)
PN1 =  0.00253 (3)
PN2 =  1.458E-5 (16)

K =  0.88026 (32)
L =  0.10031 (18)
M =  0.01688 (10)
N =  0.002545 (31)


------------------------------
Capture branch from input data

Iec =   0.19 (5) %


---------------------
Capture probabilities

PK  =  0.88026 (32)
PL1  =  0.09930 (19)
PL2  =  0.0010117 (24)
PM1  =  0.01672 (10)
PM2  =  1.628E-4 (5)
PN1  =  0.00253 (3)
PN2  =  1.458E-5 (16)

K =  0.88026 (32)
L =  0.10031 (18)
M =  0.01688 (10)
N =  0.002545 (31)


------------------------------------------------------------
Input log ft value (ec): 6.9

Log ft value (ec)    =  6.89 (12)
with log f           =  -0.597 (16)
or f-value           =  0.253 (9)
and log partial T1/2 =  7.48 (11)

