--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4210 (1) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 753 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11219 (23)
PL2/PK =  0.0011449 (23)
PM1/PK =  0.01887 (12)
PM2/PK =  1.841E-4 (6)
PN1/PK =  0.002857 (35)
PN2/PK =  1.649E-5 (19)

L/K =  0.11334 (23)
M/K =  0.01906 (12)
N/K =  0.002873 (35)


------------------------------
Relative capture probabilities

PK  =  0.88085 (30)
PL1 =  0.09882 (17)
PL2 =  0.0010085 (23)
PM1 =  0.01663 (10)
PM2 =  1.6219E-4 (48)
PN1 =  0.002516 (30)
PN2 =  1.452E-5 (16)

K =  0.88085 (30)
L =  0.09983 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------
Capture branch from input data

Iec =   0.24 (4) %


---------------------
Capture probabilities

PK  =  0.88085 (30)
PL1  =  0.09882 (17)
PL2  =  0.0010085 (23)
PM1  =  0.01663 (10)
PM2  =  1.6219E-4 (48)
PN1  =  0.002516 (30)
PN2  =  1.452E-5 (16)

K =  0.88085 (30)
L =  0.09983 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------------------------------------
Input log ft value (ec): 6.9

Log ft value (ec)    =  6.94 (7)
with log f           =  -0.445 (14)
or f-value           =  0.359 (12)
and log partial T1/2 =  7.38 (7)

