--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4215.5 (2) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 748 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11222 (23)
PL2/PK =  0.0011450 (23)
PM1/PK =  0.01888 (12)
PM2/PK =  1.842E-4 (6)
PN1/PK =  0.002857 (35)
PN2/PK =  1.649E-5 (19)

L/K =  0.11336 (23)
M/K =  0.01906 (12)
N/K =  0.002874 (35)


------------------------------
Relative capture probabilities

PK  =  0.88083 (30)
PL1 =  0.09884 (17)
PL2 =  0.0010086 (23)
PM1 =  0.01663 (10)
PM2 =  1.6221E-4 (48)
PN1 =  0.002517 (30)
PN2 =  1.452E-5 (16)

K =  0.88083 (30)
L =  0.09985 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------
Capture branch from input data

Iec =   0.61 (3) %


---------------------
Capture probabilities

PK  =  0.88083 (30)
PL1  =  0.09884 (17)
PL2  =  0.0010086 (23)
PM1  =  0.01663 (10)
PM2  =  1.6221E-4 (48)
PN1  =  0.002517 (30)
PN2  =  1.452E-5 (16)

K =  0.88083 (30)
L =  0.09985 (17)
M =  0.01679 (10)
N =  0.002531 (30)


------------------------------------------------------------
Input log ft value (ec): 6.5

Log ft value (ec)    =  6.527 (26)
with log f           =  -0.452 (14)
or f-value           =  0.354 (12)
and log partial T1/2 =  6.978 (22)

