--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3970.6 (4) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 992 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11140 (22)
PL2/PK =  0.0011406 (21)
PM1/PK =  0.01872 (12)
PM2/PK =  1.833E-4 (6)
PN1/PK =  0.002834 (34)
PN2/PK =  1.641E-5 (18)

L/K =  0.11254 (21)
M/K =  0.01891 (12)
N/K =  0.002850 (34)


------------------------------
Relative capture probabilities

PK  =  0.88160 (28)
PL1 =  0.09821 (16)
PL2 =  0.0010055 (21)
PM1 =  0.01651 (10)
PM2 =  1.6159E-4 (45)
PN1 =  0.002498 (29)
PN2 =  1.447E-5 (16)

K =  0.88160 (28)
L =  0.09922 (16)
M =  0.01667 (10)
N =  0.002513 (29)


------------------------------
Capture branch from input data

Iec =   0.64 (5) %


---------------------
Capture probabilities

PK  =  0.88160 (28)
PL1  =  0.09821 (16)
PL2  =  0.0010055 (21)
PM1  =  0.01651 (10)
PM2  =  1.6159E-4 (45)
PN1  =  0.002498 (29)
PN2  =  1.447E-5 (16)

K =  0.88160 (28)
L =  0.09922 (16)
M =  0.01667 (10)
N =  0.002513 (29)


------------------------------------------------------------
Input log ft value (ec): 6.7

Log ft value (ec)    =  6.755 (36)
with log f           =  -0.202 (12)
or f-value           =  0.628 (17)
and log partial T1/2 =  6.957 (34)

