--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 2858.1 (20) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 2105 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11011 (20)
PL2/PK =  0.0011450 (21)
PM1/PK =  0.01848 (11)
PM2/PK =  1.837E-4 (6)
PN1/PK =  0.002796 (33)
PN2/PK =  1.645E-5 (18)

L/K =  0.11126 (19)
M/K =  0.01866 (11)
N/K =  0.002812 (33)


------------------------------
Relative capture probabilities

PK  =  0.88282 (26)
PL1 =  0.09721 (14)
PL2 =  0.0010108 (21)
PM1 =  0.01631 (9)
PM2 =  1.6222E-4 (46)
PN1 =  0.002468 (29)
PN2 =  1.452E-5 (16)

K =  0.88282 (26)
L =  0.09822 (14)
M =  0.01648 (9)
N =  0.002483 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.907 (33)
L1/b+ =  0.0999 (35)
L2/b+ =  0.001039 (40)
M1/b+ =  0.0168 (5)
M2/b+ =  1.67E-4 (6)
N1/b+ =  0.00254 (8)
N2/b+ =  1.492E-5 (46)

K/b+ =  0.907 (33)
L/b+ =  0.1010 (36)
M/b+ =  0.0169 (5)
N/b+ =  0.00255 (8)

EC/b+ =  1.028 (38)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.270 (42) %   Iec =   0.14 (3) %   Ib+ =   0.13 (3) %
Iec      =   0.14 (3) % (input data kept)
Ib+      =   0.13 (3) % (input data kept)
Iec tot. =   0.270 (42) % (input data kept)


---------------------
Capture probabilities

PK  =  0.447 (8)
PL1  =  0.0493 (9)
PL2  =  5.12E-4 (9)
PM1  =  0.00827 (16)
PM2  =  8.22E-5 (15)
PN1  =  0.001251 (27)
PN2  =  7.36E-6 (15)

K =  0.447 (8)
L =  0.0498 (9)
M =  0.00835 (16)
N =  0.001259 (27)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.1

Log ft value (ec)    =  8.07 (9)
with log f           =  0.457 (7)
or f-value           =  2.867 (49)
and log partial T1/2 =  7.62 (9)

