--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [2+] 3160.07 (6) keV
This 1st forbidden non-unique transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 1803 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1103 (2)
PL2/PK =  0.0011422 (21)
PM1/PK =  0.01852 (11)
PM2/PK =  1.833E-4 (6)
PN1/PK =  0.002802 (33)
PN2/PK =  1.641E-5 (18)

L/K =  0.11145 (20)
M/K =  0.01870 (11)
N/K =  0.002818 (34)


------------------------------
Relative capture probabilities

PK  =  0.88264 (27)
PL1 =  0.09736 (14)
PL2 =  0.0010081 (21)
PM1 =  0.01634 (9)
PM2 =  1.6182E-4 (45)
PN1 =  0.002473 (29)
PN2 =  1.449E-5 (16)

K =  0.88264 (27)
L =  0.09837 (14)
M =  0.01651 (9)
N =  0.002487 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  2.71 (13)
L1/b+ =  0.299 (14)
L2/b+ =  0.00309 (16)
M1/b+ =  0.0502 (22)
M2/b+ =  4.97E-4 (23)
N1/b+ =  0.00759 (33)
N2/b+ =  4.45E-5 (19)

K/b+ =  2.71 (13)
L/b+ =  0.302 (14)
M/b+ =  0.0507 (22)
N/b+ =  0.00763 (34)

EC/b+ =  3.07 (15)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.31 (15) %   Iec =   3.99 (14) %   Ib+ =   1.32 (4) %
Iec      =   3.99 (14) % (input data kept)
Ib+      =   1.32 (4) % (input data kept)
Iec tot. =   5.31 (15) % (input data kept)


---------------------
Capture probabilities

PK  =  0.666 (8)
PL1  =  0.0734 (9)
PL2  =  7.60E-4 (9)
PM1  =  0.01233 (16)
PM2  =  1.221E-4 (15)
PN1  =  0.001865 (31)
PN2  =  1.093E-5 (18)

K =  0.666 (8)
L =  0.0742 (9)
M =  0.01245 (16)
N =  0.001876 (31)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.47

Log ft value (ec)    =  6.484 (18)
with log f           =  0.322 (8)
or f-value           =  2.098 (38)
and log partial T1/2 =  6.162 (16)

