--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4621.5 (20) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 342 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11628 (42)
PL2/PK =  0.0011802 (41)
PM1/PK =  0.01965 (16)
PM2/PK =  1.906E-4 (9)
PN1/PK =  0.002976 (42)
PN2/PK =  1.707E-5 (22)

L/K =  0.11746 (42)
M/K =  0.01984 (16)
N/K =  0.002993 (42)


------------------------------
Relative capture probabilities

PK  =  0.87697 (47)
PL1 =  0.10197 (31)
PL2 =  0.0010350 (37)
PM1 =  0.01723 (13)
PM2 =  1.671E-4 (7)
PN1 =  0.002609 (35)
PN2 =  1.497E-5 (19)

K =  0.87697 (47)
L =  0.10301 (31)
M =  0.01740 (13)
N =  0.002624 (35)


------------------------------
Capture branch from input data

Iec =   0.21 (4) %


---------------------
Capture probabilities

PK  =  0.87697 (47)
PL1  =  0.10197 (31)
PL2  =  0.0010350 (37)
PM1  =  0.01723 (13)
PM2  =  1.671E-4 (7)
PN1  =  0.002609 (35)
PN2  =  1.497E-5 (19)

K =  0.87697 (47)
L =  0.10301 (31)
M =  0.01740 (13)
N =  0.002624 (35)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.29 (9)
with log f           =  -1.148 (28)
or f-value           =  0.0711 (46)
and log partial T1/2 =  7.44 (8)

