--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 3622.2 (20) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 1341 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11077 (20)
PL2/PK =  0.0011396 (20)
PM1/PK =  0.01860 (11)
PM2/PK =  1.830E-4 (6)
PN1/PK =  0.002815 (34)
PN2/PK =  1.638E-5 (18)

L/K =  0.11191 (20)
M/K =  0.01879 (11)
N/K =  0.002831 (34)


------------------------------
Relative capture probabilities

PK  =  0.88220 (27)
PL1 =  0.09772 (15)
PL2 =  0.0010054 (21)
PM1 =  0.01641 (10)
PM2 =  1.6145E-4 (44)
PN1 =  0.002483 (29)
PN2 =  1.445E-5 (15)

K =  0.88220 (27)
L =  0.09872 (15)
M =  0.01657 (10)
N =  0.002498 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  71 (9)
L1/b+ =  7.8 (10)
L2/b+ =  0.080 (11)
M1/b+ =  1.31 (16)
M2/b+ =  0.0129 (16)
N1/b+ =  0.199 (25)
N2/b+ =  0.00116 (14)

K/b+ =  71 (9)
L/b+ =  7.9 (10)
M/b+ =  1.33 (16)
N/b+ =  0.200 (25)

EC/b+ =  80 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.37 (11) %   Iec =   0.36 (11) %   Ib+ =   0.005 (2) %
Iec      =   0.36 (11) % (input data kept)
Ib+      =   0.005 (2) % (input data kept)
Iec tot. =   0.37 (11) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8713 (14)
PL1  =  0.09651 (21)
PL2  =  9.930E-4 (26)
PM1  =  0.01621 (10)
PM2  =  1.595E-4 (5)
PN1  =  0.002453 (29)
PN2  =  1.428E-5 (15)

K =  0.8713 (14)
L =  0.09751 (21)
M =  0.01637 (10)
N =  0.002467 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.3

Log ft value (ec)    =  7.27 (13)
with log f           =  0.062 (10)
or f-value           =  1.154 (25)
and log partial T1/2 =  7.21 (13)

