--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4084.3 (2) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 879 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11172 (22)
PL2/PK =  0.0011421 (22)
PM1/PK =  0.01879 (12)
PM2/PK =  1.836E-4 (6)
PN1/PK =  0.002843 (34)
PN2/PK =  1.644E-5 (18)

L/K =  0.11287 (22)
M/K =  0.01897 (12)
N/K =  0.002859 (35)


------------------------------
Relative capture probabilities

PK  =  0.88130 (29)
PL1 =  0.09846 (16)
PL2 =  0.0010065 (22)
PM1 =  0.01656 (10)
PM2 =  1.6180E-4 (46)
PN1 =  0.002505 (30)
PN2 =  1.449E-5 (16)

K =  0.88130 (29)
L =  0.09947 (16)
M =  0.01672 (10)
N =  0.00252 (3)


------------------------------
Capture branch from input data

Iec =   0.50 (4) %


---------------------
Capture probabilities

PK  =  0.88130 (29)
PL1  =  0.09846 (16)
PL2  =  0.0010065 (22)
PM1  =  0.01656 (10)
PM2  =  1.6180E-4 (46)
PN1  =  0.002505 (30)
PN2  =  1.449E-5 (16)

K =  0.88130 (29)
L =  0.09947 (16)
M =  0.01672 (10)
N =  0.00252 (3)


------------------------------------------------------------
Input log ft value (ec): 6.7

Log ft value (ec)    =  6.755 (37)
with log f           =  -0.309 (13)
or f-value           =  0.491 (14)
and log partial T1/2 =  7.064 (35)

