--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3351.54 (7) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 1611 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11046 (20)
PL2/PK =  0.0011408 (21)
PM1/PK =  0.01855 (11)
PM2/PK =  1.831E-4 (6)
PN1/PK =  0.002806 (33)
PN2/PK =  1.639E-5 (18)

L/K =  0.1116 (2)
M/K =  0.01873 (11)
N/K =  0.002823 (34)


------------------------------
Relative capture probabilities

PK  =  0.88249 (27)
PL1 =  0.09748 (15)
PL2 =  0.0010067 (21)
PM1 =  0.01637 (9)
PM2 =  1.6162E-4 (45)
PN1 =  0.002476 (29)
PN2 =  1.447E-5 (16)

K =  0.88249 (27)
L =  0.09849 (14)
M =  0.01653 (9)
N =  0.002491 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  7.22 (47)
L1/b+ =  0.80 (5)
L2/b+ =  0.0082 (5)
M1/b+ =  0.134 (8)
M2/b+ =  0.00132 (8)
N1/b+ =  0.0203 (12)
N2/b+ =  1.18E-4 (7)

K/b+ =  7.22 (47)
L/b+ =  0.81 (5)
M/b+ =  0.135 (8)
N/b+ =  0.0204 (12)

EC/b+ =  8.2 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   9.0 (4) %   Iec =   8.0 (4) %   Ib+ =   1.00 (4) %
Iec      =   8.0 (4) % (input data kept)
Ib+      =   1.00 (4) % (input data kept)
Iec tot. =   9.0 (4) % (input data kept)


---------------------
Capture probabilities

PK  =  0.786 (6)
PL1  =  0.0869 (6)
PL2  =  8.97E-4 (7)
PM1  =  0.01458 (13)
PM2  =  1.440E-4 (11)
PN1  =  0.002207 (30)
PN2  =  1.289E-5 (17)

K =  0.786 (6)
L =  0.0878 (6)
M =  0.01473 (13)
N =  0.00222 (3)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.07

Log ft value (ec)    =  6.084 (24)
with log f           =  0.223 (8)
or f-value           =  1.672 (32)
and log partial T1/2 =  5.860 (22)

