--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 4199.6 (4) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 763 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11215 (23)
PL2/PK =  0.0011446 (23)
PM1/PK =  0.01887 (12)
PM2/PK =  1.841E-4 (6)
PN1/PK =  0.002855 (35)
PN2/PK =  1.648E-5 (19)

L/K =  0.11329 (23)
M/K =  0.01905 (12)
N/K =  0.002872 (35)


------------------------------
Relative capture probabilities

PK  =  0.88089 (30)
PL1 =  0.09879 (17)
PL2 =  0.0010082 (23)
PM1 =  0.01662 (10)
PM2 =  1.6215E-4 (48)
PN1 =  0.002515 (30)
PN2 =  1.452E-5 (16)

K =  0.88089 (30)
L =  0.09980 (17)
M =  0.01678 (10)
N =  0.00253 (3)


------------------------------
Capture branch from input data

Iec =   0.36 (4) %


---------------------
Capture probabilities

PK  =  0.88089 (30)
PL1  =  0.09879 (17)
PL2  =  0.0010082 (23)
PM1  =  0.01662 (10)
PM2  =  1.6215E-4 (48)
PN1  =  0.002515 (30)
PN2  =  1.452E-5 (16)

K =  0.88089 (30)
L =  0.09980 (17)
M =  0.01678 (10)
N =  0.00253 (3)


------------------------------------------------------------
Input log ft value (ec): 6.8

Log ft value (ec)    =  6.77 (5)
with log f           =  -0.433 (14)
or f-value           =  0.369 (12)
and log partial T1/2 =  7.207 (49)

