--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1+] 3441.5 (2) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 1522 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11055 (20)
PL2/PK =  0.0011403 (20)
PM1/PK =  0.01856 (11)
PM2/PK =  1.831E-4 (6)
PN1/PK =  0.002809 (33)
PN2/PK =  1.639E-5 (18)

L/K =  0.11169 (20)
M/K =  0.01875 (11)
N/K =  0.002825 (34)


------------------------------
Relative capture probabilities

PK  =  0.88241 (27)
PL1 =  0.09755 (15)
PL2 =  0.0010062 (21)
PM1 =  0.01638 (9)
PM2 =  1.6155E-4 (45)
PN1 =  0.002478 (29)
PN2 =  1.446E-5 (16)

K =  0.88241 (27)
L =  0.09856 (14)
M =  0.01654 (9)
N =  0.002493 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  13.1 (10)
L1/b+ =  1.45 (11)
L2/b+ =  0.0149 (12)
M1/b+ =  0.243 (17)
M2/b+ =  0.00240 (18)
N1/b+ =  0.0368 (27)
N2/b+ =  2.14E-4 (15)

K/b+ =  13.1 (10)
L/b+ =  1.46 (11)
M/b+ =  0.245 (17)
N/b+ =  0.0370 (27)

EC/b+ =  14.8 (11)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.096 (30) %   Iec =   0.09 (3) %   Ib+ =   0.006 (2) %
Iec      =   0.09 (3) % (input data kept)
Ib+      =   0.006 (2) % (input data kept)
Iec tot. =   0.096 (30) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8267 (40)
PL1  =  0.09139 (46)
PL2  =  9.43E-4 (5)
PM1  =  0.01535 (12)
PM2  =  1.513E-4 (8)
PN1  =  0.002322 (29)
PN2  =  1.355E-5 (16)

K =  0.8267 (40)
L =  0.09233 (47)
M =  0.01550 (12)
N =  0.002335 (29)


------------------------------------------------------------
Input log ft value (ec & beta +): 8

Log ft value (ec)    =  7.98 (15)
with log f           =  0.173 (9)
or f-value           =  1.489 (30)
and log partial T1/2 =  7.81 (14)

