--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4064 (4) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 899 (10) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11166 (22)
PL2/PK =  0.0011417 (22)
PM1/PK =  0.01877 (12)
PM2/PK =  1.835E-4 (6)
PN1/PK =  0.002841 (34)
PN2/PK =  1.643E-5 (18)

L/K =  0.11280 (22)
M/K =  0.01896 (12)
N/K =  0.002857 (35)


------------------------------
Relative capture probabilities

PK  =  0.88136 (29)
PL1 =  0.09841 (16)
PL2 =  0.0010063 (22)
PM1 =  0.01655 (10)
PM2 =  1.6175E-4 (46)
PN1 =  0.002504 (30)
PN2 =  1.448E-5 (16)

K =  0.88136 (29)
L =  0.09942 (16)
M =  0.01671 (10)
N =  0.002518 (30)


------------------------------
Capture branch from input data

Iec =   0.43 (9) %


---------------------
Capture probabilities

PK  =  0.88136 (29)
PL1  =  0.09841 (16)
PL2  =  0.0010063 (22)
PM1  =  0.01655 (10)
PM2  =  1.6175E-4 (46)
PN1  =  0.002504 (30)
PN2  =  1.448E-5 (16)

K =  0.88136 (29)
L =  0.09942 (16)
M =  0.01671 (10)
N =  0.002518 (30)


------------------------------------------------------------
Input log ft value (ec): 6.8

Log ft value (ec)    =  6.84 (9)
with log f           =  -0.289 (13)
or f-value           =  0.514 (16)
and log partial T1/2 =  7.13 (9)

