--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [1-] 2655.32 (4) keV
Calculation of the allowed transition from the electron capture decay of Br-76.

Transition energy: 2308 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11001 (19)
PL2/PK =  0.0011472 (21)
PM1/PK =  0.01846 (11)
PM2/PK =  1.841E-4 (6)
PN1/PK =  0.002793 (33)
PN2/PK =  1.648E-5 (18)

L/K =  0.11116 (19)
M/K =  0.01865 (11)
N/K =  0.002810 (33)


------------------------------
Relative capture probabilities

PK  =  0.88291 (26)
PL1 =  0.09713 (14)
PL2 =  0.0010128 (21)
PM1 =  0.01630 (9)
PM2 =  1.6252E-4 (46)
PN1 =  0.002466 (29)
PN2 =  1.455E-5 (16)

K =  0.88291 (26)
L =  0.09815 (14)
M =  0.01646 (9)
N =  0.002481 (29)


--------------------------
Capture-to-positron ratios

K/b+ =  0.520 (16)
L1/b+ =  0.0572 (17)
L2/b+ =  5.96E-4 (20)
M1/b+ =  0.00960 (24)
M2/b+ =  9.57E-5 (27)
N1/b+ =  0.001452 (38)
N2/b+ =  8.57E-6 (22)

K/b+ =  0.520 (16)
L/b+ =  0.0578 (17)
M/b+ =  0.00970 (25)
N/b+ =  0.001461 (38)

EC/b+ =  0.589 (18)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.41 (9) %   Iec =   0.15 (4) %   Ib+ =   0.26 (8) %
Iec      =   0.15 (4) % (input data kept)
Ib+      =   0.26 (8) % (input data kept)
Iec tot. =   0.41 (9) % (input data kept)


---------------------
Capture probabilities

PK  =  0.327 (6)
PL1  =  0.0360 (7)
PL2  =  3.75E-4 (7)
PM1  =  0.00604 (12)
PM2  =  6.02E-5 (12)
PN1  =  9.14E-4 (21)
PN2  =  5.39E-6 (12)

K =  0.327 (6)
L =  0.0364 (7)
M =  0.00610 (12)
N =  9.19E-4 (21)


------------------------------------------------------------
Input log ft value (ec & beta +): 8.1

Log ft value (ec)    =  8.13 (12)
with log f           =  0.538 (7)
or f-value           =  3.45 (6)
and log partial T1/2 =  7.59 (12)

