--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 4455.2 (30) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 508 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11380 (29)
PL2/PK =  0.0011574 (29)
PM1/PK =  0.01918 (13)
PM2/PK =  1.865E-4 (7)
PN1/PK =  0.002903 (37)
PN2/PK =  1.67E-5 (2)

L/K =  0.11496 (29)
M/K =  0.01937 (13)
N/K =  0.002920 (37)


------------------------------
Relative capture probabilities

PK  =  0.87932 (36)
PL1 =  0.10007 (22)
PL2 =  0.0010178 (27)
PM1 =  0.01686 (11)
PM2 =  1.640E-4 (6)
PN1 =  0.002553 (32)
PN2 =  1.468E-5 (17)

K =  0.87932 (36)
L =  0.10108 (21)
M =  0.01703 (11)
N =  0.002568 (32)


------------------------------
Capture branch from input data

Iec =   0.007 (2) %


---------------------
Capture probabilities

PK  =  0.87932 (36)
PL1  =  0.10007 (22)
PL2  =  0.0010178 (27)
PM1  =  0.01686 (11)
PM2  =  1.640E-4 (6)
PN1  =  0.002553 (32)
PN2  =  1.468E-5 (17)

K =  0.87932 (36)
L =  0.10108 (21)
M =  0.01703 (11)
N =  0.002568 (32)


------------------------------------------------------------
Input log ft value (ec): 8.1

Log ft value (ec)    =  8.12 (13)
with log f           =  -0.794 (20)
or f-value           =  0.161 (8)
and log partial T1/2 =  8.92 (12)

