--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 35-Br-76 [1-] g.s.  -->  Daughter nucleus: 34-Se-76 [**] 3998.4 (10) keV
This transition from the electron capture decay of Br-76 is calculated as allowed.

Transition energy: 965 (9) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11147 (22)
PL2/PK =  0.0011409 (21)
PM1/PK =  0.01874 (12)
PM2/PK =  1.834E-4 (6)
PN1/PK =  0.002836 (34)
PN2/PK =  1.642E-5 (18)

L/K =  0.11262 (21)
M/K =  0.01892 (12)
N/K =  0.002852 (34)


------------------------------
Relative capture probabilities

PK  =  0.88153 (28)
PL1 =  0.09827 (16)
PL2 =  0.0010057 (21)
PM1 =  0.01652 (10)
PM2 =  1.6163E-4 (45)
PN1 =  0.002500 (29)
PN2 =  1.447E-5 (16)

K =  0.88153 (28)
L =  0.09927 (16)
M =  0.01668 (10)
N =  0.002514 (30)


------------------------------
Capture branch from input data

Iec =   0.42 (4) %


---------------------
Capture probabilities

PK  =  0.88153 (28)
PL1  =  0.09827 (16)
PL2  =  0.0010057 (21)
PM1  =  0.01652 (10)
PM2  =  1.6163E-4 (45)
PN1  =  0.002500 (29)
PN2  =  1.447E-5 (16)

K =  0.88153 (28)
L =  0.09927 (16)
M =  0.01668 (10)
N =  0.002514 (30)


------------------------------------------------------------
Input log ft value (ec): 6.9

Log ft value (ec)    =  6.913 (43)
with log f           =  -0.227 (12)
or f-value           =  0.593 (16)
and log partial T1/2 =  7.140 (42)

