--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 55-Cs-131 [5/2+] g.s.  -->  Daughter nucleus: 54-Xe-131 [3/2+] g.s.
Calculation of the allowed transition from the electron capture decay of Cs-131.

Transition energy: 358.00 (18) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14843 (17)
PL2/PK =  0.004250 (35)
PM1/PK =  0.03280 (16)
PM2/PK =  9.975E-4 (44)
PN1/PK =  0.00851 (11)
PN2/PK =  2.502E-4 (12)
PO1/PK =  0.001423 (22)
PO2/PK =  3.055E-5 (32)

L/K =  0.15268 (14)
M/K =  0.03379 (15)
N/K =  0.00876 (11)
O/K =  0.001453 (22)


------------------------------
Relative capture probabilities

PK  =  0.83565 (30)
PL1 =  0.12403 (10)
PL2 =  0.003552 (30)
PM1 =  0.02741 (12)
PM2 =  8.336E-4 (39)
PN1 =  0.00711 (9)
PN2 =  2.091E-4 (10)
PO1 =  0.001189 (18)
PO2 =  2.553E-5 (26)

K =  0.83565 (30)
L =  0.12758 (7)
M =  0.02824 (12)
N =  0.00732 (9)
O =  0.001214 (18)


------------------------------
Capture branch from input data

Iec =   100 %


---------------------
Capture probabilities

PK  =  0.83565 (30)
PL1  =  0.12403 (10)
PL2  =  0.003552 (30)
PM1  =  0.02741 (12)
PM2  =  8.336E-4 (39)
PN1  =  0.00711 (9)
PN2  =  2.091E-4 (10)
PO1  =  0.001189 (18)
PO2  =  2.553E-5 (26)

K =  0.83565 (30)
L =  0.12758 (7)
M =  0.02824 (12)
N =  0.00732 (9)
O =  0.001214 (18)


------------------------------------------------------------
Input log ft value (ec): 5.5804

Log ft value (ec)    =  5.5804 (27)
with log f           =  -0.3420 (26)
or f-value           =  0.4550 (27)
and log partial T1/2 =  5.9224 (7)

