--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-64 [1+] g.s.  -->  Daughter nucleus: 28-Ni-64 [0+] g.s.
Calculation of the allowed transition from the electron capture decay of Cu-64.

Transition energy: 1675.03 (20) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11213 (20)
PL2/PK =  7.25E-4 (10)
PM1/PK =  0.01801 (8)
PM2/PK =  1.113E-4 (19)
PN1/PK =  3.405E-4 (36)

L/K =  0.11285 (21)
M/K =  0.01812 (8)
N/K =  3.405E-4 (36)


------------------------------
Relative capture probabilities

PK  =  0.88393 (23)
PL1 =  0.09911 (15)
PL2 =  6.41E-4 (9)
PM1 =  0.01592 (6)
PM2 =  9.84E-5 (17)
PN1 =  3.010E-4 (31)

K =  0.88393 (23)
L =  0.09975 (16)
M =  0.01602 (7)
N =  3.010E-4 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  2.213 (30)
L1/b+ =  0.2481 (29)
L2/b+ =  0.0016036 (35)
M1/b+ =  0.03985 (37)
M2/b+ =  2.464E-4 (13)
N1/b+ =  7.535E-4 (23)

K/b+ =  2.213 (30)
L/b+ =  0.2497 (29)
M/b+ =  0.04010 (36)
N/b+ =  7.535E-4 (23)

EC/b+ =  2.503 (33)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   61.03 (36) %   Iec =   43.52 (27) %   Ib+ =   17.51 (17) %
Iec      =   43.52 (27) % (input data kept)
Ib+      =   17.51 (17) % (input data kept)
Iec tot. =   61.03 (32) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6316 (24)
PL1  =  0.07082 (29)
PL2  =  4.58E-4 (6)
PM1  =  0.01137 (6)
PM2  =  7.03E-5 (12)
PN1  =  2.151E-4 (24)

K =  0.6316 (24)
L =  0.07128 (29)
M =  0.01144 (6)
N =  2.151E-4 (24)


------------------------------------------------------------
Input log ft value (ec & beta +): 4.97

Log ft value (ec)    =  4.976 (6)
with log f           =  -0.045 (5)
or f-value           =  0.901 (11)
and log partial T1/2 =  5.0214 (27)

