--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 29-Cu-64 [1+] g.s.  -->  Daughter nucleus: 28-Ni-64 [2+] 1345.75 (5) keV
Calculation of the allowed transition from the electron capture decay of Cu-64.

Transition energy: 329.28 (21) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11620 (21)
PL2/PK =  7.37E-4 (10)
PM1/PK =  0.01874 (8)
PM2/PK =  1.136E-4 (20)
PN1/PK =  3.546E-4 (38)

L/K =  0.11693 (22)
M/K =  0.01886 (8)
N/K =  3.546E-4 (38)


------------------------------
Relative capture probabilities

PK  =  0.88017 (24)
PL1 =  0.10227 (15)
PL2 =  6.48E-4 (9)
PM1 =  0.01650 (7)
PM2 =  10.00E-5 (17)
PN1 =  3.121E-4 (32)

K =  0.88017 (24)
L =  0.10292 (16)
M =  0.01660 (7)
N =  3.121E-4 (32)


------------------------------
Capture branch from input data

Iec =   0.4743 (39) %


---------------------
Capture probabilities

PK  =  0.88017 (24)
PL1  =  0.10227 (15)
PL2  =  6.48E-4 (9)
PM1  =  0.01650 (7)
PM2  =  10.00E-5 (17)
PN1  =  3.121E-4 (32)

K =  0.88017 (24)
L =  0.10292 (16)
M =  0.01660 (7)
N =  3.121E-4 (32)


------------------------------------------------------------
Input log ft value (ec): 5.51

Log ft value (ec)    =  5.509 (7)
with log f           =  -1.475 (6)
or f-value           =  0.03351 (45)
and log partial T1/2 =  6.9841 (36)

