--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 2655.82 (10) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 1747.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11324 (20)
PL2/PK =  0.001288 (12)
PM1/PK =  0.02188 (17)
PM2/PK =  2.552E-4 (7)
PN1/PK =  0.003133 (37)
PN2/PK =  2.557E-5 (16)

L/K =  0.11453 (19)
M/K =  0.02213 (17)
N/K =  0.003159 (37)


------------------------------
Relative capture probabilities

PK  =  0.87733 (30)
PL1 =  0.09935 (14)
PL2 =  0.001130 (11)
PM1 =  0.01920 (14)
PM2 =  2.239E-4 (7)
PN1 =  0.002749 (31)
PN2 =  2.243E-5 (13)

K =  0.87733 (30)
L =  0.10048 (13)
M =  0.01942 (14)
N =  0.002771 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  4.36 (9)
L1/b+ =  0.494 (9)
L2/b+ =  0.00562 (17)
M1/b+ =  0.0955 (15)
M2/b+ =  0.001113 (26)
N1/b+ =  0.01367 (27)
N2/b+ =  1.116E-4 (16)

K/b+ =  4.36 (9)
L/b+ =  0.50 (1)
M/b+ =  0.0966 (15)
N/b+ =  0.01378 (27)

EC/b+ =  4.97 (10)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0170 (17) %   Iec =   0.0142 (17) %   Ib+ =   0.00284 (34) %
Iec      =   0.0142 (17) % (input data kept)
Ib+      =   0.00284 (34) % (input data kept)
Iec tot. =   0.0170 (17) % (input data kept)


---------------------
Capture probabilities

PK  =  0.7305 (25)
PL1  =  0.08272 (31)
PL2  =  9.41E-4 (10)
PM1  =  0.01598 (13)
PM2  =  1.864E-4 (9)
PN1  =  0.002288 (27)
PN2  =  1.868E-5 (13)

K =  0.7305 (25)
L =  0.08366 (31)
M =  0.01617 (13)
N =  0.002307 (27)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.1

Log ft value (ec)    =  6.11 (5)
with log f           =  0.3771 (41)
or f-value           =  2.383 (23)
and log partial T1/2 =  5.73 (5)

