--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3835.8 (5) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 567.2 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11665 (23)
PL2/PK =  0.001305 (13)
PM1/PK =  0.02262 (18)
PM2/PK =  2.597E-4 (8)
PN1/PK =  0.003241 (39)
PN2/PK =  2.603E-5 (16)

L/K =  0.11795 (22)
M/K =  0.02288 (18)
N/K =  0.003267 (39)


------------------------------
Relative capture probabilities

PK  =  0.87405 (34)
PL1 =  0.10195 (16)
PL2 =  0.001141 (12)
PM1 =  0.01977 (15)
PM2 =  2.269E-4 (8)
PN1 =  0.002833 (33)
PN2 =  2.275E-5 (13)

K =  0.87405 (34)
L =  0.10310 (15)
M =  0.02000 (15)
N =  0.002856 (33)


------------------------------
Capture branch from input data

Iec =   8.9E-4 (5) %


---------------------
Capture probabilities

PK  =  0.87405 (34)
PL1  =  0.10195 (16)
PL2  =  0.001141 (12)
PM1  =  0.01977 (15)
PM2  =  2.269E-4 (8)
PN1  =  0.002833 (33)
PN2  =  2.275E-5 (13)

K =  0.87405 (34)
L =  0.10310 (15)
M =  0.02000 (15)
N =  0.002856 (33)


------------------------------------------------------------
Input log ft value (ec): 6.3

Log ft value (ec)    =  6.317 (26)
with log f           =  -0.614 (7)
or f-value           =  0.2431 (41)
and log partial T1/2 =  6.931 (24)

