--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [4+] 2556.3 (7) keV
Calculation of the 2nd forbidden unique transition from the electron capture decay of Rb-82.

Transition energy: 1846.7 (31) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11620 (21)
PL2/PK =  0.001309 (13)
PL3/PK =  9.77E-4 (14)
PM1/PK =  0.02253 (18)
PM2/PK =  2.603E-4 (7)
PM3/PK =  1.761E-4 (9)
PN1/PK =  0.003227 (38)
PM4/PK =  1.495E-7 (32)
PM5/PK =  1.226E-8 (32)
PN2/PK =  2.609E-5 (16)
PN3/PK =  1.394E-5 (20)

L/K =  0.11849 (19)
M/K =  0.02296 (18)
N/K =  0.003267 (38)


------------------------------
Relative capture probabilities

PK  =  0.87358 (31)
PL1 =  0.10151 (15)
PL2 =  0.001144 (11)
PL3 =  8.53E-4 (12)
PM1 =  0.01968 (15)
PM2 =  2.274E-4 (7)
PM3 =  1.538E-4 (9)
PN1 =  0.002819 (32)
PM4 =  1.306E-7 (27)
PM5 =  1.071E-8 (27)
PN2 =  2.279E-5 (13)
PN3 =  1.218E-5 (17)

K =  0.87358 (31)
L =  0.10351 (13)
M =  0.02006 (15)
N =  0.002854 (32)


--------------------------
Capture-to-positron ratios

K/b+ =  47.2 (11)
L1/b+ =  5.48 (12)
L2/b+ =  0.0618 (21)
L3/b+ =  0.0461 (18)
M1/b+ =  1.063 (20)
M2/b+ =  0.01228 (33)
M3/b+ =  0.00831 (24)
N1/b+ =  0.1522 (35)
M4/b+ =  7.05E-6 (23)
M5/b+ =  5.78E-7 (22)
N2/b+ =  0.001231 (22)
N3/b+ =  6.58E-4 (17)

K/b+ =  47.2 (11)
L/b+ =  5.59 (13)
M/b+ =  1.083 (20)
N/b+ =  0.1541 (35)

EC/b+ =  54.0 (13)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   3.0E-4 (12) %   Iec =   2.3E-4 (11) %   Ib+ =   7.E-5 (4) %
Iec      =   2.3E-4 (11) % (input data kept)
Ib+      =   7.E-5 (4) % (input data kept)
Iec tot. =   3.0E-4 (12) % (input data kept)


---------------------
Capture probabilities

PK  =  0.85769 (48)
PL1  =  0.09967 (15)
PL2  =  0.001123 (11)
PL3  =  8.38E-4 (12)
PM1  =  0.01932 (14)
PM2  =  2.232E-4 (7)
PM3  =  1.510E-4 (9)
PN1  =  0.002768 (32)
PM4  =  1.283E-7 (27)
PM5  =  1.052E-8 (27)
PN2  =  2.238E-5 (13)
PN3  =  1.196E-5 (16)

K =  0.85769 (48)
L =  0.10163 (14)
M =  0.01970 (14)
N =  0.002802 (32)


------------------------------------------------------------
Input log ft value (ec & beta +): 10

Log ft value (ec)    =  10.16 (21)
with log f           =  2.646 (7)
or f-value           =  443 (7)
and log partial T1/2 =  7.52 (21)

