--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [4+] 1820.6 (4) keV
Calculation of the 2nd forbidden unique transition from the electron capture decay of Rb-82.

Transition energy: 2582.4 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11489 (21)
PL2/PK =  0.001308 (12)
PL3/PK =  4.99E-4 (7)
PM1/PK =  0.02224 (17)
PM2/PK =  2.598E-4 (7)
PM3/PK =  8.987E-5 (38)
PN1/PK =  0.003185 (37)
PM4/PK =  7.63E-8 (16)
PM5/PK =  3.20E-9 (8)
PN2/PK =  2.604E-5 (16)
PN3/PK =  7.12E-6 (9)

L/K =  0.11670 (19)
M/K =  0.02259 (17)
N/K =  0.003219 (38)


------------------------------
Relative capture probabilities

PK  =  0.87527 (31)
PL1 =  0.10056 (14)
PL2 =  0.001145 (11)
PL3 =  4.37E-4 (6)
PM1 =  0.01947 (14)
PM2 =  2.274E-4 (7)
PM3 =  7.866E-5 (36)
PN1 =  0.002788 (32)
PM4 =  6.68E-8 (13)
PM5 =  2.80E-9 (7)
PN2 =  2.279E-5 (13)
PN3 =  6.23E-6 (8)

K =  0.87527 (31)
L =  0.10214 (13)
M =  0.01977 (14)
N =  0.002817 (32)


--------------------------
Capture-to-positron ratios

K/b+ =  2.943 (42)
L1/b+ =  0.3381 (43)
L2/b+ =  0.00385 (9)
L3/b+ =  0.001468 (40)
M1/b+ =  0.0654 (6)
M2/b+ =  7.64E-4 (13)
M3/b+ =  2.644E-4 (49)
N1/b+ =  0.00937 (12)
M4/b+ =  2.245E-7 (49)
M5/b+ =  9.41E-9 (24)
N2/b+ =  7.66E-5 (6)
N3/b+ =  2.094E-5 (31)

K/b+ =  2.943 (42)
L/b+ =  0.3434 (44)
M/b+ =  0.0665 (6)
N/b+ =  0.00947 (13)

EC/b+ =  3.362 (47)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.0E-4 (8) %   Iec =   3.E-5 (3) %   Ib+ =   7E-5 (7) %
Iec      =   3.E-5 (3) % (input data kept)
Ib+      =   7E-5 (7) % (input data kept)
Iec tot. =   1.0E-4 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6746 (22)
PL1  =  0.07751 (27)
PL2  =  8.83E-4 (9)
PL3  =  3.365E-4 (47)
PM1  =  0.01500 (12)
PM2  =  1.752E-4 (8)
PM3  =  6.063E-5 (34)
PN1  =  0.002149 (25)
PM4  =  5.15E-8 (10)
PM5  =  2.16E-9 (5)
PN2  =  1.756E-5 (12)
PN3  =  4.80E-6 (6)

K =  0.6746 (22)
L =  0.07872 (27)
M =  0.01524 (12)
N =  0.002171 (26)


------------------------------------------------------------
Input log ft value (ec & beta +): 11.5

Log ft value (ec)    =  11.93 (43)
with log f           =  3.526 (6)
or f-value           =  3356 (44)
and log partial T1/2 =  8.40 (43)

