--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3355.32 (19) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 1047.7 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11431 (21)
PL2/PK =  0.001288 (12)
PM1/PK =  0.02211 (17)
PM2/PK =  2.555E-4 (7)
PN1/PK =  0.003167 (37)
PN2/PK =  2.560E-5 (16)

L/K =  0.1156 (2)
M/K =  0.02237 (17)
N/K =  0.003193 (37)


------------------------------
Relative capture probabilities

PK  =  0.87630 (31)
PL1 =  0.10017 (15)
PL2 =  0.001128 (11)
PM1 =  0.01938 (14)
PM2 =  2.239E-4 (7)
PN1 =  0.002775 (32)
PN2 =  2.244E-5 (13)

K =  0.87630 (31)
L =  0.10130 (14)
M =  0.01960 (14)
N =  0.002798 (32)


--------------------------
Capture-to-positron ratios

K/b+ =  1.1E7 (11)
L1/b+ =  1.3E6 (12)
L2/b+ =  1.4E4 (14)
M1/b+ =  2.4E5 (24)
M2/b+ =  2.8E3 (28)
N1/b+ =  3.5E4 (34)
N2/b+ =  2.8E2 (27)

K/b+ =  1.1E7 (11)
L/b+ =  1.3E6 (12)
M/b+ =  2.5E5 (24)
N/b+ =  3.5E4 (35)

EC/b+ =  1.3E7 (12)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.00134 (13) %   Iec =   0.00134 (13) %   Ib+ =   0 %
Iec      =   0.00134 (13) % (input data kept)
Ib+      =   0 % (input data kept)
Iec tot. =   0.00134 (13) % (input data kept)


---------------------
Capture probabilities

PK  =  0.87630 (31)
PL1  =  0.10017 (15)
PL2  =  0.001128 (11)
PM1  =  0.01938 (14)
PM2  =  2.239E-4 (7)
PN1  =  0.002775 (32)
PN2  =  2.244E-5 (13)

K =  0.87630 (31)
L =  0.10130 (14)
M =  0.01960 (14)
N =  0.002798 (32)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.7

Log ft value (ec)    =  6.681 (42)
with log f           =  -0.072 (5)
or f-value           =  0.847 (10)
and log partial T1/2 =  6.753 (42)

