--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [**] 2509.0 (5) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 1894 (3) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11312 (20)
PL2/PK =  0.001289 (12)
PM1/PK =  0.02185 (17)
PM2/PK =  2.554E-4 (7)
PN1/PK =  0.003129 (37)
PN2/PK =  2.559E-5 (16)

L/K =  0.11441 (19)
M/K =  0.02211 (17)
N/K =  0.003155 (37)


------------------------------
Relative capture probabilities

PK  =  0.87745 (30)
PL1 =  0.09925 (14)
PL2 =  0.001131 (11)
PM1 =  0.01917 (14)
PM2 =  2.241E-4 (7)
PN1 =  0.002746 (31)
PN2 =  2.245E-5 (13)

K =  0.87745 (30)
L =  0.10038 (13)
M =  0.01940 (14)
N =  0.002768 (31)


--------------------------
Capture-to-positron ratios

K/b+ =  2.320 (42)
L1/b+ =  0.2624 (43)
L2/b+ =  0.00299 (8)
M1/b+ =  0.0507 (7)
M2/b+ =  5.92E-4 (12)
N1/b+ =  0.00726 (13)
N2/b+ =  5.94E-5 (7)

K/b+ =  2.320 (42)
L/b+ =  0.2654 (44)
M/b+ =  0.0513 (7)
N/b+ =  0.00732 (13)

EC/b+ =  2.644 (47)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.0015 (7) %   Iec =   0.0011 (6) %   Ib+ =   4.1E-4 (25) %
Iec      =   0.0011 (6) % (input data kept)
Ib+      =   4.1E-4 (25) % (input data kept)
Iec tot. =   0.0015 (7) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6367 (31)
PL1  =  0.07202 (37)
PL2  =  8.20E-4 (9)
PM1  =  0.01391 (12)
PM2  =  1.626E-4 (9)
PN1  =  0.001992 (25)
PN2  =  1.629E-5 (12)

K =  0.6367 (31)
L =  0.07284 (37)
M =  0.01408 (12)
N =  0.002008 (25)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.4

Log ft value (ec)    =  7.29 (24)
with log f           =  0.4478 (40)
or f-value           =  2.804 (26)
and log partial T1/2 =  6.84 (24)

