--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3457.5 (7) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 945.5 (31) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11461 (21)
PL2/PK =  0.001289 (12)
PM1/PK =  0.02218 (17)
PM2/PK =  2.559E-4 (7)
PN1/PK =  0.003176 (37)
PN2/PK =  2.564E-5 (16)

L/K =  0.1159 (2)
M/K =  0.02243 (17)
N/K =  0.003202 (38)


------------------------------
Relative capture probabilities

PK  =  0.87601 (31)
PL1 =  0.10040 (15)
PL2 =  0.001129 (11)
PM1 =  0.01943 (15)
PM2 =  2.241E-4 (7)
PN1 =  0.002783 (32)
PN2 =  2.246E-5 (13)

K =  0.87601 (31)
L =  0.10153 (14)
M =  0.01965 (14)
N =  0.002805 (32)


------------------------------
Capture branch from input data

Iec =   1.11E-4 (23) %


---------------------
Capture probabilities

PK  =  0.87601 (31)
PL1  =  0.10040 (15)
PL2  =  0.001129 (11)
PM1  =  0.01943 (15)
PM2  =  2.241E-4 (7)
PN1  =  0.002783 (32)
PN2  =  2.246E-5 (13)

K =  0.87601 (31)
L =  0.10153 (14)
M =  0.01965 (14)
N =  0.002805 (32)


------------------------------------------------------------
Input log ft value (ec): 7.7

Log ft value (ec)    =  7.67 (9)
with log f           =  -0.162 (6)
or f-value           =  0.688 (9)
and log partial T1/2 =  7.83 (9)

