--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [**] 3741.96 (8) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 661 (3) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11592 (22)
PL2/PK =  0.001299 (13)
PM1/PK =  0.02246 (18)
PM2/PK =  2.581E-4 (8)
PN1/PK =  0.003218 (38)
PN2/PK =  2.588E-5 (16)

L/K =  0.11722 (21)
M/K =  0.02272 (18)
N/K =  0.003244 (38)


------------------------------
Relative capture probabilities

PK  =  0.87475 (33)
PL1 =  0.10140 (16)
PL2 =  0.001136 (11)
PM1 =  0.01965 (15)
PM2 =  2.258E-4 (8)
PN1 =  0.002815 (32)
PN2 =  2.264E-5 (13)

K =  0.87475 (33)
L =  0.10253 (15)
M =  0.01988 (15)
N =  0.002838 (32)


------------------------------
Capture branch from input data

Iec =   0.0036 (6) %


---------------------
Capture probabilities

PK  =  0.87475 (33)
PL1  =  0.10140 (16)
PL2  =  0.001136 (11)
PM1  =  0.01965 (15)
PM2  =  2.258E-4 (8)
PN1  =  0.002815 (32)
PN2  =  2.264E-5 (13)

K =  0.87475 (33)
L =  0.10253 (15)
M =  0.01988 (15)
N =  0.002838 (32)


------------------------------------------------------------
Input log ft value (ec): 5.9

Log ft value (ec)    =  5.85 (7)
with log f           =  -0.478 (7)
or f-value           =  0.332 (5)
and log partial T1/2 =  6.32 (7)

