--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 37-Rb-82 [1+] g.s.  -->  Daughter nucleus: 36-Kr-82 [1+] 3815.1 (10) keV
This transition from the electron capture decay of Rb-82 is calculated as allowed.

Transition energy: 587.9 (32) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11647 (23)
PL2/PK =  0.001304 (13)
PM1/PK =  0.02258 (18)
PM2/PK =  2.593E-4 (8)
PN1/PK =  0.003236 (39)
PN2/PK =  2.599E-5 (16)

L/K =  0.11777 (22)
M/K =  0.02284 (18)
N/K =  0.003262 (39)


------------------------------
Relative capture probabilities

PK  =  0.87422 (33)
PL1 =  0.10182 (16)
PL2 =  0.001140 (12)
PM1 =  0.01974 (15)
PM2 =  2.267E-4 (8)
PN1 =  0.002829 (33)
PN2 =  2.272E-5 (13)

K =  0.87422 (33)
L =  0.10296 (15)
M =  0.01997 (15)
N =  0.002851 (33)


------------------------------
Capture branch from input data

Iec =   0.0019 (8) %


---------------------
Capture probabilities

PK  =  0.87422 (33)
PL1  =  0.10182 (16)
PL2  =  0.001140 (12)
PM1  =  0.01974 (15)
PM2  =  2.267E-4 (8)
PN1  =  0.002829 (33)
PN2  =  2.272E-5 (13)

K =  0.87422 (33)
L =  0.10296 (15)
M =  0.01997 (15)
N =  0.002851 (33)


------------------------------------------------------------
Input log ft value (ec): 5.6

Log ft value (ec)    =  6.02 (18)
with log f           =  -0.582 (7)
or f-value           =  0.2616 (44)
and log partial T1/2 =  6.60 (18)

