--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 39-Y-88 [4-] g.s.  -->  Daughter nucleus: 38-Sr-88 [2+] 3218.489 (22) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Y-88.

Transition energy: 404.1 (15) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13378 (29)
PL2/PK =  0.001679 (22)
PL3/PK =  0.00773 (16)
PM1/PK =  0.02602 (15)
PM2/PK =  3.44E-4 (6)
PM3/PK =  0.001439 (36)
PN1/PK =  0.00430 (5)
PM4/PK =  1.67E-6 (6)
PN2/PK =  4.70E-5 (12)
PN3/PK =  1.65E-4 (6)
PO1/PK =  4.71E-4 (9)

L/K =  0.14319 (47)
M/K =  0.02781 (19)
N/K =  0.00452 (6)
O/K =  4.71E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.8504 (5)
PL1 =  0.11376 (17)
PL2 =  0.001428 (18)
PL3 =  0.00657 (13)
PM1 =  0.02213 (11)
PM2 =  2.927E-4 (47)
PM3 =  0.001223 (30)
PN1 =  0.003660 (41)
PM4 =  1.421E-6 (47)
PN2 =  3.99E-5 (10)
PN3 =  1.41E-4 (5)
PO1 =  4.01E-4 (8)

K =  0.8504 (5)
L =  0.12176 (32)
M =  0.02365 (15)
N =  0.003841 (47)
O =  4.01E-4 (8)


------------------------------
Capture branch from input data

Iec =   0.023 (4) %


---------------------
Capture probabilities

PK  =  0.8504 (5)
PL1  =  0.11376 (17)
PL2  =  0.001428 (18)
PL3  =  0.00657 (13)
PM1  =  0.02213 (11)
PM2  =  2.927E-4 (47)
PM3  =  0.001223 (30)
PN1  =  0.003660 (41)
PM4  =  1.421E-6 (47)
PN2  =  3.99E-5 (10)
PN3  =  1.41E-4 (5)
PO1  =  4.01E-4 (8)

K =  0.8504 (5)
L =  0.12176 (32)
M =  0.02365 (15)
N =  0.003841 (47)
O =  4.01E-4 (8)


------------------------------------------------------------
Input log ft value (ec): 9.5

Log ft value (ec)    =  9.55 (8)
with log f           =  -1.056 (14)
or f-value           =  0.0879 (28)
and log partial T1/2 =  10.60 (8)

