--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-68 [1+] g.s.  -->  Daughter nucleus: 30-Zn-68 [2+] 1883.19 (6) keV
Calculation of the allowed transition from the electron capture decay of Ga-68.

Transition energy: 1037.9 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11196 (16)
PL2/PK =  8.38E-4 (31)
PM1/PK =  0.01855 (7)
PM2/PK =  1.35E-4 (5)
PN1/PK =  0.001487 (32)

L/K =  0.11280 (19)
M/K =  0.01868 (7)
N/K =  0.001487 (32)


------------------------------
Relative capture probabilities

PK  =  0.88264 (23)
PL1 =  0.09882 (12)
PL2 =  7.40E-4 (27)
PM1 =  0.01637 (6)
PM2 =  1.195E-4 (47)
PN1 =  0.001313 (28)

K =  0.88264 (23)
L =  0.09956 (14)
M =  0.01649 (6)
N =  0.001313 (28)


--------------------------
Capture-to-positron ratios

K/b+ =  4.3E7 (25)
L1/b+ =  4.8E6 (28)
L2/b+ =  3.6E4 (20)
M1/b+ =  8.0E5 (46)
M2/b+ =  5.9E3 (33)
N1/b+ =  6.4E4 (35)

K/b+ =  4.3E7 (25)
L/b+ =  4.9E6 (28)
M/b+ =  8.1E5 (46)
N/b+ =  6.4E4 (35)

EC/b+ =  4.9E7 (28)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.234 (5) %   Iec =   0.234 (5) %   Ib+ =   0 %
Iec      =   0.234 (5) % (input data kept)
Ib+      =   0 % (input data kept)
Iec tot. =   0.234 (5) % (input data kept)


---------------------
Capture probabilities

PK  =  0.88264 (23)
PL1  =  0.09882 (12)
PL2  =  7.40E-4 (27)
PM1  =  0.01637 (6)
PM2  =  1.195E-4 (47)
PN1  =  0.001313 (28)

K =  0.88264 (23)
L =  0.09956 (14)
M =  0.01649 (6)
N =  0.001313 (28)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.9

Log ft value (ec)    =  5.877 (16)
with log f           =  -0.364 (13)
or f-value           =  0.433 (13)
and log partial T1/2 =  6.240 (9)

