--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [3-] 2834.898 (20) keV
Calculation of the allowed transition from the electron capture decay of I-124.

Transition energy: 324.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15077 (38)
PL2/PK =  0.003895 (15)
PM1/PK =  0.03354 (21)
PM2/PK =  9.506E-4 (20)
PN1/PK =  0.00756 (8)
PN2/PK =  2.007E-4 (16)
PO1/PK =  0.001244 (23)
PO2/PK =  2.080E-5 (34)

L/K =  0.15467 (37)
M/K =  0.03449 (21)
N/K =  0.00777 (9)
O/K =  0.001265 (23)


------------------------------
Relative capture probabilities

PK  =  0.83459 (48)
PL1 =  0.12583 (24)
PL2 =  0.003251 (13)
PM1 =  0.02799 (16)
PM2 =  7.933E-4 (12)
PN1 =  0.00631 (7)
PN2 =  1.675E-4 (12)
PO1 =  0.001039 (18)
PO2 =  1.736E-5 (27)

K =  0.83459 (48)
L =  0.12909 (23)
M =  0.02879 (16)
N =  0.00648 (7)
O =  0.001056 (19)


------------------------------
Capture branch from input data

Iec =   4.22 (7) %


---------------------
Capture probabilities

PK  =  0.83459 (48)
PL1  =  0.12583 (24)
PL2  =  0.003251 (13)
PM1  =  0.02799 (16)
PM2  =  7.933E-4 (12)
PN1  =  0.00631 (7)
PN2  =  1.675E-4 (12)
PO1  =  0.001039 (18)
PO2  =  1.736E-5 (27)

K =  0.83459 (48)
L =  0.12909 (23)
M =  0.02879 (16)
N =  0.00648 (7)
O =  0.001056 (19)


------------------------------------------------------------
Input log ft value (ec): 6.438

Log ft value (ec)    =  6.438 (12)
with log f           =  -0.494 (9)
or f-value           =  0.320 (7)
and log partial T1/2 =  6.932 (7)

