--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [1-] 2747.04 (4) keV
Calculation of the allowed transition from the electron capture decay of I-124.

Transition energy: 412.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14505 (30)
PL2/PK =  0.003749 (13)
PM1/PK =  0.03210 (18)
PM2/PK =  9.105E-4 (15)
PN1/PK =  0.00723 (8)
PN2/PK =  1.921E-4 (14)
PO1/PK =  0.001189 (21)
PO2/PK =  1.990E-5 (32)

L/K =  0.14880 (29)
M/K =  0.03301 (18)
N/K =  0.00742 (8)
O/K =  0.001209 (21)


------------------------------
Relative capture probabilities

PK  =  0.84002 (40)
PL1 =  0.12185 (19)
PL2 =  0.003149 (11)
PM1 =  0.02697 (14)
PM2 =  7.649E-4 (9)
PN1 =  0.00608 (6)
PN2 =  1.613E-4 (11)
PO1 =  9.99E-4 (17)
PO2 =  1.672E-5 (26)

K =  0.84002 (40)
L =  0.12499 (18)
M =  0.02773 (14)
N =  0.00624 (6)
O =  0.001016 (17)


------------------------------
Capture branch from input data

Iec =   0.577 (18) %


---------------------
Capture probabilities

PK  =  0.84002 (40)
PL1  =  0.12185 (19)
PL2  =  0.003149 (11)
PM1  =  0.02697 (14)
PM2  =  7.649E-4 (9)
PN1  =  0.00608 (6)
PN2  =  1.613E-4 (11)
PO1  =  9.99E-4 (17)
PO2  =  1.672E-5 (26)

K =  0.84002 (40)
L =  0.12499 (18)
M =  0.02773 (14)
N =  0.00624 (6)
O =  0.001016 (17)


------------------------------------------------------------
Input log ft value (ec): 7.527

Log ft value (ec)    =  7.527 (16)
with log f           =  -0.269 (8)
or f-value           =  0.538 (9)
and log partial T1/2 =  7.796 (14)

