--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2521.33 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 638.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13810 (23)
PL2/PK =  0.003577 (11)
PM1/PK =  0.03036 (16)
PM2/PK =  8.631E-4 (10)
PN1/PK =  0.00683 (7)
PN2/PK =  1.818E-4 (12)
PO1/PK =  0.001123 (19)
PO2/PK =  1.884E-5 (29)

L/K =  0.14168 (22)
M/K =  0.03122 (16)
N/K =  0.00701 (7)
O/K =  0.001142 (20)


------------------------------
Relative capture probabilities

PK  =  0.84670 (34)
PL1 =  0.11693 (15)
PL2 =  0.003028 (10)
PM1 =  0.02571 (12)
PM2 =  7.308E-4 (6)
PN1 =  0.00578 (6)
PN2 =  1.54E-4 (1)
PO1 =  9.51E-4 (16)
PO2 =  1.595E-5 (24)

K =  0.84670 (34)
L =  0.11996 (14)
M =  0.02644 (12)
N =  0.00594 (6)
O =  9.67E-4 (16)


------------------------------
Capture branch from input data

Iec =   0.173 (6) %


---------------------
Capture probabilities

PK  =  0.84670 (34)
PL1  =  0.11693 (15)
PL2  =  0.003028 (10)
PM1  =  0.02571 (12)
PM2  =  7.308E-4 (6)
PN1  =  0.00578 (6)
PN2  =  1.54E-4 (1)
PO1  =  9.51E-4 (16)
PO2  =  1.595E-5 (24)

K =  0.84670 (34)
L =  0.11996 (14)
M =  0.02644 (12)
N =  0.00594 (6)
O =  9.67E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 8.45

Log ft value (ec)    =  8.450 (16)
with log f           =  0.131 (6)
or f-value           =  1.352 (19)
and log partial T1/2 =  8.319 (15)

