--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2945.59 (6) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 214.0 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1664 (7)
PL2/PK =  0.004296 (23)
PM1/PK =  0.03748 (30)
PM2/PK =  0.0010612 (41)
PN1/PK =  0.00847 (11)
PN2/PK =  2.246E-4 (22)
PO1/PK =  0.001395 (28)
PO2/PK =  2.328E-5 (42)

L/K =  0.1707 (7)
M/K =  0.03854 (30)
N/K =  0.00870 (11)
O/K =  0.001418 (28)


------------------------------
Relative capture probabilities

PK  =  0.8201 (8)
PL1 =  0.13644 (43)
PL2 =  0.003524 (19)
PM1 =  0.03074 (22)
PM2 =  8.703E-4 (26)
PN1 =  0.00695 (8)
PN2 =  1.842E-4 (16)
PO1 =  0.001144 (22)
PO2 =  1.909E-5 (33)

K =  0.8201 (8)
L =  0.13996 (43)
M =  0.03161 (22)
N =  0.00713 (9)
O =  0.001163 (22)


------------------------------
Capture branch from input data

Iec =   0.029 (3) %


---------------------
Capture probabilities

PK  =  0.8201 (8)
PL1  =  0.13644 (43)
PL2  =  0.003524 (19)
PM1  =  0.03074 (22)
PM2  =  8.703E-4 (26)
PN1  =  0.00695 (8)
PN2  =  1.842E-4 (16)
PO1  =  0.001144 (22)
PO2  =  1.909E-5 (33)

K =  0.8201 (8)
L =  0.13996 (43)
M =  0.03161 (22)
N =  0.00713 (9)
O =  0.001163 (22)


------------------------------------------------------------
Input log ft value (ec): 8.197

Log ft value (ec)    =  8.197 (47)
with log f           =  -0.898 (12)
or f-value           =  0.1264 (36)
and log partial T1/2 =  9.095 (45)

