--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2322.95 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 836.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13526 (21)
PL2/PK =  0.00351 (1)
PM1/PK =  0.02965 (15)
PM2/PK =  8.447E-4 (9)
PN1/PK =  0.00667 (7)
PN2/PK =  1.779E-4 (12)
PO1/PK =  0.001096 (19)
PO2/PK =  1.842E-5 (28)

L/K =  0.13877 (20)
M/K =  0.03049 (15)
N/K =  0.00684 (7)
O/K =  0.001114 (19)


------------------------------
Relative capture probabilities

PK  =  0.84946 (32)
PL1 =  0.11490 (14)
PL2 =  0.002982 (9)
PM1 =  0.02519 (12)
PM2 =  7.1751E-4 (48)
PN1 =  0.00566 (5)
PN2 =  1.511E-4 (10)
PO1 =  9.31E-4 (16)
PO2 =  1.565E-5 (23)

K =  0.84946 (32)
L =  0.11788 (13)
M =  0.02590 (12)
N =  0.00581 (6)
O =  9.47E-4 (16)


------------------------------
Capture branch from input data

Iec =   0.201 (12) %


---------------------
Capture probabilities

PK  =  0.84946 (32)
PL1  =  0.11490 (14)
PL2  =  0.002982 (9)
PM1  =  0.02519 (12)
PM2  =  7.1751E-4 (48)
PN1  =  0.00566 (5)
PN2  =  1.511E-4 (10)
PO1  =  9.31E-4 (16)
PO2  =  1.565E-5 (23)

K =  0.84946 (32)
L =  0.11788 (13)
M =  0.02590 (12)
N =  0.00581 (6)
O =  9.47E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 8.63

Log ft value (ec)    =  8.630 (26)
with log f           =  0.375 (5)
or f-value           =  2.374 (30)
and log partial T1/2 =  8.254 (26)

