--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [3-] 2693.679 (5) keV
Calculation of the allowed transition from the electron capture decay of I-124.

Transition energy: 465.9 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14274 (27)
PL2/PK =  0.003691 (12)
PM1/PK =  0.03152 (17)
PM2/PK =  8.945E-4 (13)
PN1/PK =  0.00710 (7)
PN2/PK =  1.886E-4 (13)
PO1/PK =  0.001167 (20)
PO2/PK =  1.954E-5 (31)

L/K =  0.14643 (27)
M/K =  0.03242 (17)
N/K =  0.00729 (8)
O/K =  0.001187 (21)


------------------------------
Relative capture probabilities

PK  =  0.84223 (38)
PL1 =  0.12022 (18)
PL2 =  0.003109 (11)
PM1 =  0.02655 (13)
PM2 =  7.534E-4 (8)
PN1 =  0.00598 (6)
PN2 =  1.589E-4 (11)
PO1 =  9.83E-4 (17)
PO2 =  1.646E-5 (25)

K =  0.84223 (38)
L =  0.12333 (17)
M =  0.02730 (13)
N =  0.00614 (6)
O =  10.00E-4 (17)


------------------------------
Capture branch from input data

Iec =   0.94 (3) %


---------------------
Capture probabilities

PK  =  0.84223 (38)
PL1  =  0.12022 (18)
PL2  =  0.003109 (11)
PM1  =  0.02655 (13)
PM2  =  7.534E-4 (8)
PN1  =  0.00598 (6)
PN2  =  1.589E-4 (11)
PO1  =  9.83E-4 (17)
PO2  =  1.646E-5 (25)

K =  0.84223 (38)
L =  0.12333 (17)
M =  0.02730 (13)
N =  0.00614 (6)
O =  10.00E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 7.427

Log ft value (ec)    =  7.427 (16)
with log f           =  -0.157 (7)
or f-value           =  0.697 (11)
and log partial T1/2 =  7.584 (14)

