--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [3-] 2293.711 (3) keV
Calculation of the allowed transition from the electron capture decay of I-124.

Transition energy: 865.9 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13495 (21)
PL2/PK =  0.003503 (10)
PM1/PK =  0.02957 (15)
PM2/PK =  8.428E-4 (9)
PN1/PK =  0.00665 (7)
PN2/PK =  1.775E-4 (12)
PO1/PK =  0.001093 (19)
PO2/PK =  1.838E-5 (28)

L/K =  0.13846 (20)
M/K =  0.03042 (15)
N/K =  0.00683 (7)
O/K =  0.001112 (19)


------------------------------
Relative capture probabilities

PK  =  0.84975 (32)
PL1 =  0.11468 (13)
PL2 =  0.002977 (9)
PM1 =  0.02513 (12)
PM2 =  7.1615E-4 (48)
PN1 =  0.00565 (5)
PN2 =  1.508E-4 (9)
PO1 =  9.29E-4 (15)
PO2 =  1.562E-5 (23)

K =  0.84975 (32)
L =  0.11765 (13)
M =  0.02585 (12)
N =  0.00580 (6)
O =  9.45E-4 (16)


------------------------------
Capture branch from input data

Iec =   11.54 (25) %


---------------------
Capture probabilities

PK  =  0.84975 (32)
PL1  =  0.11468 (13)
PL2  =  0.002977 (9)
PM1  =  0.02513 (12)
PM2  =  7.1615E-4 (48)
PN1  =  0.00565 (5)
PN2  =  1.508E-4 (9)
PO1  =  9.29E-4 (15)
PO2  =  1.562E-5 (23)

K =  0.84975 (32)
L =  0.11765 (13)
M =  0.02585 (12)
N =  0.00580 (6)
O =  9.45E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 6.901

Log ft value (ec)    =  6.901 (11)
with log f           =  0.406 (5)
or f-value           =  2.549 (31)
and log partial T1/2 =  6.495 (9)

