--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] 1882.92 (3) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 1276.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13793 (21)
PL2/PK =  0.003583 (10)
PL3/PK =  0.001303 (7)
PM1/PK =  0.03032 (15)
PM2/PK =  8.647E-4 (9)
PM3/PK =  2.973E-4 (14)
PN1/PK =  0.00682 (7)
PM4/PK =  8.28E-7 (12)
PN2/PK =  1.822E-4 (12)
PN3/PK =  5.55E-5 (6)
PO1/PK =  0.001122 (19)
PN4/PK =  1.327E-7 (31)
PO2/PK =  1.887E-5 (29)
PO3/PK =  3.06E-6 (7)

L/K =  0.14281 (20)
M/K =  0.03149 (16)
N/K =  0.00706 (7)
O/K =  0.001144 (19)


------------------------------
Relative capture probabilities

PK  =  0.84566 (32)
PL1 =  0.11664 (13)
PL2 =  0.00303 (1)
PL3 =  0.001101 (6)
PM1 =  0.02564 (12)
PM2 =  7.3126E-4 (47)
PM3 =  2.514E-4 (11)
PN1 =  0.00577 (6)
PM4 =  7.0E-7 (1)
PN2 =  1.541E-4 (10)
PN3 =  4.693E-5 (49)
PO1 =  9.49E-4 (16)
PN4 =  1.122E-7 (25)
PO2 =  1.596E-5 (24)
PO3 =  2.59E-6 (6)

K =  0.84566 (32)
L =  0.12077 (13)
M =  0.02663 (12)
N =  0.00597 (6)
O =  9.67E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  1.47E4 (7)
L1/b+ =  2.03E3 (9)
L2/b+ =  52.8 (26)
L3/b+ =  19.2 (10)
M1/b+ =  447 (18)
M2/b+ =  12.8 (6)
M3/b+ =  4.38 (21)
N1/b+ =  100.6 (40)
M4/b+ =  0.0122 (5)
N2/b+ =  2.69 (11)
N3/b+ =  0.818 (34)
O1/b+ =  16.5 (8)
N4/b+ =  0.00196 (10)
O2/b+ =  0.278 (12)
O3/b+ =  0.0451 (23)

K/b+ =  1.47E4 (7)
L/b+ =  2.11E3 (9)
M/b+ =  464 (19)
N/b+ =  104.1 (41)
O/b+ =  16.9 (8)

EC/b+ =  1.74E4 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.025 (16) %   Iec =   0.025 (16) %   Ib+ =   1.5E-6 (9) %
Iec      =   0.025 (16) % (input data kept)
Ib+      =   1.5E-6 (9) % (input data kept)
Iec tot. =   0.025 (16) % (input data kept)


---------------------
Capture probabilities

PK  =  0.84562 (32)
PL1  =  0.11663 (13)
PL2  =  0.00303 (1)
PL3  =  0.001101 (6)
PM1  =  0.02564 (12)
PM2  =  7.3121E-4 (47)
PM3  =  2.514E-4 (11)
PN1  =  0.00577 (6)
PM4  =  7.0E-7 (1)
PN2  =  1.541E-4 (10)
PN3  =  4.692E-5 (49)
PO1  =  9.49E-4 (16)
PN4  =  1.122E-7 (25)
PO2  =  1.596E-5 (24)
PO3  =  2.59E-6 (6)

K =  0.84562 (32)
L =  0.12077 (13)
M =  0.02662 (12)
N =  0.00597 (6)
O =  9.67E-4 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.69

Log ft value (ec)    =  10.69 (28)
with log f           =  1.530 (6)
or f-value           =  33.89 (47)
and log partial T1/2 =  9.16 (28)

