--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 1325.5131 (24) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 1834.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13052 (19)
PL2/PK =  0.003423 (9)
PM1/PK =  0.02847 (14)
PM2/PK =  8.198E-4 (8)
PN1/PK =  0.00639 (6)
PN2/PK =  1.725E-4 (11)
PO1/PK =  0.001051 (18)
PO2/PK =  1.786E-5 (27)

L/K =  0.13394 (18)
M/K =  0.02929 (14)
N/K =  0.00657 (6)
O/K =  0.001069 (18)


------------------------------
Relative capture probabilities

PK  =  0.85407 (29)
PL1 =  0.11147 (12)
PL2 =  0.002924 (9)
PM1 =  0.02431 (11)
PM2 =  7.0020E-4 (41)
PN1 =  0.00546 (5)
PN2 =  1.473E-4 (9)
PO1 =  8.98E-4 (15)
PO2 =  1.526E-5 (23)

K =  0.85407 (29)
L =  0.11440 (11)
M =  0.02501 (11)
N =  0.00561 (5)
O =  9.13E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  16.23 (27)
L1/b+ =  2.118 (32)
L2/b+ =  0.0555 (11)
M1/b+ =  0.462 (5)
M2/b+ =  0.01330 (21)
N1/b+ =  0.1038 (10)
N2/b+ =  0.002799 (28)
O1/b+ =  0.01706 (29)
O2/b+ =  2.899E-4 (44)

K/b+ =  16.23 (27)
L/b+ =  2.174 (33)
M/b+ =  0.475 (6)
N/b+ =  0.1066 (11)
O/b+ =  0.01735 (29)

EC/b+ =  19.00 (31)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   5.72 (18) %   Iec =   5.43 (18) %   Ib+ =   0.287 (10) %
Iec      =   5.43 (18) % (input data kept)
Ib+      =   0.287 (10) % (input data kept)
Iec tot. =   5.72 (18) % (input data kept)


---------------------
Capture probabilities

PK  =  0.8114 (7)
PL1  =  0.10590 (14)
PL2  =  0.002778 (9)
PM1  =  0.02310 (11)
PM2  =  6.652E-4 (7)
PN1  =  0.00519 (5)
PN2  =  1.399E-4 (9)
PO1  =  8.53E-4 (14)
PO2  =  1.449E-5 (21)

K =  0.8114 (7)
L =  0.10868 (14)
M =  0.02376 (11)
N =  0.00533 (5)
O =  8.67E-4 (14)


------------------------------------------------------------
Input log ft value (ec & beta +): 7.897

Log ft value (ec)    =  7.896 (15)
with log f           =  1.0740 (43)
or f-value           =  11.86 (12)
and log partial T1/2 =  6.822 (14)

