--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [4+] 2483.362 (13) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 676.2 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14899 (28)
PL2/PK =  0.003848 (12)
PL3/PK =  0.005018 (42)
PM1/PK =  0.03311 (18)
PM2/PK =  9.381E-4 (13)
PM3/PK =  0.001151 (9)
PN1/PK =  0.00747 (8)
PM4/PK =  3.21E-6 (6)
PN2/PK =  1.980E-4 (14)
PN3/PK =  2.15E-4 (3)
PO1/PK =  0.001228 (21)
PN4/PK =  5.14E-7 (13)
PO2/PK =  2.052E-5 (32)
PO3/PK =  1.187E-5 (30)

L/K =  0.15785 (29)
M/K =  0.03520 (19)
N/K =  0.00788 (8)
O/K =  0.001260 (22)


------------------------------
Relative capture probabilities

PK  =  0.83181 (40)
PL1 =  0.12393 (17)
PL2 =  0.003201 (11)
PL3 =  0.004174 (36)
PM1 =  0.02754 (14)
PM2 =  7.803E-4 (7)
PM3 =  9.57E-4 (7)
PN1 =  0.00621 (6)
PM4 =  2.668E-6 (45)
PN2 =  1.647E-4 (11)
PN3 =  1.789E-4 (24)
PO1 =  0.001021 (17)
PN4 =  4.28E-7 (11)
PO2 =  1.707E-5 (26)
PO3 =  9.87E-6 (24)

K =  0.83181 (40)
L =  0.13130 (18)
M =  0.02928 (14)
N =  0.00655 (7)
O =  0.001048 (18)


------------------------------
Capture branch from input data

Iec =   0.014 (7) %


---------------------
Capture probabilities

PK  =  0.83181 (40)
PL1  =  0.12393 (17)
PL2  =  0.003201 (11)
PL3  =  0.004174 (36)
PM1  =  0.02754 (14)
PM2  =  7.803E-4 (7)
PM3  =  9.57E-4 (7)
PN1  =  0.00621 (6)
PM4  =  2.668E-6 (45)
PN2  =  1.647E-4 (11)
PN3  =  1.789E-4 (24)
PO1  =  0.001021 (17)
PN4  =  4.28E-7 (11)
PO2  =  1.707E-5 (26)
PO3  =  9.87E-6 (24)

K =  0.83181 (40)
L =  0.13130 (18)
M =  0.02928 (14)
N =  0.00655 (7)
O =  0.001048 (18)


------------------------------------------------------------
Input log ft value (ec): 9.8

Log ft value (ec)    =  9.80 (22)
with log f           =  0.394 (9)
or f-value           =  2.475 (48)
and log partial T1/2 =  9.41 (22)

