--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] 1657.283 (22) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 1502.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13617 (20)
PL2/PK =  0.003547 (10)
PL3/PK =  9.300E-4 (45)
PM1/PK =  0.02988 (15)
PM2/PK =  8.544E-4 (8)
PM3/PK =  2.121E-4 (9)
PN1/PK =  0.00672 (7)
PM4/PK =  5.91E-7 (8)
PN2/PK =  1.799E-4 (12)
PN3/PK =  3.958E-5 (41)
PO1/PK =  0.001105 (19)
PN4/PK =  9.46E-8 (21)
PO2/PK =  1.864E-5 (28)
PO3/PK =  2.184E-6 (47)

L/K =  0.14065 (20)
M/K =  0.03095 (15)
N/K =  0.00694 (7)
O/K =  0.001126 (19)


------------------------------
Relative capture probabilities

PK  =  0.84770 (31)
PL1 =  0.11543 (13)
PL2 =  0.003007 (9)
PL3 =  7.884E-4 (41)
PM1 =  0.02533 (12)
PM2 =  7.2428E-4 (45)
PM3 =  1.798E-4 (7)
PN1 =  0.00570 (5)
PM4 =  5.01E-7 (7)
PN2 =  1.525E-4 (10)
PN3 =  3.355E-5 (34)
PO1 =  9.37E-4 (16)
PN4 =  8.02E-8 (18)
PO2 =  1.580E-5 (23)
PO3 =  1.851E-6 (39)

K =  0.84770 (31)
L =  0.11923 (12)
M =  0.02623 (12)
N =  0.00588 (6)
O =  9.54E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  747 (19)
L1/b+ =  101.7 (25)
L2/b+ =  2.65 (8)
L3/b+ =  0.694 (22)
M1/b+ =  22.31 (48)
M2/b+ =  0.638 (16)
M3/b+ =  0.1583 (43)
N1/b+ =  5.02 (10)
M4/b+ =  4.41E-4 (10)
N2/b+ =  0.1343 (27)
N3/b+ =  0.0296 (6)
O1/b+ =  0.825 (22)
N4/b+ =  7.06E-5 (23)
O2/b+ =  0.01392 (35)
O3/b+ =  0.00163 (5)

K/b+ =  747 (19)
L/b+ =  105.0 (26)
M/b+ =  23.1 (5)
N/b+ =  5.18 (10)
O/b+ =  0.840 (23)

EC/b+ =  881 (23)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.106 (8) %   Iec =   0.106 (8) %   Ib+ =   1.21E-4 (10) %
Iec      =   0.106 (8) % (input data kept)
Ib+      =   1.21E-4 (10) % (input data kept)
Iec tot. =   0.106 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.84674 (31)
PL1  =  0.11530 (13)
PL2  =  0.003003 (9)
PL3  =  7.875E-4 (41)
PM1  =  0.02530 (12)
PM2  =  7.2346E-4 (45)
PM3  =  1.796E-4 (7)
PN1  =  0.00569 (5)
PM4  =  5.00E-7 (7)
PN2  =  1.524E-4 (10)
PN3  =  3.351E-5 (34)
PO1  =  9.36E-4 (16)
PN4  =  8.01E-8 (18)
PO2  =  1.578E-5 (23)
PO3  =  1.849E-6 (39)

K =  0.84674 (31)
L =  0.11909 (12)
M =  0.02621 (12)
N =  0.00588 (6)
O =  9.53E-4 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 10.351

Log ft value (ec)    =  10.350 (33)
with log f           =  1.819 (6)
or f-value           =  65.8 (9)
and log partial T1/2 =  8.532 (33)

