--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] 2308.42 (9) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 851.2 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14401 (25)
PL2/PK =  0.003725 (11)
PL3/PK =  0.003057 (22)
PM1/PK =  0.03185 (17)
PM2/PK =  9.040E-4 (11)
PM3/PK =  6.997E-4 (46)
PN1/PK =  0.00718 (7)
PM4/PK =  1.950E-6 (31)
PN2/PK =  1.907E-4 (13)
PN3/PK =  1.307E-4 (17)
PO1/PK =  0.00118 (2)
PN4/PK =  3.12E-7 (8)
PO2/PK =  1.976E-5 (30)
PO3/PK =  7.21E-6 (17)

L/K =  0.15080 (24)
M/K =  0.03346 (17)
N/K =  0.00750 (8)
O/K =  0.001207 (21)


------------------------------
Relative capture probabilities

PK  =  0.83825 (36)
PL1 =  0.12072 (15)
PL2 =  0.003122 (10)
PL3 =  0.002563 (19)
PM1 =  0.02670 (13)
PM2 =  7.578E-4 (6)
PM3 =  5.865E-4 (36)
PN1 =  0.00601 (6)
PM4 =  1.634E-6 (25)
PN2 =  1.598E-4 (10)
PN3 =  1.095E-4 (13)
PO1 =  9.89E-4 (17)
PN4 =  2.62E-7 (6)
PO2 =  1.656E-5 (25)
PO3 =  6.04E-6 (14)

K =  0.83825 (36)
L =  0.12640 (15)
M =  0.02805 (13)
N =  0.00628 (6)
O =  0.001012 (17)


------------------------------
Capture branch from input data

Iec =   0.009 (2) %


---------------------
Capture probabilities

PK  =  0.83825 (36)
PL1  =  0.12072 (15)
PL2  =  0.003122 (10)
PL3  =  0.002563 (19)
PM1  =  0.02670 (13)
PM2  =  7.578E-4 (6)
PM3  =  5.865E-4 (36)
PN1  =  0.00601 (6)
PM4  =  1.634E-6 (25)
PN2  =  1.598E-4 (10)
PN3  =  1.095E-4 (13)
PO1  =  9.89E-4 (17)
PN4  =  2.62E-7 (6)
PO2  =  1.656E-5 (25)
PO3  =  6.04E-6 (14)

K =  0.83825 (36)
L =  0.12640 (15)
M =  0.02805 (13)
N =  0.00628 (6)
O =  0.001012 (17)


------------------------------------------------------------
Input log ft value (ec): 10.41

Log ft value (ec)    =  10.41 (10)
with log f           =  0.807 (7)
or f-value           =  6.42 (11)
and log partial T1/2 =  9.6 (1)

