--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2858.90 (15) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 300.7 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15302 (41)
PL2/PK =  0.003952 (16)
PM1/PK =  0.03411 (22)
PM2/PK =  9.664E-4 (22)
PN1/PK =  0.00769 (9)
PN2/PK =  2.041E-4 (16)
PO1/PK =  0.001266 (23)
PO2/PK =  2.115E-5 (35)

L/K =  0.15697 (41)
M/K =  0.03507 (22)
N/K =  0.00790 (9)
O/K =  0.001287 (24)


------------------------------
Relative capture probabilities

PK  =  0.8325 (5)
PL1 =  0.12738 (26)
PL2 =  0.003290 (14)
PM1 =  0.02839 (16)
PM2 =  8.045E-4 (14)
PN1 =  0.00641 (7)
PN2 =  1.699E-4 (13)
PO1 =  0.001054 (19)
PO2 =  1.761E-5 (28)

K =  0.8325 (5)
L =  0.13067 (26)
M =  0.02920 (16)
N =  0.00658 (7)
O =  0.001071 (19)


------------------------------
Capture branch from input data

Iec =   0.003 (1) %


---------------------
Capture probabilities

PK  =  0.8325 (5)
PL1  =  0.12738 (26)
PL2  =  0.003290 (14)
PM1  =  0.02839 (16)
PM2  =  8.045E-4 (14)
PN1  =  0.00641 (7)
PN2  =  1.699E-4 (13)
PO1  =  0.001054 (19)
PO2  =  1.761E-5 (28)

K =  0.8325 (5)
L =  0.13067 (26)
M =  0.02920 (16)
N =  0.00658 (7)
O =  0.001071 (19)


------------------------------------------------------------
Input log ft value (ec): 9.51

Log ft value (ec)    =  9.51 (15)
with log f           =  -0.567 (10)
or f-value           =  0.271 (6)
and log partial T1/2 =  10.08 (14)

