--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2817.48 (11) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 342.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14937 (36)
PL2/PK =  0.003859 (14)
PM1/PK =  0.03319 (20)
PM2/PK =  9.407E-4 (19)
PN1/PK =  0.00748 (8)
PN2/PK =  1.986E-4 (15)
PO1/PK =  0.001231 (22)
PO2/PK =  2.058E-5 (33)

L/K =  0.15323 (35)
M/K =  0.03413 (20)
N/K =  0.00768 (8)
O/K =  0.001251 (23)


------------------------------
Relative capture probabilities

PK  =  0.83591 (46)
PL1 =  0.12486 (23)
PL2 =  0.003226 (13)
PM1 =  0.02774 (15)
PM2 =  7.864E-4 (11)
PN1 =  0.00626 (7)
PN2 =  1.660E-4 (12)
PO1 =  0.001029 (18)
PO2 =  1.720E-5 (27)

K =  0.83591 (46)
L =  0.12809 (22)
M =  0.02853 (15)
N =  0.00642 (7)
O =  0.001046 (18)


------------------------------
Capture branch from input data

Iec =   0.006 (1) %


---------------------
Capture probabilities

PK  =  0.83591 (46)
PL1  =  0.12486 (23)
PL2  =  0.003226 (13)
PM1  =  0.02774 (15)
PM2  =  7.864E-4 (11)
PN1  =  0.00626 (7)
PN2  =  1.660E-4 (12)
PO1  =  0.001029 (18)
PO2  =  1.720E-5 (27)

K =  0.83591 (46)
L =  0.12809 (22)
M =  0.02853 (15)
N =  0.00642 (7)
O =  0.001046 (18)


------------------------------------------------------------
Input log ft value (ec): 9.33

Log ft value (ec)    =  9.33 (7)
with log f           =  -0.445 (9)
or f-value           =  0.359 (7)
and log partial T1/2 =  9.78 (7)

