--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2-] 2701.61 (3) keV
Calculation of the allowed transition from the electron capture decay of I-124.

Transition energy: 458.0 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14304 (28)
PL2/PK =  0.003699 (12)
PM1/PK =  0.03160 (17)
PM2/PK =  8.966E-4 (13)
PN1/PK =  0.00712 (7)
PN2/PK =  1.891E-4 (13)
PO1/PK =  0.00117 (2)
PO2/PK =  1.959E-5 (31)

L/K =  0.14674 (27)
M/K =  0.03250 (18)
N/K =  0.00731 (8)
O/K =  0.001190 (21)


------------------------------
Relative capture probabilities

PK  =  0.84194 (38)
PL1 =  0.12043 (18)
PL2 =  0.003114 (11)
PM1 =  0.02660 (13)
PM2 =  7.549E-4 (8)
PN1 =  0.00599 (6)
PN2 =  1.592E-4 (11)
PO1 =  9.85E-4 (17)
PO2 =  1.649E-5 (25)

K =  0.84194 (38)
L =  0.12355 (17)
M =  0.02736 (13)
N =  0.00615 (6)
O =  0.001002 (17)


------------------------------
Capture branch from input data

Iec =   1.98 (3) %


---------------------
Capture probabilities

PK  =  0.84194 (38)
PL1  =  0.12043 (18)
PL2  =  0.003114 (11)
PM1  =  0.02660 (13)
PM2  =  7.549E-4 (8)
PN1  =  0.00599 (6)
PN2  =  1.592E-4 (11)
PO1  =  9.85E-4 (17)
PO2  =  1.649E-5 (25)

K =  0.84194 (38)
L =  0.12355 (17)
M =  0.02736 (13)
N =  0.00615 (6)
O =  0.001002 (17)


------------------------------------------------------------
Input log ft value (ec): 7.088

Log ft value (ec)    =  7.088 (10)
with log f           =  -0.173 (7)
or f-value           =  0.672 (11)
and log partial T1/2 =  7.261 (7)

