--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2681.46 (4) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 478.1 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14229 (27)
PL2/PK =  0.003680 (12)
PM1/PK =  0.03141 (17)
PM2/PK =  8.914E-4 (13)
PN1/PK =  0.00707 (7)
PN2/PK =  1.879E-4 (13)
PO1/PK =  0.001163 (20)
PO2/PK =  1.947E-5 (30)

L/K =  0.14597 (26)
M/K =  0.03230 (17)
N/K =  0.00726 (8)
O/K =  0.001183 (21)


------------------------------
Relative capture probabilities

PK  =  0.84267 (38)
PL1 =  0.11990 (17)
PL2 =  0.003101 (11)
PM1 =  0.02647 (13)
PM2 =  7.512E-4 (7)
PN1 =  0.00596 (6)
PN2 =  1.584E-4 (10)
PO1 =  9.80E-4 (17)
PO2 =  1.641E-5 (25)

K =  0.84267 (38)
L =  0.12300 (16)
M =  0.02722 (13)
N =  0.00612 (6)
O =  9.96E-4 (17)


------------------------------
Capture branch from input data

Iec =   0.39 (2) %


---------------------
Capture probabilities

PK  =  0.84267 (38)
PL1  =  0.11990 (17)
PL2  =  0.003101 (11)
PM1  =  0.02647 (13)
PM2  =  7.512E-4 (7)
PN1  =  0.00596 (6)
PN2  =  1.584E-4 (10)
PO1  =  9.80E-4 (17)
PO2  =  1.641E-5 (25)

K =  0.84267 (38)
L =  0.12300 (16)
M =  0.02722 (13)
N =  0.00612 (6)
O =  9.96E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 7.833

Log ft value (ec)    =  7.833 (23)
with log f           =  -0.133 (7)
or f-value           =  0.736 (12)
and log partial T1/2 =  7.966 (22)

