--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [5-] 2335.03 (1) keV
Calculation of the 2nd forbidden unique transition from the electron capture decay of I-124.

Transition energy: 824.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15448 (29)
PL2/PK =  0.003988 (13)
PL3/PK =  0.01164 (9)
PM1/PK =  0.03451 (19)
PM2/PK =  9.772E-4 (14)
PM3/PK =  0.002687 (19)
PN1/PK =  0.00779 (8)
PM4/PK =  7.49E-6 (12)
PM5/PK =  2.50E-6 (5)
PN2/PK =  2.065E-4 (15)
PN3/PK =  5.03E-4 (7)
PO1/PK =  0.001282 (22)
PN4/PK =  1.202E-6 (30)
PN5/PK =  4.30E-7 (13)
PO2/PK =  2.140E-5 (33)
PO3/PK =  2.77E-5 (7)

L/K =  0.17011 (31)
M/K =  0.03819 (21)
N/K =  0.00850 (9)
O/K =  0.001331 (23)


------------------------------
Relative capture probabilities

PK  =  0.82093 (43)
PL1 =  0.12682 (17)
PL2 =  0.003274 (11)
PL3 =  0.00955 (7)
PM1 =  0.02833 (14)
PM2 =  8.022E-4 (7)
PM3 =  0.002206 (14)
PN1 =  0.00640 (6)
PM4 =  6.15E-6 (10)
PM5 =  2.053E-6 (42)
PN2 =  1.695E-4 (11)
PN3 =  4.13E-4 (5)
PO1 =  0.001052 (18)
PN4 =  9.87E-7 (24)
PN5 =  3.53E-7 (11)
PO2 =  1.757E-5 (26)
PO3 =  2.28E-5 (5)

K =  0.82093 (43)
L =  0.13965 (18)
M =  0.03135 (15)
N =  0.00698 (7)
O =  0.001093 (19)


------------------------------
Capture branch from input data

Iec =   0.02 (1) %


---------------------
Capture probabilities

PK  =  0.82093 (43)
PL1  =  0.12682 (17)
PL2  =  0.003274 (11)
PL3  =  0.00955 (7)
PM1  =  0.02833 (14)
PM2  =  8.022E-4 (7)
PM3  =  0.002206 (14)
PN1  =  0.00640 (6)
PM4  =  6.15E-6 (10)
PM5  =  2.053E-6 (42)
PN2  =  1.695E-4 (11)
PN3  =  4.13E-4 (5)
PO1  =  0.001052 (18)
PN4  =  9.87E-7 (24)
PN5  =  3.53E-7 (11)
PO2  =  1.757E-5 (26)
PO3  =  2.28E-5 (5)

K =  0.82093 (43)
L =  0.13965 (18)
M =  0.03135 (15)
N =  0.00698 (7)
O =  0.001093 (19)


------------------------------------------------------------
Input log ft value (ec): 10.4

Log ft value (ec)    =  10.40 (22)
with log f           =  1.141 (10)
or f-value           =  13.83 (31)
and log partial T1/2 =  9.26 (22)

