--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [4+] 2224.954 (15) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 934.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14235 (23)
PL2/PK =  0.003685 (11)
PL3/PK =  0.002506 (17)
PM1/PK =  0.03143 (16)
PM2/PK =  8.929E-4 (10)
PM3/PK =  5.730E-4 (35)
PN1/PK =  0.00708 (7)
PM4/PK =  1.597E-6 (25)
PN2/PK =  1.883E-4 (13)
PN3/PK =  1.070E-4 (13)
PO1/PK =  0.001164 (20)
PN4/PK =  2.56E-7 (6)
PO2/PK =  1.951E-5 (30)
PO3/PK =  5.90E-6 (14)

L/K =  0.14854 (23)
M/K =  0.03290 (17)
N/K =  0.00737 (7)
O/K =  0.001189 (20)


------------------------------
Relative capture probabilities

PK  =  0.84033 (35)
PL1 =  0.11962 (15)
PL2 =  0.003096 (10)
PL3 =  0.002106 (15)
PM1 =  0.02641 (13)
PM2 =  7.503E-4 (5)
PM3 =  4.815E-4 (27)
PN1 =  0.00595 (6)
PM4 =  1.342E-6 (20)
PN2 =  1.582E-4 (10)
PN3 =  8.99E-5 (11)
PO1 =  9.78E-4 (16)
PN4 =  2.15E-7 (5)
PO2 =  1.639E-5 (24)
PO3 =  4.96E-6 (11)

K =  0.84033 (35)
L =  0.12482 (14)
M =  0.02765 (13)
N =  0.00620 (6)
O =  10.00E-4 (17)


------------------------------
Capture branch from input data

Iec =   0.005 (2) %


---------------------
Capture probabilities

PK  =  0.84033 (35)
PL1  =  0.11962 (15)
PL2  =  0.003096 (10)
PL3  =  0.002106 (15)
PM1  =  0.02641 (13)
PM2  =  7.503E-4 (5)
PM3  =  4.815E-4 (27)
PN1  =  0.00595 (6)
PM4  =  1.342E-6 (20)
PN2  =  1.582E-4 (10)
PN3  =  8.99E-5 (11)
PO1  =  9.78E-4 (16)
PN4  =  2.15E-7 (5)
PO2  =  1.639E-5 (24)
PO3  =  4.96E-6 (11)

K =  0.84033 (35)
L =  0.12482 (14)
M =  0.02765 (13)
N =  0.00620 (6)
O =  10.00E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 10.83

Log ft value (ec)    =  10.83 (17)
with log f           =  0.975 (7)
or f-value           =  9.43 (15)
and log partial T1/2 =  9.86 (17)

