--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [3+] 2039.34 (6) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 1120.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13302 (20)
PL2/PK =  0.003462 (10)
PM1/PK =  0.02909 (15)
PM2/PK =  8.313E-4 (8)
PN1/PK =  0.00654 (7)
PN2/PK =  1.750E-4 (12)
PO1/PK =  0.001075 (18)
PO2/PK =  1.812E-5 (27)

L/K =  0.13648 (19)
M/K =  0.02992 (15)
N/K =  0.00671 (7)
O/K =  0.001093 (19)


------------------------------
Relative capture probabilities

PK  =  0.85164 (30)
PL1 =  0.11328 (13)
PL2 =  0.002948 (9)
PM1 =  0.02477 (11)
PM2 =  7.0794E-4 (44)
PN1 =  0.00557 (5)
PN2 =  1.490E-4 (9)
PO1 =  9.15E-4 (15)
PO2 =  1.543E-5 (23)

K =  0.85164 (30)
L =  0.11623 (12)
M =  0.02548 (12)
N =  0.00572 (5)
O =  9.31E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.32E5 (15)
L1/b+ =  1.76E4 (19)
L2/b+ =  4.6E2 (5)
M1/b+ =  3.85E3 (41)
M2/b+ =  110 (12)
N1/b+ =  8.7E2 (9)
N2/b+ =  23.2 (24)
O1/b+ =  142 (16)
O2/b+ =  2.40 (27)

K/b+ =  1.32E5 (15)
L/b+ =  1.81E4 (20)
M/b+ =  3.96E3 (43)
N/b+ =  8.9E2 (9)
O/b+ =  145 (17)

EC/b+ =  1.55E5 (17)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.026 (16) %   Iec =   0.026 (16) %   Ib+ =   1.8E-7 (11) %
Iec      =   0.026 (16) % (input data kept)
Ib+      =   1.8E-7 (11) % (input data kept)
Iec tot. =   0.026 (16) % (input data kept)


---------------------
Capture probabilities

PK  =  0.85164 (30)
PL1  =  0.11328 (13)
PL2  =  0.002948 (9)
PM1  =  0.02477 (11)
PM2  =  7.0794E-4 (44)
PN1  =  0.00557 (5)
PN2  =  1.490E-4 (9)
PO1  =  9.15E-4 (15)
PO2  =  1.543E-5 (23)

K =  0.85164 (30)
L =  0.11623 (12)
M =  0.02548 (12)
N =  0.00572 (5)
O =  9.31E-4 (15)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.78

Log ft value (ec)    =  9.78 (27)
with log f           =  0.6366 (49)
or f-value           =  4.331 (49)
and log partial T1/2 =  9.14 (27)

