--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [0+] g.s.
Calculation of the 1st forbidden unique transition from the electron capture decay of I-124.

Transition energy: 3159.6 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13112 (19)
PL2/PK =  0.003481 (9)
PL3/PK =  2.056E-4 (7)
PM1/PK =  0.02862 (14)
PM2/PK =  8.341E-4 (8)
PM3/PK =  4.678E-5 (14)
PN1/PK =  0.00643 (6)
PM4/PK =  1.303E-7 (16)
PN2/PK =  1.755E-4 (12)
PN3/PK =  8.73E-6 (8)
PO1/PK =  0.001057 (18)
PN4/PK =  2.086E-8 (44)
PO2/PK =  1.818E-5 (27)
PO3/PK =  4.81E-7 (10)

L/K =  0.13481 (18)
M/K =  0.02950 (14)
N/K =  0.00661 (6)
O/K =  0.001075 (18)


------------------------------
Relative capture probabilities

PK  =  0.85324 (29)
PL1 =  0.11188 (12)
PL2 =  0.002970 (9)
PL3 =  1.755E-4 (7)
PM1 =  0.02442 (11)
PM2 =  7.1173E-4 (42)
PM3 =  3.992E-5 (11)
PN1 =  0.00549 (5)
PM4 =  1.112E-7 (13)
PN2 =  1.497E-4 (9)
PN3 =  7.45E-6 (6)
PO1 =  9.02E-4 (15)
PN4 =  1.780E-8 (37)
PO2 =  1.551E-5 (23)
PO3 =  4.11E-7 (8)

K =  0.85324 (29)
L =  0.11503 (11)
M =  0.02517 (11)
N =  0.00564 (5)
O =  9.18E-4 (15)


--------------------------
Capture-to-positron ratios

K/b+ =  1.992 (22)
L1/b+ =  0.2612 (26)
L2/b+ =  0.00693 (10)
L3/b+ =  4.10E-4 (6)
M1/b+ =  0.05702 (37)
M2/b+ =  0.001662 (17)
M3/b+ =  9.32E-5 (10)
N1/b+ =  0.01281 (6)
M4/b+ =  2.596E-7 (18)
N2/b+ =  3.496E-4 (17)
N3/b+ =  1.738E-5 (8)
O1/b+ =  0.002105 (25)
N4/b+ =  4.16E-8 (7)
O2/b+ =  3.621E-5 (36)
O3/b+ =  9.59E-7 (14)

K/b+ =  1.992 (22)
L/b+ =  0.2686 (27)
M/b+ =  0.05877 (38)
N/b+ =  0.01318 (6)
O/b+ =  0.002143 (25)

EC/b+ =  2.335 (25)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   34.40 (35) %   Iec =   24.08 (33) %   Ib+ =   10.32 (13) %
Iec      =   24.08 (33) % (input data kept)
Ib+      =   10.32 (13) % (input data kept)
Iec tot. =   34.40 (35) % (input data kept)


---------------------
Capture probabilities

PK  =  0.5974 (20)
PL1  =  0.07833 (27)
PL2  =  0.002079 (9)
PL3  =  1.228E-4 (6)
PM1  =  0.0171 (1)
PM2  =  4.983E-4 (17)
PM3  =  2.795E-5 (12)
PN1  =  0.003841 (39)
PM4  =  7.79E-8 (10)
PN2  =  1.048E-4 (7)
PN3  =  5.213E-6 (48)
PO1  =  6.31E-4 (11)
PN4  =  1.246E-8 (26)
PO2  =  1.086E-5 (16)
PO3  =  2.88E-7 (6)

K =  0.5974 (20)
L =  0.08054 (27)
M =  0.01762 (10)
N =  0.003951 (39)
O =  6.42E-4 (11)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.309

Log ft value (ec)    =  9.305 (7)
with log f           =  3.1290 (45)
or f-value           =  1346 (14)
and log partial T1/2 =  6.176 (6)

