--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-124 [2-] g.s.  -->  Daughter nucleus: 52-Te-124 [2+] 2641.15 (7) keV
This 1st forbidden non-unique transition from the electron capture decay of I-124 is calculated as allowed.

Transition energy: 518.4 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14097 (26)
PL2/PK =  0.003647 (11)
PM1/PK =  0.03108 (17)
PM2/PK =  8.824E-4 (12)
PN1/PK =  0.00700 (7)
PN2/PK =  1.860E-4 (13)
PO1/PK =  0.00115 (2)
PO2/PK =  1.927E-5 (30)

L/K =  0.14461 (25)
M/K =  0.03196 (17)
N/K =  0.00718 (7)
O/K =  0.00117 (2)


------------------------------
Relative capture probabilities

PK  =  0.84394 (36)
PL1 =  0.11897 (16)
PL2 =  0.003078 (11)
PM1 =  0.02623 (13)
PM2 =  7.447E-4 (7)
PN1 =  0.00590 (6)
PN2 =  1.57E-4 (1)
PO1 =  9.71E-4 (16)
PO2 =  1.626E-5 (25)

K =  0.84394 (36)
L =  0.12204 (16)
M =  0.02697 (13)
N =  0.00606 (6)
O =  9.87E-4 (17)


------------------------------
Capture branch from input data

Iec =   0.404 (15) %


---------------------
Capture probabilities

PK  =  0.84394 (36)
PL1  =  0.11897 (16)
PL2  =  0.003078 (11)
PM1  =  0.02623 (13)
PM2  =  7.447E-4 (7)
PN1  =  0.00590 (6)
PN2  =  1.57E-4 (1)
PO1  =  9.71E-4 (16)
PO2  =  1.626E-5 (25)

K =  0.84394 (36)
L =  0.12204 (16)
M =  0.02697 (13)
N =  0.00606 (6)
O =  9.87E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 7.892

Log ft value (ec)    =  7.892 (17)
with log f           =  -0.059 (7)
or f-value           =  0.874 (14)
and log partial T1/2 =  7.951 (16)

