--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 25-Mn-52 [6+] g.s.  -->  Daughter nucleus: 24-Cr-52 [4+] 2369.654 (21) keV
This 2nd forbidden non-unique transition from the electron capture decay of Mn-52 is calculated as 1st forbidden unique.

Transition energy: 2342.3 (19) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11054 (29)
PL2/PK =  5.10E-4 (14)
PL3/PK =  8.19E-5 (24)
PM1/PK =  0.01719 (10)
PM2/PK =  7.41E-5 (24)
PM3/PK =  1.047E-5 (37)
PN1/PK =  0.001312 (25)
PM4/PK =  1.123E-9 (11)

L/K =  0.11113 (30)
M/K =  0.01728 (10)
N/K =  0.001312 (25)


------------------------------
Relative capture probabilities

PK  =  0.88518 (34)
PL1 =  0.09785 (22)
PL2 =  4.52E-4 (12)
PL3 =  7.25E-5 (21)
PM1 =  0.01522 (8)
PM2 =  6.56E-5 (21)
PM3 =  9.27E-6 (33)
PN1 =  0.001161 (22)
PM4 =  9.94E-10 (10)

K =  0.88518 (34)
L =  0.09837 (23)
M =  0.01529 (9)
N =  0.001161 (22)


--------------------------
Capture-to-positron ratios

K/b+ =  0.3890 (39)
L1/b+ =  0.0430 (5)
L2/b+ =  1.99E-4 (8)
L3/b+ =  3.18E-5 (13)
M1/b+ =  0.00669 (11)
M2/b+ =  2.88E-5 (12)
M3/b+ =  4.07E-6 (19)
N1/b+ =  5.10E-4 (15)
M4/b+ =  4.37E-10 (9)

K/b+ =  0.3890 (39)
L/b+ =  0.0432 (6)
M/b+ =  0.00672 (11)
N/b+ =  5.10E-4 (15)

EC/b+ =  0.4395 (46)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.5 (8) %   Iec =   0.2 (6) %   Ib+ =   0.3 (6) %
Iec      =   0.2 (6) % (input data kept)
Ib+      =   0.3 (6) % (input data kept)
Iec tot. =   0.5 (8) % (input data kept)


---------------------
Capture probabilities

PK  =  0.2703 (20)
PL1  =  0.02987 (23)
PL2  =  1.380E-4 (39)
PL3  =  2.21E-5 (7)
PM1  =  0.004646 (42)
PM2  =  2.00E-5 (7)
PM3  =  2.83E-6 (10)
PN1  =  3.55E-4 (7)
PM4  =  3.036E-10 (37)

K =  0.2703 (20)
L =  0.03003 (23)
M =  0.004669 (43)
N =  3.55E-4 (7)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.8 (7)

Log ft value (ec)    =  9.7 (13)
with log f           =  1.3123 (36)
or f-value           =  20.52 (17)
and log partial T1/2 =  8.4 (13)

