--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 158.99 (3) keV
Calculation of the allowed transition from the electron capture decay of I-123.

Transition energy: 1075 (3) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13329 (21)
PL2/PK =  0.003468 (10)
PM1/PK =  0.02916 (15)
PM2/PK =  8.328E-4 (9)
PN1/PK =  0.00655 (7)
PN2/PK =  1.753E-4 (12)
PO1/PK =  0.001077 (18)
PO2/PK =  1.816E-5 (28)

L/K =  0.13676 (20)
M/K =  0.02999 (15)
N/K =  0.00673 (7)
O/K =  0.001095 (19)


------------------------------
Relative capture probabilities

PK  =  0.85137 (31)
PL1 =  0.11348 (13)
PL2 =  0.002952 (9)
PM1 =  0.02482 (12)
PM2 =  7.0904E-4 (47)
PN1 =  0.00558 (5)
PN2 =  1.492E-4 (9)
PO1 =  9.17E-4 (15)
PO2 =  1.546E-5 (23)

K =  0.85137 (31)
L =  0.11643 (13)
M =  0.02553 (12)
N =  0.00573 (5)
O =  9.33E-4 (16)


--------------------------
Capture-to-positron ratios

K/b+ =  3.5E6 (13)
L1/b+ =  4.6E5 (18)
L2/b+ =  1.20E4 (47)
M1/b+ =  1.01E5 (39)
M2/b+ =  2.9E3 (11)
N1/b+ =  2.3E4 (9)
N2/b+ =  6.1E2 (23)
O1/b+ =  3.7E3 (15)
O2/b+ =  63 (25)

K/b+ =  3.5E6 (13)
L/b+ =  4.7E5 (18)
M/b+ =  1.04E5 (40)
N/b+ =  2.3E4 (9)
O/b+ =  3.8E3 (15)

EC/b+ =  4.1E6 (16)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   97.18 (32) %   Iec =   97.18 (32) %   Ib+ =   0 %
Iec      =   97.18 (32) % (input data kept)
Ib+      =   0 % (input data kept)
Iec tot. =   97.18 (32) % (input data kept)


---------------------
Capture probabilities

PK  =  0.85137 (31)
PL1  =  0.11348 (13)
PL2  =  0.002952 (9)
PM1  =  0.02482 (12)
PM2  =  7.0904E-4 (47)
PN1  =  0.00558 (5)
PN2  =  1.492E-4 (9)
PO1  =  9.17E-4 (15)
PO2  =  1.546E-5 (23)

K =  0.85137 (31)
L =  0.11643 (13)
M =  0.02553 (12)
N =  0.00573 (5)
O =  9.33E-4 (16)


------------------------------------------------------------
Input log ft value (ec & beta +): 5.26

Log ft value (ec)    =  5.290 (6)
with log f           =  0.600 (6)
or f-value           =  3.98 (5)
and log partial T1/2 =  4.6901 (14)

