--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [5/2+] 505.34 (4) keV
Calculation of the allowed transition from the electron capture decay of I-123.

Transition energy: 728.7 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13660 (24)
PL2/PK =  0.003541 (11)
PM1/PK =  0.02999 (16)
PM2/PK =  8.532E-4 (10)
PN1/PK =  0.00674 (7)
PN2/PK =  1.797E-4 (12)
PO1/PK =  0.001109 (19)
PO2/PK =  1.862E-5 (29)

L/K =  0.14014 (23)
M/K =  0.03084 (16)
N/K =  0.00692 (7)
O/K =  0.001127 (19)


------------------------------
Relative capture probabilities

PK  =  0.84815 (34)
PL1 =  0.11586 (15)
PL2 =  0.003003 (10)
PM1 =  0.02543 (12)
PM2 =  7.237E-4 (6)
PN1 =  0.00572 (6)
PN2 =  1.524E-4 (10)
PO1 =  9.40E-4 (16)
PO2 =  1.579E-5 (24)

K =  0.84815 (34)
L =  0.11886 (14)
M =  0.02616 (12)
N =  0.00587 (6)
O =  9.56E-4 (16)


------------------------------
Capture branch from input data

Iec =   0.349 (42) %


---------------------
Capture probabilities

PK  =  0.84815 (34)
PL1  =  0.11586 (15)
PL2  =  0.003003 (10)
PM1  =  0.02543 (12)
PM2  =  7.237E-4 (6)
PN1  =  0.00572 (6)
PN2  =  1.524E-4 (10)
PO1  =  9.40E-4 (16)
PO2  =  1.579E-5 (24)

K =  0.84815 (34)
L =  0.11886 (14)
M =  0.02616 (12)
N =  0.00587 (6)
O =  9.56E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 7.35

Log ft value (ec)    =  7.39 (5)
with log f           =  0.251 (7)
or f-value           =  1.783 (29)
and log partial T1/2 =  7.13 (5)

