--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [5/2-] 996.06 (12) keV
This 1st forbidden non-unique transition from the electron capture decay of I-123 is calculated as allowed.

Transition energy: 237.9 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1615 (8)
PL2/PK =  0.004171 (25)
PM1/PK =  0.03625 (32)
PM2/PK =  0.0010265 (48)
PN1/PK =  0.00819 (11)
PN2/PK =  2.171E-4 (23)
PO1/PK =  0.001348 (28)
PO2/PK =  2.250E-5 (43)

L/K =  0.1657 (8)
M/K =  0.03727 (32)
N/K =  0.00841 (12)
O/K =  0.001370 (29)


------------------------------
Relative capture probabilities

PK  =  0.8246 (8)
PL1 =  0.1332 (5)
PL2 =  0.003439 (20)
PM1 =  0.02989 (23)
PM2 =  8.464E-4 (31)
PN1 =  0.00675 (9)
PN2 =  1.790E-4 (17)
PO1 =  0.001111 (22)
PO2 =  1.856E-5 (33)

K =  0.8246 (8)
L =  0.1366 (5)
M =  0.03074 (23)
N =  0.00693 (9)
O =  0.001130 (22)


------------------------------
Capture branch from input data

Iec =   0.0035 (3) %


---------------------
Capture probabilities

PK  =  0.8246 (8)
PL1  =  0.1332 (5)
PL2  =  0.003439 (20)
PM1  =  0.02989 (23)
PM2  =  8.464E-4 (31)
PN1  =  0.00675 (9)
PN2  =  1.790E-4 (17)
PO1  =  0.001111 (22)
PO2  =  1.856E-5 (33)

K =  0.8246 (8)
L =  0.1366 (5)
M =  0.03074 (23)
N =  0.00693 (9)
O =  0.001130 (22)


------------------------------------------------------------
Input log ft value (ec): 8.31

Log ft value (ec)    =  8.34 (4)
with log f           =  -0.794 (16)
or f-value           =  0.161 (6)
and log partial T1/2 =  9.134 (37)

