--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 894.74 (6) keV
This transition from the electron capture decay of I-123 is calculated as allowed.

Transition energy: 339.3 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14959 (45)
PL2/PK =  0.003865 (17)
PM1/PK =  0.03324 (22)
PM2/PK =  9.422E-4 (25)
PN1/PK =  0.00750 (9)
PN2/PK =  1.989E-4 (17)
PO1/PK =  0.001233 (23)
PO2/PK =  2.061E-5 (35)

L/K =  0.15346 (44)
M/K =  0.03419 (22)
N/K =  0.00769 (9)
O/K =  0.001254 (23)


------------------------------
Relative capture probabilities

PK  =  0.8357 (5)
PL1 =  0.12501 (29)
PL2 =  0.003230 (14)
PM1 =  0.02778 (17)
PM2 =  7.874E-4 (16)
PN1 =  0.00626 (7)
PN2 =  1.662E-4 (13)
PO1 =  0.001030 (19)
PO2 =  1.723E-5 (28)

K =  0.8357 (5)
L =  0.12824 (28)
M =  0.02857 (17)
N =  0.00643 (7)
O =  0.001048 (19)


------------------------------
Capture branch from input data

Iec =   0.0744 (13) %


---------------------
Capture probabilities

PK  =  0.8357 (5)
PL1  =  0.12501 (29)
PL2  =  0.003230 (14)
PM1  =  0.02778 (17)
PM2  =  7.874E-4 (16)
PN1  =  0.00626 (7)
PN2  =  1.662E-4 (13)
PO1  =  0.001030 (19)
PO2  =  1.723E-5 (28)

K =  0.8357 (5)
L =  0.12824 (28)
M =  0.02857 (17)
N =  0.00643 (7)
O =  0.001048 (19)


------------------------------------------------------------
Input log ft value (ec): 7.32

Log ft value (ec)    =  7.353 (14)
with log f           =  -0.453 (12)
or f-value           =  0.353 (10)
and log partial T1/2 =  7.806 (8)

