--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 1068.18 (8) keV
This transition from the electron capture decay of I-123 is calculated as allowed.

Transition energy: 165.8 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1819 (16)
PL2/PK =  0.004699 (49)
PM1/PK =  0.0414 (6)
PM2/PK =  0.001173 (11)
PN1/PK =  0.00938 (18)
PN2/PK =  2.486E-4 (38)
PO1/PK =  0.001545 (40)
PO2/PK =  2.58E-5 (6)

L/K =  0.1866 (17)
M/K =  0.0426 (6)
N/K =  0.00963 (18)
O/K =  0.001571 (41)


------------------------------
Relative capture probabilities

PK  =  0.8062 (16)
PL1 =  0.1466 (10)
PL2 =  0.003788 (35)
PM1 =  0.03339 (38)
PM2 =  9.45E-4 (7)
PN1 =  0.00757 (13)
PN2 =  2.005E-4 (27)
PO1 =  0.001246 (30)
PO2 =  2.079E-5 (46)

K =  0.8062 (16)
L =  0.1504 (10)
M =  0.03434 (39)
N =  0.00777 (13)
O =  0.001267 (30)


------------------------------
Capture branch from input data

Iec =   0.0079 (4) %


---------------------
Capture probabilities

PK  =  0.8062 (16)
PL1  =  0.1466 (10)
PL2  =  0.003788 (35)
PM1  =  0.03339 (38)
PM2  =  9.45E-4 (7)
PN1  =  0.00757 (13)
PN2  =  2.005E-4 (27)
PO1  =  0.001246 (30)
PO2  =  2.079E-5 (46)

K =  0.8062 (16)
L =  0.1504 (10)
M =  0.03434 (39)
N =  0.00777 (13)
O =  0.001267 (30)


------------------------------------------------------------
Input log ft value (ec): 7.59

Log ft value (ec)    =  7.623 (31)
with log f           =  -1.157 (22)
or f-value           =  0.0697 (36)
and log partial T1/2 =  8.780 (22)

