--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 440.00 (4) keV
Calculation of the allowed transition from the electron capture decay of I-123.

Transition energy: 794 (3) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13574 (23)
PL2/PK =  0.003521 (10)
PM1/PK =  0.02977 (15)
PM2/PK =  8.477E-4 (10)
PN1/PK =  0.00669 (7)
PN2/PK =  1.785E-4 (12)
PO1/PK =  0.001101 (19)
PO2/PK =  1.849E-5 (28)

L/K =  0.13926 (22)
M/K =  0.03062 (16)
N/K =  0.00687 (7)
O/K =  0.001119 (19)


------------------------------
Relative capture probabilities

PK  =  0.84899 (33)
PL1 =  0.11524 (15)
PL2 =  0.002989 (10)
PM1 =  0.02528 (12)
PM2 =  7.197E-4 (6)
PN1 =  0.00568 (6)
PN2 =  1.516E-4 (10)
PO1 =  9.34E-4 (16)
PO2 =  1.570E-5 (23)

K =  0.84899 (33)
L =  0.11823 (14)
M =  0.02599 (12)
N =  0.00584 (6)
O =  9.50E-4 (16)


------------------------------
Capture branch from input data

Iec =   0.419 (5) %


---------------------
Capture probabilities

PK  =  0.84899 (33)
PL1  =  0.11524 (15)
PL2  =  0.002989 (10)
PM1  =  0.02528 (12)
PM2  =  7.197E-4 (6)
PN1  =  0.00568 (6)
PN2  =  1.516E-4 (10)
PO1  =  9.34E-4 (16)
PO2  =  1.570E-5 (23)

K =  0.84899 (33)
L =  0.11823 (14)
M =  0.02599 (12)
N =  0.00584 (6)
O =  9.50E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 7.35

Log ft value (ec)    =  7.384 (9)
with log f           =  0.328 (7)
or f-value           =  2.130 (33)
and log partial T1/2 =  7.055 (5)

