--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 687.95 (4) keV
Calculation of the allowed transition from the electron capture decay of I-123.

Transition energy: 546.1 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14018 (28)
PL2/PK =  0.003627 (12)
PM1/PK =  0.03088 (17)
PM2/PK =  8.771E-4 (13)
PN1/PK =  0.00695 (7)
PN2/PK =  1.849E-4 (13)
PO1/PK =  0.001143 (20)
PO2/PK =  1.915E-5 (30)

L/K =  0.14381 (27)
M/K =  0.03176 (17)
N/K =  0.00714 (7)
O/K =  0.001162 (20)


------------------------------
Relative capture probabilities

PK  =  0.84469 (38)
PL1 =  0.11841 (18)
PL2 =  0.003064 (11)
PM1 =  0.02609 (13)
PM2 =  7.409E-4 (8)
PN1 =  0.00587 (6)
PN2 =  1.561E-4 (10)
PO1 =  9.65E-4 (17)
PO2 =  1.618E-5 (25)

K =  0.84469 (38)
L =  0.12148 (17)
M =  0.02683 (13)
N =  0.00603 (6)
O =  9.82E-4 (17)


------------------------------
Capture branch from input data

Iec =   1.40 (12) %


---------------------
Capture probabilities

PK  =  0.84469 (38)
PL1  =  0.11841 (18)
PL2  =  0.003064 (11)
PM1  =  0.02609 (13)
PM2  =  7.409E-4 (8)
PN1  =  0.00587 (6)
PN2  =  1.561E-4 (10)
PO1  =  9.65E-4 (17)
PO2  =  1.618E-5 (25)

K =  0.84469 (38)
L =  0.12148 (17)
M =  0.02683 (13)
N =  0.00603 (6)
O =  9.82E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 6.49

Log ft value (ec)    =  6.520 (38)
with log f           =  -0.011 (8)
or f-value           =  0.975 (19)
and log partial T1/2 =  6.532 (37)

