--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [7/2+] 697.52 (5) keV
Calculation of the allowed transition from the electron capture decay of I-123.

Transition energy: 536.5 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14045 (28)
PL2/PK =  0.003634 (12)
PM1/PK =  0.03095 (17)
PM2/PK =  8.788E-4 (14)
PN1/PK =  0.00697 (7)
PN2/PK =  1.852E-4 (13)
PO1/PK =  0.001145 (20)
PO2/PK =  1.919E-5 (30)

L/K =  0.14408 (27)
M/K =  0.03183 (17)
N/K =  0.00715 (7)
O/K =  0.001165 (20)


------------------------------
Relative capture probabilities

PK  =  0.84444 (39)
PL1 =  0.11860 (18)
PL2 =  0.003069 (11)
PM1 =  0.02613 (13)
PM2 =  7.421E-4 (8)
PN1 =  0.00588 (6)
PN2 =  1.564E-4 (11)
PO1 =  9.67E-4 (17)
PO2 =  1.621E-5 (25)

K =  0.84444 (39)
L =  0.12167 (18)
M =  0.02688 (13)
N =  0.00604 (6)
O =  9.83E-4 (17)


------------------------------
Capture branch from input data

Iec =   0.419 (13) %


---------------------
Capture probabilities

PK  =  0.84444 (39)
PL1  =  0.11860 (18)
PL2  =  0.003069 (11)
PM1  =  0.02613 (13)
PM2  =  7.421E-4 (8)
PN1  =  0.00588 (6)
PN2  =  1.564E-4 (11)
PO1  =  9.67E-4 (17)
PO2  =  1.621E-5 (25)

K =  0.84444 (39)
L =  0.12167 (18)
M =  0.02688 (13)
N =  0.00604 (6)
O =  9.83E-4 (17)


------------------------------------------------------------
Input log ft value (ec): 6.98

Log ft value (ec)    =  7.028 (16)
with log f           =  -0.027 (9)
or f-value           =  0.939 (18)
and log partial T1/2 =  7.055 (13)

