--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 53-I-123 [5/2+] g.s.  -->  Daughter nucleus: 52-Te-123 [3/2+] 1036.64 (12) keV
This transition from the electron capture decay of I-123 is calculated as allowed.

Transition energy: 197.4 (30) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1706 (11)
PL2/PK =  0.004407 (35)
PM1/PK =  0.03856 (41)
PM2/PK =  0.001092 (7)
PN1/PK =  0.00872 (14)
PN2/PK =  2.312E-4 (29)
PO1/PK =  0.001436 (33)
PO2/PK =  2.40E-5 (5)

L/K =  0.1750 (11)
M/K =  0.03965 (42)
N/K =  0.00896 (14)
O/K =  0.001460 (33)


------------------------------
Relative capture probabilities

PK  =  0.8163 (11)
PL1 =  0.1393 (7)
PL2 =  0.003597 (26)
PM1 =  0.03148 (29)
PM2 =  8.912E-4 (46)
PN1 =  0.00712 (10)
PN2 =  1.887E-4 (21)
PO1 =  0.001172 (25)
PO2 =  1.956E-5 (38)

K =  0.8163 (11)
L =  0.1429 (7)
M =  0.03237 (30)
N =  0.00731 (10)
O =  0.001192 (26)


------------------------------
Capture branch from input data

Iec =   0.0025 (9) %


---------------------
Capture probabilities

PK  =  0.8163 (11)
PL1  =  0.1393 (7)
PL2  =  0.003597 (26)
PM1  =  0.03148 (29)
PM2  =  8.912E-4 (46)
PN1  =  0.00712 (10)
PN2  =  1.887E-4 (21)
PO1  =  0.001172 (25)
PO2  =  1.956E-5 (38)

K =  0.8163 (11)
L =  0.1429 (7)
M =  0.03237 (30)
N =  0.00731 (10)
O =  0.001192 (26)


------------------------------------------------------------
Input log ft value (ec): 8.27

Log ft value (ec)    =  8.30 (16)
with log f           =  -0.979 (19)
or f-value           =  0.1049 (45)
and log partial T1/2 =  9.28 (16)

