--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-67 [3/2-] g.s.  -->  Daughter nucleus: 30-Zn-67 [1/2-] 93.31 keV
Calculation of the allowed transition from the electron capture decay of Ga-67.

Transition energy: 907.5 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11222 (16)
PL2/PK =  8.38E-4 (31)
PM1/PK =  0.01859 (7)
PM2/PK =  1.35E-4 (5)
PN1/PK =  0.001491 (32)

L/K =  0.11306 (19)
M/K =  0.01873 (7)
N/K =  0.001491 (32)


------------------------------
Relative capture probabilities

PK  =  0.88240 (23)
PL1 =  0.09902 (12)
PL2 =  7.40E-4 (27)
PM1 =  0.01641 (6)
PM2 =  1.195E-4 (47)
PN1 =  0.001316 (28)

K =  0.88240 (23)
L =  0.09976 (14)
M =  0.01653 (6)
N =  0.001316 (28)


------------------------------
Capture branch from input data

Iec =   50.5 (17) %


---------------------
Capture probabilities

PK  =  0.88240 (23)
PL1  =  0.09902 (12)
PL2  =  7.40E-4 (27)
PM1  =  0.01641 (6)
PM2  =  1.195E-4 (47)
PN1  =  0.001316 (28)

K =  0.88240 (23)
L =  0.09976 (14)
M =  0.01653 (6)
N =  0.001316 (28)


------------------------------------------------------------
Input log ft value (ec): 5.261

Log ft value (ec)    =  5.265 (20)
with log f           =  -0.481 (14)
or f-value           =  0.33 (1)
and log partial T1/2 =  5.747 (15)

