--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 31-Ga-67 [3/2-] g.s.  -->  Daughter nucleus: 30-Zn-67 [5/2-] 887.69 keV
Calculation of the allowed transition from the electron capture decay of Ga-67.

Transition energy: 113.1 (12) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12857 (41)
PL2/PK =  9.51E-4 (37)
PM1/PK =  0.02165 (12)
PM2/PK =  1.56E-4 (7)
PN1/PK =  0.001739 (41)

L/K =  0.12952 (44)
M/K =  0.02180 (13)
N/K =  0.001739 (41)


------------------------------
Relative capture probabilities

PK  =  0.86725 (46)
PL1 =  0.11150 (29)
PL2 =  8.25E-4 (32)
PM1 =  0.01877 (10)
PM2 =  1.35E-4 (6)
PN1 =  0.001509 (35)

K =  0.86725 (46)
L =  0.11233 (33)
M =  0.01891 (10)
N =  0.001509 (35)


------------------------------
Capture branch from input data

Iec =   0.280 (8) %


---------------------
Capture probabilities

PK  =  0.86725 (46)
PL1  =  0.11150 (29)
PL2  =  8.25E-4 (32)
PM1  =  0.01877 (10)
PM2  =  1.35E-4 (6)
PN1  =  0.001509 (35)

K =  0.86725 (46)
L =  0.11233 (33)
M =  0.01891 (10)
N =  0.001509 (35)


------------------------------------------------------------
Input log ft value (ec): 5.648

Log ft value (ec)    =  5.653 (26)
with log f           =  -2.350 (23)
or f-value           =  0.00447 (23)
and log partial T1/2 =  8.003 (12)

