--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 7-N-13 [1/2-] g.s.  -->  Daughter nucleus: 6-C-13 [1/2-] g.s.
Calculation of the allowed transition from the electron capture decay of N-13.

Transition energy: 2220.47 (27) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.0806 (7)
PL2/PK =  7.40E-6 (14)

L/K =  0.0806 (7)


------------------------------
Relative capture probabilities

PK  =  0.9254 (6)
PL1 =  0.0746 (6)
PL2 =  6.85E-6 (12)

K =  0.9254 (6)
L =  0.0746 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  0.00182 (5)
L1/b+ =  1.469E-4 (30)
L2/b+ =  1.347E-8 (15)

K/b+ =  0.00182 (5)
L/b+ =  1.469E-4 (30)

EC/b+ =  0.00197 (5)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   100.000 (7) %   Iec =   0.197 (5) %   Ib+ =   99.803 (5) %
Iec      =   0.197 (5) % (input data kept)
Ib+      =   99.803 (5) % (input data kept)
Iec tot. =   100 % (input data kept)


---------------------
Capture probabilities

PK  =  0.00182 (5)
PL1  =  1.466E-4 (42)
PL2  =  1.345E-8 (45)

K =  0.00182 (5)
L =  1.466E-4 (42)


------------------------------------------------------------
Input log ft value (ec & beta +): 3.6718

Log ft value (ec)    =  3.662 (16)
with log f           =  -1.820 (12)
or f-value           =  0.01513 (41)
and log partial T1/2 =  5.482 (11)

