--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [2+] 1769.10 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 105.2 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.3663 (39)
PL2/PK =  0.01438 (16)
PM1/PK =  0.0962 (14)
PM2/PK =  0.00413 (6)
PN1/PK =  0.02547 (48)
PN2/PK =  0.001068 (21)
PO1/PK =  0.00436 (9)
PO2/PK =  1.438E-4 (31)
PP1/PK =  4.22E-4 (9)

L/K =  0.3806 (41)
M/K =  0.1004 (15)
N/K =  0.0265 (5)
O/K =  0.00450 (9)
P/K =  4.22E-4 (9)


------------------------------
Relative capture probabilities

PK  =  0.6612 (27)
PL1 =  0.2422 (16)
PL2 =  0.00951 (7)
PM1 =  0.0636 (7)
PM2 =  0.00273 (3)
PN1 =  0.01684 (24)
PN2 =  7.06E-4 (11)
PO1 =  0.002880 (48)
PO2 =  9.51E-5 (17)
PP1 =  2.788E-4 (46)

K =  0.6612 (27)
L =  0.2517 (17)
M =  0.0664 (7)
N =  0.01755 (25)
O =  0.00298 (5)
P =  2.788E-4 (46)


------------------------------
Capture branch from input data

Iec =   0.068 (5) %


---------------------
Capture probabilities

PK  =  0.6612 (27)
PL1  =  0.2422 (16)
PL2  =  0.00951 (7)
PM1  =  0.0636 (7)
PM2  =  0.00273 (3)
PN1  =  0.01684 (24)
PN2  =  7.06E-4 (11)
PO1  =  0.002880 (48)
PO2  =  9.51E-5 (17)
PP1  =  2.788E-4 (46)

K =  0.6612 (27)
L =  0.2517 (17)
M =  0.0664 (7)
N =  0.01755 (25)
O =  0.00298 (5)
P =  2.788E-4 (46)


------------------------------------------------------------
Input log ft value (ec): 10.3

Log ft value (ec)    =  10.374 (34)
with log f           =  -1.424 (10)
or f-value           =  0.0377 (9)
and log partial T1/2 =  11.798 (32)

