--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [2+] 810.4474 (20) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 1063.9 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14351 (17)
PL2/PK =  0.005649 (10)
PM1/PK =  0.03390 (13)
PM2/PK =  0.001464 (7)
PN1/PK =  0.00877 (7)
PN2/PK =  3.708E-4 (33)
PO1/PK =  0.001492 (15)
PO2/PK =  4.97E-5 (5)
PP1/PK =  1.443E-4 (14)

L/K =  0.14916 (18)
M/K =  0.03536 (14)
N/K =  0.00914 (7)
O/K =  0.001542 (16)
P/K =  1.443E-4 (14)


------------------------------
Relative capture probabilities

PK  =  0.83658 (29)
PL1 =  0.12006 (10)
PL2 =  0.004726 (7)
PM1 =  0.02836 (10)
PM2 =  0.001225 (5)
PN1 =  0.00733 (6)
PN2 =  3.102E-4 (26)
PO1 =  0.001248 (12)
PO2 =  4.160E-5 (44)
PP1 =  1.207E-4 (12)

K =  0.83658 (29)
L =  0.12478 (11)
M =  0.02958 (11)
N =  0.00764 (6)
O =  0.001290 (13)
P =  1.207E-4 (12)


--------------------------
Capture-to-positron ratios

K/b+ =  5.7E7 (6)
L1/b+ =  8.2E6 (9)
L2/b+ =  3.22E5 (35)
M1/b+ =  1.94E6 (21)
M2/b+ =  8.4E4 (9)
N1/b+ =  5.0E5 (6)
N2/b+ =  2.12E4 (24)
O1/b+ =  8.5E4 (10)
O2/b+ =  2.84E3 (33)
P1/b+ =  8.2E3 (9)

K/b+ =  5.7E7 (6)
L/b+ =  8.5E6 (9)
M/b+ =  2.02E6 (22)
N/b+ =  5.2E5 (6)
O/b+ =  8.8E4 (10)
P/b+ =  8.2E3 (9)

EC/b+ =  6.8E7 (8)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.28 (3) %   Iec =   1.28 (3) %   Ib+ =   0 %
Iec      =   1.28 (3) % (input data kept)
Ib+      =   0 % (input data kept)
Iec tot. =   1.28 (3) % (input data kept)


---------------------
Capture probabilities

PK  =  0.83658 (29)
PL1  =  0.12006 (10)
PL2  =  0.004726 (7)
PM1  =  0.02836 (10)
PM2  =  0.001225 (5)
PN1  =  0.00733 (6)
PN2  =  3.102E-4 (26)
PO1  =  0.001248 (12)
PO2  =  4.160E-5 (44)
PP1  =  1.207E-4 (12)

K =  0.83658 (29)
L =  0.12478 (11)
M =  0.02958 (11)
N =  0.00764 (6)
O =  0.001290 (13)
P =  1.207E-4 (12)


------------------------------------------------------------
Input log ft value (ec & beta +): 11.4

Log ft value (ec)    =  11.472 (10)
with log f           =  0.9496 (20)
or f-value           =  8.903 (41)
and log partial T1/2 =  10.523 (10)

