--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [3+] 1233.8656 (17) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 640.4 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15111 (19)
PL2/PK =  0.005925 (11)
PM1/PK =  0.03596 (15)
PM2/PK =  0.001547 (7)
PN1/PK =  0.00932 (8)
PN2/PK =  3.924E-4 (35)
PO1/PK =  0.001586 (16)
PO2/PK =  5.26E-5 (6)
PP1/PK =  1.534E-4 (15)

L/K =  0.15703 (20)
M/K =  0.03750 (15)
N/K =  0.00971 (8)
O/K =  0.001639 (17)
P/K =  1.534E-4 (15)


------------------------------
Relative capture probabilities

PK  =  0.82916 (31)
PL1 =  0.12529 (11)
PL2 =  0.004913 (7)
PM1 =  0.02981 (11)
PM2 =  0.001283 (6)
PN1 =  0.00772 (6)
PN2 =  3.253E-4 (28)
PO1 =  0.001315 (13)
PO2 =  4.364E-5 (47)
PP1 =  1.272E-4 (12)

K =  0.82916 (31)
L =  0.13021 (12)
M =  0.03110 (12)
N =  0.00805 (6)
O =  0.001359 (13)
P =  1.272E-4 (12)


------------------------------
Capture branch from input data

Iec =   17.16 (8) %


---------------------
Capture probabilities

PK  =  0.82916 (31)
PL1  =  0.12529 (11)
PL2  =  0.004913 (7)
PM1  =  0.02981 (11)
PM2  =  0.001283 (6)
PN1  =  0.00772 (6)
PN2  =  3.253E-4 (28)
PO1  =  0.001315 (13)
PO2  =  4.364E-5 (47)
PP1  =  1.272E-4 (12)

K =  0.82916 (31)
L =  0.13021 (12)
M =  0.03110 (12)
N =  0.00805 (6)
O =  0.001359 (13)
P =  1.272E-4 (12)


------------------------------------------------------------
Input log ft value (ec): 9.8

Log ft value (ec)    =  9.8814 (32)
with log f           =  0.4858 (24)
or f-value           =  3.061 (17)
and log partial T1/2 =  9.3956 (21)

