--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [**] 1612.94 (6) keV
This transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 261.4 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1855 (4)
PL2/PK =  0.00726 (2)
PM1/PK =  0.04537 (23)
PM2/PK =  0.001946 (11)
PN1/PK =  0.01183 (11)
PN2/PK =  4.96E-4 (5)
PO1/PK =  0.002016 (23)
PO2/PK =  6.66E-5 (8)
PP1/PK =  1.950E-4 (22)

L/K =  0.19276 (42)
M/K =  0.04732 (24)
N/K =  0.01232 (11)
O/K =  0.002083 (24)
P/K =  1.950E-4 (22)


------------------------------
Relative capture probabilities

PK  =  0.7970 (5)
PL1 =  0.14785 (22)
PL2 =  0.005786 (12)
PM1 =  0.03616 (16)
PM2 =  0.001551 (8)
PN1 =  0.00942 (8)
PN2 =  3.956E-4 (37)
PO1 =  0.001607 (17)
PO2 =  5.31E-5 (6)
PP1 =  1.554E-4 (16)

K =  0.7970 (5)
L =  0.15363 (23)
M =  0.03771 (17)
N =  0.00982 (8)
O =  0.001660 (18)
P =  1.554E-4 (16)


------------------------------
Capture branch from input data

Iec =   0.0208 (14) %


---------------------
Capture probabilities

PK  =  0.7970 (5)
PL1  =  0.14785 (22)
PL2  =  0.005786 (12)
PM1  =  0.03616 (16)
PM2  =  0.001551 (8)
PN1  =  0.00942 (8)
PN2  =  3.956E-4 (37)
PO1  =  0.001607 (17)
PO2  =  5.31E-5 (6)
PP1  =  1.554E-4 (16)

K =  0.7970 (5)
L =  0.15363 (23)
M =  0.03771 (17)
N =  0.00982 (8)
O =  0.001660 (18)
P =  1.554E-4 (16)


------------------------------------------------------------
Input log ft value (ec): 11.9

Log ft value (ec)    =  11.932 (30)
with log f           =  -0.3798 (41)
or f-value           =  0.417 (4)
and log partial T1/2 =  12.312 (29)

