--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [3-] 1730.241 (22) keV
Calculation of the allowed transition from the electron capture decay of Eu-152.

Transition energy: 144.1 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.2597 (14)
PL2/PK =  0.01018 (6)
PM1/PK =  0.0660 (6)
PM2/PK =  0.002833 (26)
PN1/PK =  0.01736 (22)
PN2/PK =  7.28E-4 (10)
PO1/PK =  0.002965 (44)
PO2/PK =  9.79E-5 (15)
PP1/PK =  2.869E-4 (42)

L/K =  0.2699 (14)
M/K =  0.0689 (6)
N/K =  0.01809 (23)
O/K =  0.003063 (45)
P/K =  2.869E-4 (42)


------------------------------
Relative capture probabilities

PK  =  0.7352 (12)
PL1 =  0.1910 (7)
PL2 =  0.007485 (31)
PM1 =  0.04855 (33)
PM2 =  0.002082 (15)
PN1 =  0.01276 (14)
PN2 =  5.35E-4 (6)
PO1 =  0.002180 (29)
PO2 =  7.2E-5 (1)
PP1 =  2.109E-4 (27)

K =  0.7352 (12)
L =  0.1984 (7)
M =  0.05064 (35)
N =  0.01330 (15)
O =  0.002252 (30)
P =  2.109E-4 (27)


------------------------------
Capture branch from input data

Iec =   0.0422 (12) %


---------------------
Capture probabilities

PK  =  0.7352 (12)
PL1  =  0.1910 (7)
PL2  =  0.007485 (31)
PM1  =  0.04855 (33)
PM2  =  0.002082 (15)
PN1  =  0.01276 (14)
PN2  =  5.35E-4 (6)
PO1  =  0.002180 (29)
PO2  =  7.2E-5 (1)
PP1  =  2.109E-4 (27)

K =  0.7352 (12)
L =  0.1984 (7)
M =  0.05064 (35)
N =  0.01330 (15)
O =  0.002252 (30)
P =  2.109E-4 (27)


------------------------------------------------------------
Input log ft value (ec): 10.9

Log ft value (ec)    =  10.975 (14)
with log f           =  -1.030 (7)
or f-value           =  0.0934 (15)
and log partial T1/2 =  12.005 (12)

