--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [4-] 1022.967 (5) keV
Calculation of the allowed transition from the electron capture decay of Eu-152.

Transition energy: 851.3 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.14630 (18)
PL2/PK =  0.005747 (10)
PM1/PK =  0.03465 (14)
PM2/PK =  0.001494 (7)
PN1/PK =  0.00897 (7)
PN2/PK =  3.785E-4 (34)
PO1/PK =  0.001527 (16)
PO2/PK =  5.08E-5 (6)
PP1/PK =  1.476E-4 (15)

L/K =  0.15205 (19)
M/K =  0.03615 (15)
N/K =  0.00935 (7)
O/K =  0.001577 (16)
P/K =  1.476E-4 (15)


------------------------------
Relative capture probabilities

PK  =  0.83384 (30)
PL1 =  0.12199 (10)
PL2 =  0.004792 (7)
PM1 =  0.02889 (11)
PM2 =  0.001246 (5)
PN1 =  0.00748 (6)
PN2 =  3.156E-4 (27)
PO1 =  0.001273 (13)
PO2 =  4.233E-5 (45)
PP1 =  1.231E-4 (12)

K =  0.83384 (30)
L =  0.12678 (11)
M =  0.03014 (11)
N =  0.00779 (6)
O =  0.001315 (13)
P =  1.231E-4 (12)


------------------------------
Capture branch from input data

Iec =   0.238 (5) %


---------------------
Capture probabilities

PK  =  0.83384 (30)
PL1  =  0.12199 (10)
PL2  =  0.004792 (7)
PM1  =  0.02889 (11)
PM2  =  0.001246 (5)
PN1  =  0.00748 (6)
PN2  =  3.156E-4 (27)
PO1  =  0.001273 (13)
PO2  =  4.233E-5 (45)
PP1  =  1.231E-4 (12)

K =  0.83384 (30)
L =  0.12678 (11)
M =  0.03014 (11)
N =  0.00779 (6)
O =  0.001315 (13)
P =  1.231E-4 (12)


------------------------------------------------------------
Input log ft value (ec): 11.9

Log ft value (ec)    =  12.001 (9)
with log f           =  0.7474 (22)
or f-value           =  5.589 (28)
and log partial T1/2 =  11.254 (9)

