--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [2+] 121.7818 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 1752.5 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13929 (16)
PL2/PK =  0.005519 (9)
PM1/PK =  0.03276 (13)
PM2/PK =  0.001424 (6)
PN1/PK =  0.00846 (7)
PN2/PK =  3.604E-4 (32)
PO1/PK =  0.001440 (15)
PO2/PK =  4.83E-5 (5)
PP1/PK =  1.393E-4 (14)

L/K =  0.14481 (17)
M/K =  0.03418 (14)
N/K =  0.00882 (7)
O/K =  0.001489 (15)
P/K =  1.393E-4 (14)


------------------------------
Relative capture probabilities

PK  =  0.84073 (28)
PL1 =  0.11711 (10)
PL2 =  0.004640 (6)
PM1 =  0.02754 (10)
PM2 =  0.001198 (5)
PN1 =  0.00712 (5)
PN2 =  3.030E-4 (26)
PO1 =  0.001211 (12)
PO2 =  4.063E-5 (43)
PP1 =  1.171E-4 (11)

K =  0.84073 (28)
L =  0.12175 (10)
M =  0.02874 (10)
N =  0.00742 (6)
O =  0.001252 (12)
P =  1.171E-4 (11)


--------------------------
Capture-to-positron ratios

K/b+ =  59.14 (42)
L1/b+ =  8.238 (49)
L2/b+ =  0.3264 (18)
M1/b+ =  1.937 (8)
M2/b+ =  0.08424 (38)
N1/b+ =  0.5005 (39)
N2/b+ =  0.02131 (19)
O1/b+ =  0.0852 (9)
O2/b+ =  0.002858 (31)
P1/b+ =  0.00824 (8)

K/b+ =  59.14 (42)
L/b+ =  8.56 (5)
M/b+ =  2.021 (8)
N/b+ =  0.5218 (41)
O/b+ =  0.0880 (9)
P/b+ =  0.00824 (8)

EC/b+ =  70.34 (48)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   1.7 (10) %   Iec =   1.7 (10) %   Ib+ =   0.025 (15) %
Iec      =   1.7 (10) % (input data kept)
Ib+      =   0.025 (15) % (input data kept)
Iec tot. =   1.7 (10) % (input data kept)


---------------------
Capture probabilities

PK  =  0.82894 (28)
PL1  =  0.11547 (9)
PL2  =  0.004575 (6)
PM1  =  0.02715 (10)
PM2  =  0.001181 (5)
PN1  =  0.00702 (5)
PN2  =  2.988E-4 (25)
PO1  =  0.001194 (12)
PO2  =  4.006E-5 (42)
PP1  =  1.155E-4 (11)

K =  0.82894 (28)
L =  0.12004 (10)
M =  0.02833 (10)
N =  0.00731 (6)
O =  0.001234 (12)
P =  1.155E-4 (11)


------------------------------------------------------------
Input log ft value (ec & beta +): 11.8

Log ft value (ec)    =  11.80 (26)
with log f           =  1.3970 (18)
or f-value           =  24.94 (10)
and log partial T1/2 =  10.40 (26)

