--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [2+] 1292.771 (6) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 581.5 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15315 (20)
PL2/PK =  0.006003 (11)
PM1/PK =  0.03651 (15)
PM2/PK =  0.001570 (7)
PN1/PK =  0.00946 (8)
PN2/PK =  3.984E-4 (36)
PO1/PK =  0.001611 (17)
PO2/PK =  5.34E-5 (6)
PP1/PK =  1.559E-4 (16)

L/K =  0.15916 (21)
M/K =  0.03808 (16)
N/K =  0.00986 (8)
O/K =  0.001665 (17)
P/K =  1.559E-4 (16)


------------------------------
Relative capture probabilities

PK  =  0.82718 (32)
PL1 =  0.12669 (12)
PL2 =  0.004965 (7)
PM1 =  0.03020 (11)
PM2 =  0.001299 (6)
PN1 =  0.00783 (6)
PN2 =  3.295E-4 (28)
PO1 =  0.001333 (13)
PO2 =  4.420E-5 (47)
PP1 =  1.289E-4 (13)

K =  0.82718 (32)
L =  0.13165 (12)
M =  0.03150 (12)
N =  0.00816 (6)
O =  0.001377 (14)
P =  1.289E-4 (13)


------------------------------
Capture branch from input data

Iec =   0.644 (10) %


---------------------
Capture probabilities

PK  =  0.82718 (32)
PL1  =  0.12669 (12)
PL2  =  0.004965 (7)
PM1  =  0.03020 (11)
PM2  =  0.001299 (6)
PN1  =  0.00783 (6)
PN2  =  3.295E-4 (28)
PO1  =  0.001333 (13)
PO2  =  4.420E-5 (47)
PP1  =  1.289E-4 (13)

K =  0.82718 (32)
L =  0.13165 (12)
M =  0.03150 (12)
N =  0.00816 (6)
O =  0.001377 (14)
P =  1.289E-4 (13)


------------------------------------------------------------
Input log ft value (ec): 11.2

Log ft value (ec)    =  11.217 (7)
with log f           =  0.3962 (25)
or f-value           =  2.490 (14)
and log partial T1/2 =  10.821 (7)

