--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [3-] 1579.365 (3) keV
Calculation of the allowed transition from the electron capture decay of Eu-152.

Transition energy: 294.9 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.17792 (34)
PL2/PK =  0.006963 (17)
PM1/PK =  0.04329 (21)
PM2/PK =  0.001857 (10)
PN1/PK =  0.01127 (10)
PN2/PK =  4.731E-4 (46)
PO1/PK =  0.001921 (21)
PO2/PK =  6.35E-5 (8)
PP1/PK =  1.858E-4 (20)

L/K =  0.18489 (35)
M/K =  0.04514 (22)
N/K =  0.01174 (10)
O/K =  0.001984 (22)
P/K =  1.858E-4 (20)


------------------------------
Relative capture probabilities

PK  =  0.80390 (45)
PL1 =  0.14303 (19)
PL2 =  0.005598 (11)
PM1 =  0.03480 (15)
PM2 =  0.001493 (7)
PN1 =  0.00906 (7)
PN2 =  3.804E-4 (35)
PO1 =  0.001544 (16)
PO2 =  5.11E-5 (6)
PP1 =  1.494E-4 (15)

K =  0.80390 (45)
L =  0.14863 (20)
M =  0.03629 (15)
N =  0.00944 (8)
O =  0.001595 (17)
P =  1.494E-4 (15)


------------------------------
Capture branch from input data

Iec =   2.068 (12) %


---------------------
Capture probabilities

PK  =  0.80390 (45)
PL1  =  0.14303 (19)
PL2  =  0.005598 (11)
PM1  =  0.03480 (15)
PM2  =  0.001493 (7)
PN1  =  0.00906 (7)
PN2  =  3.804E-4 (35)
PO1  =  0.001544 (16)
PO2  =  5.11E-5 (6)
PP1  =  1.494E-4 (15)

K =  0.80390 (45)
L =  0.14863 (20)
M =  0.03629 (15)
N =  0.00944 (8)
O =  0.001595 (17)
P =  1.494E-4 (15)


------------------------------------------------------------
Input log ft value (ec): 10

Log ft value (ec)    =  10.0570 (46)
with log f           =  -0.2575 (38)
or f-value           =  0.5527 (48)
and log partial T1/2 =  10.3146 (26)

