--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 63-Eu-152 [3-] g.s.  -->  Daughter nucleus: 62-Sm-152 [4+] 1371.691 (9) keV
This 1st forbidden non-unique transition from the electron capture decay of Eu-152 is calculated as allowed.

Transition energy: 502.6 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.15675 (21)
PL2/PK =  0.006140 (12)
PM1/PK =  0.03749 (16)
PM2/PK =  0.001611 (8)
PN1/PK =  0.00972 (8)
PN2/PK =  4.090E-4 (37)
PO1/PK =  0.001656 (17)
PO2/PK =  5.49E-5 (6)
PP1/PK =  1.602E-4 (16)

L/K =  0.16289 (23)
M/K =  0.03910 (17)
N/K =  0.01013 (8)
O/K =  0.001711 (18)
P/K =  1.602E-4 (16)


------------------------------
Relative capture probabilities

PK  =  0.82372 (34)
PL1 =  0.12912 (12)
PL2 =  0.005058 (8)
PM1 =  0.03088 (12)
PM2 =  0.001327 (6)
PN1 =  0.00801 (6)
PN2 =  3.369E-4 (29)
PO1 =  0.001364 (14)
PO2 =  4.520E-5 (49)
PP1 =  1.319E-4 (13)

K =  0.82372 (34)
L =  0.13418 (13)
M =  0.03221 (12)
N =  0.00835 (7)
O =  0.001409 (14)
P =  1.319E-4 (13)


------------------------------
Capture branch from input data

Iec =   0.869 (24) %


---------------------
Capture probabilities

PK  =  0.82372 (34)
PL1  =  0.12912 (12)
PL2  =  0.005058 (8)
PM1  =  0.03088 (12)
PM2  =  0.001327 (6)
PN1  =  0.00801 (6)
PN2  =  3.369E-4 (29)
PO1  =  0.001364 (14)
PO2  =  4.520E-5 (49)
PP1  =  1.319E-4 (13)

K =  0.82372 (34)
L =  0.13418 (13)
M =  0.03221 (12)
N =  0.00835 (7)
O =  0.001409 (14)
P =  1.319E-4 (13)


------------------------------------------------------------
Input log ft value (ec): 10.9

Log ft value (ec)    =  10.950 (12)
with log f           =  0.2594 (27)
or f-value           =  1.817 (11)
and log partial T1/2 =  10.691 (12)

