# ============================================================================
# ============================================================================

# ----------------------------------------------------------------------------
# Random number validation
# ----------------------------------------------------------------------------
add_subdirectory(random)

# ----------------------------------------------------------------------------
# Radioactivity validation
# ----------------------------------------------------------------------------
add_subdirectory(radioactivity)
