--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [9/2+] 908.97 (3) keV
Calculation of the allowed transition from the electron capture decay of Zr-89.

Transition energy: 1923.8 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.11669 (19)
PL2/PK =  0.001594 (9)
PM1/PK =  0.02273 (12)
PM2/PK =  3.251E-4 (32)
PN1/PK =  0.004018 (45)
PN2/PK =  4.86E-5 (9)
PO1/PK =  4.15E-4 (6)

L/K =  0.11829 (20)
M/K =  0.02306 (12)
N/K =  0.004066 (46)
O/K =  4.15E-4 (6)


------------------------------
Relative capture probabilities

PK  =  0.87273 (29)
PL1 =  0.10184 (14)
PL2 =  0.001391 (7)
PM1 =  0.01984 (10)
PM2 =  2.837E-4 (27)
PN1 =  0.003506 (38)
PN2 =  4.24E-5 (7)
PO1 =  3.62E-4 (5)

K =  0.87273 (29)
L =  0.10323 (14)
M =  0.02012 (10)
N =  0.003549 (39)
O =  3.62E-4 (5)


--------------------------
Capture-to-positron ratios

K/b+ =  2.97 (6)
L1/b+ =  0.347 (6)
L2/b+ =  0.00473 (7)
M1/b+ =  0.0675 (10)
M2/b+ =  9.66E-4 (11)
N1/b+ =  0.01194 (15)
N2/b+ =  1.443E-4 (28)
O1/b+ =  0.001232 (21)

K/b+ =  2.97 (6)
L/b+ =  0.351 (6)
M/b+ =  0.0685 (10)
N/b+ =  0.01208 (15)
O/b+ =  0.001232 (21)

EC/b+ =  3.40 (7)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   99.00 (42) %   Iec =   76.2 (3) %   Ib+ =   22.8 (3) %
Iec      =   76.2 (3) % (input data kept)
Ib+      =   22.8 (3) % (input data kept)
Iec tot. =   99.00 (42) % (input data kept)


---------------------
Capture probabilities

PK  =  0.6746 (29)
PL1  =  0.07872 (36)
PL2  =  0.001075 (7)
PM1  =  0.01533 (10)
PM2  =  2.193E-4 (23)
PN1  =  0.002710 (32)
PN2  =  3.28E-5 (6)
PO1  =  2.798E-4 (44)

K =  0.6746 (29)
L =  0.07979 (37)
M =  0.01555 (10)
N =  0.002743 (32)
O =  2.798E-4 (44)


------------------------------------------------------------
Input log ft value (ec & beta +): 6.152

Log ft value (ec)    =  6.169 (5)
with log f           =  0.600 (5)
or f-value           =  3.980 (46)
and log partial T1/2 =  5.5688 (19)

