--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [5/2-] 1744.74 (18) keV
Calculation of the 1st forbidden unique transition from the electron capture decay of Zr-89.

Transition energy: 1088.1 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12128 (22)
PL2/PK =  0.001631 (10)
PL3/PK =  0.001013 (11)
PM1/PK =  0.02375 (13)
PM2/PK =  3.342E-4 (33)
PM3/PK =  1.919E-4 (30)
PN1/PK =  0.004201 (48)
PM4/PK =  2.133E-7 (47)
PN2/PK =  5.00E-5 (9)
PN3/PK =  2.43E-5 (6)
PO1/PK =  4.34E-4 (7)
PN4/PK =  3.04E-9 (6)

L/K =  0.12392 (24)
M/K =  0.02427 (14)
N/K =  0.004275 (49)
O/K =  4.34E-4 (7)


------------------------------
Relative capture probabilities

PK  =  0.86738 (32)
PL1 =  0.10519 (15)
PL2 =  0.001414 (8)
PL3 =  8.79E-4 (10)
PM1 =  0.02060 (11)
PM2 =  2.898E-4 (28)
PM3 =  1.665E-4 (26)
PN1 =  0.003643 (40)
PM4 =  1.850E-7 (42)
PN2 =  4.33E-5 (8)
PN3 =  2.11E-5 (5)
PO1 =  3.76E-4 (6)
PN4 =  2.64E-9 (5)

K =  0.86738 (32)
L =  0.10749 (17)
M =  0.02105 (11)
N =  0.003708 (41)
O =  3.76E-4 (6)


--------------------------
Capture-to-positron ratios

K/b+ =  3.3E6 (9)
L1/b+ =  4.0E5 (11)
L2/b+ =  5.4E3 (15)
L3/b+ =  3.4E3 (9)
M1/b+ =  7.9E4 (22)
M2/b+ =  1.12E3 (30)
M3/b+ =  6.4E2 (18)
N1/b+ =  1.40E4 (38)
M4/b+ =  0.71 (21)
N2/b+ =  167 (47)
N3/b+ =  81 (24)
O1/b+ =  1.45E3 (40)
N4/b+ =  0.0102 (29)

K/b+ =  3.3E6 (9)
L/b+ =  4.1E5 (11)
M/b+ =  8.1E4 (22)
N/b+ =  1.43E4 (39)
O/b+ =  1.45E3 (40)

EC/b+ =  3.8E6 (11)


------------------------------------------------------------
Splitting of the branch between capture and beta plus decays

Input data: Iec tot. =   0.123 (4) %   Iec =   0.123 (4) %   Ib+ =   0 %
Iec      =   0.123 (4) % (input data kept)
Ib+      =   0 % (input data kept)
Iec tot. =   0.123 (4) % (input data kept)


---------------------
Capture probabilities

PK  =  0.86738 (32)
PL1  =  0.10519 (15)
PL2  =  0.001414 (8)
PL3  =  8.79E-4 (10)
PM1  =  0.02060 (11)
PM2  =  2.898E-4 (28)
PM3  =  1.665E-4 (26)
PN1  =  0.003643 (40)
PM4  =  1.850E-7 (42)
PN2  =  4.33E-5 (8)
PN3  =  2.11E-5 (5)
PO1  =  3.76E-4 (6)
PN4  =  2.64E-9 (5)

K =  0.86738 (32)
L =  0.10749 (17)
M =  0.02105 (11)
N =  0.003708 (41)
O =  3.76E-4 (6)


------------------------------------------------------------
Input log ft value (ec & beta +): 9.09

Log ft value (ec)    =  9.105 (16)
with log f           =  0.744 (8)
or f-value           =  5.54 (11)
and log partial T1/2 =  8.361 (14)

