--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 40-Zr-89 [9/2+] g.s.  -->  Daughter nucleus: 39-Y-89 [7/2+] 2529.8 (2) keV
Calculation of the allowed transition from the electron capture decay of Zr-89.

Transition energy: 303.0 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.12685 (33)
PL2/PK =  0.001698 (11)
PM1/PK =  0.02498 (16)
PM2/PK =  3.499E-4 (38)
PN1/PK =  0.00442 (5)
PN2/PK =  5.23E-5 (10)
PO1/PK =  4.57E-4 (8)

L/K =  0.12855 (34)
M/K =  0.02533 (16)
N/K =  0.00448 (6)
O/K =  4.57E-4 (8)


------------------------------
Relative capture probabilities

PK  =  0.86295 (42)
PL1 =  0.10947 (23)
PL2 =  0.001465 (9)
PM1 =  0.02156 (13)
PM2 =  3.019E-4 (31)
PN1 =  0.003817 (45)
PN2 =  4.52E-5 (8)
PO1 =  3.94E-4 (6)

K =  0.86295 (42)
L =  0.11093 (24)
M =  0.02186 (13)
N =  0.003862 (46)
O =  3.94E-4 (6)


------------------------------
Capture branch from input data

Iec =   0.074 (5) %


---------------------
Capture probabilities

PK  =  0.86295 (42)
PL1  =  0.10947 (23)
PL2  =  0.001465 (9)
PM1  =  0.02156 (13)
PM2  =  3.019E-4 (31)
PN1  =  0.003817 (45)
PN2  =  4.52E-5 (8)
PO1  =  3.94E-4 (6)

K =  0.86295 (42)
L =  0.11093 (24)
M =  0.02186 (13)
N =  0.003862 (46)
O =  3.94E-4 (6)


------------------------------------------------------------
Input log ft value (ec): 7.52

Log ft value (ec)    =  7.538 (32)
with log f           =  -1.044 (12)
or f-value           =  0.0904 (25)
and log partial T1/2 =  8.581 (29)

