--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 64-Gd-153 [3/2-] g.s.  -->  Daughter nucleus: 63-Eu-153 [5/2+] 172.85320 (13) keV
This 1st forbidden non-unique transition from the electron capture decay of Gd-153 is calculated as allowed.

Transition energy: 311.1 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.17839 (32)
PL2/PK =  0.00728 (7)
PM1/PK =  0.04325 (19)
PM2/PK =  0.001931 (24)
PN1/PK =  0.01132 (8)
PN2/PK =  4.95E-4 (8)
PO1/PK =  0.002054 (23)
PO2/PK =  7.31E-5 (16)
PP1/PK =  2.069E-4 (37)

L/K =  0.18567 (39)
M/K =  0.04518 (21)
N/K =  0.01181 (9)
O/K =  0.002127 (25)
P/K =  2.069E-4 (37)


------------------------------
Relative capture probabilities

PK  =  0.80321 (46)
PL1 =  0.14329 (17)
PL2 =  0.00585 (5)
PM1 =  0.03474 (13)
PM2 =  0.001551 (18)
PN1 =  0.00909 (6)
PN2 =  3.97E-4 (6)
PO1 =  0.001650 (18)
PO2 =  5.88E-5 (12)
PP1 =  1.662E-4 (29)

K =  0.80321 (46)
L =  0.14914 (23)
M =  0.03629 (15)
N =  0.00949 (7)
O =  0.001708 (19)
P =  1.662E-4 (29)


------------------------------
Capture branch from input data

Iec =   15.7 (6) %


---------------------
Capture probabilities

PK  =  0.80321 (46)
PL1  =  0.14329 (17)
PL2  =  0.00585 (5)
PM1  =  0.03474 (13)
PM2  =  0.001551 (18)
PN1  =  0.00909 (6)
PN2  =  3.97E-4 (6)
PO1  =  0.001650 (18)
PO2  =  5.88E-5 (12)
PP1  =  1.662E-4 (29)

K =  0.80321 (46)
L =  0.14914 (23)
M =  0.03629 (15)
N =  0.00949 (7)
O =  0.001708 (19)
P =  1.662E-4 (29)


------------------------------------------------------------
Input log ft value (ec): 7.9

Log ft value (ec)    =  7.946 (18)
with log f           =  -0.176 (6)
or f-value           =  0.667 (9)
and log partial T1/2 =  8.122 (17)

