--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 64-Gd-153 [3/2-] g.s.  -->  Daughter nucleus: 63-Eu-153 [5/2-] 97.43103 (17) keV
Calculation of the allowed transition from the electron capture decay of Gd-153.

Transition energy: 386.6 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.16803 (26)
PL2/PK =  0.00686 (7)
PM1/PK =  0.04041 (16)
PM2/PK =  0.001805 (22)
PN1/PK =  0.01056 (7)
PN2/PK =  4.62E-4 (7)
PO1/PK =  0.001915 (21)
PO2/PK =  6.83E-5 (14)
PP1/PK =  1.929E-4 (34)

L/K =  0.17489 (32)
M/K =  0.04222 (18)
N/K =  0.01102 (8)
O/K =  0.001983 (22)
P/K =  1.929E-4 (34)


------------------------------
Relative capture probabilities

PK  =  0.81281 (40)
PL1 =  0.13658 (14)
PL2 =  0.00558 (5)
PM1 =  0.03285 (12)
PM2 =  0.001467 (17)
PN1 =  0.00858 (6)
PN2 =  3.75E-4 (6)
PO1 =  0.001557 (16)
PO2 =  5.55E-5 (11)
PP1 =  1.568E-4 (27)

K =  0.81281 (40)
L =  0.14215 (19)
M =  0.03432 (13)
N =  0.00896 (6)
O =  0.001612 (17)
P =  1.568E-4 (27)


------------------------------
Capture branch from input data

Iec =   38.0 (11) %


---------------------
Capture probabilities

PK  =  0.81281 (40)
PL1  =  0.13658 (14)
PL2  =  0.00558 (5)
PM1  =  0.03285 (12)
PM2  =  0.001467 (17)
PN1  =  0.00858 (6)
PN2  =  3.75E-4 (6)
PO1  =  0.001557 (16)
PO2  =  5.55E-5 (11)
PP1  =  1.568E-4 (27)

K =  0.81281 (40)
L =  0.14215 (19)
M =  0.03432 (13)
N =  0.00896 (6)
O =  0.001612 (17)
P =  1.568E-4 (27)


------------------------------------------------------------
Input log ft value (ec): 7.7

Log ft value (ec)    =  7.775 (14)
with log f           =  0.038 (6)
or f-value           =  1.091 (14)
and log partial T1/2 =  7.738 (13)

