--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 64-Gd-153 [3/2-] g.s.  -->  Daughter nucleus: 63-Eu-153 [5/2+] g.s.
This 1st forbidden non-unique transition from the electron capture decay of Gd-153 is calculated as allowed.

Transition energy: 484.0 (7) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.16017 (22)
PL2/PK =  0.00654 (6)
PM1/PK =  0.03827 (15)
PM2/PK =  0.001711 (20)
PN1/PK =  0.00998 (7)
PN2/PK =  4.37E-4 (7)
PO1/PK =  0.001810 (19)
PO2/PK =  6.46E-5 (13)
PP1/PK =  1.823E-4 (32)

L/K =  0.16671 (28)
M/K =  0.03998 (17)
N/K =  0.01042 (8)
O/K =  0.001875 (21)
P/K =  1.823E-4 (32)


------------------------------
Relative capture probabilities

PK  =  0.82023 (37)
PL1 =  0.13138 (12)
PL2 =  0.005366 (48)
PM1 =  0.03139 (11)
PM2 =  0.001403 (16)
PN1 =  0.00819 (5)
PN2 =  3.58E-4 (5)
PO1 =  0.001485 (15)
PO2 =  5.30E-5 (11)
PP1 =  1.496E-4 (26)

K =  0.82023 (37)
L =  0.13674 (17)
M =  0.03279 (12)
N =  0.00855 (6)
O =  0.001538 (16)
P =  1.496E-4 (26)


------------------------------
Capture branch from input data

Iec =   4 (3) %


---------------------
Capture probabilities

PK  =  0.82023 (37)
PL1  =  0.13138 (12)
PL2  =  0.005366 (48)
PM1  =  0.03139 (11)
PM2  =  0.001403 (16)
PN1  =  0.00819 (5)
PN2  =  3.58E-4 (5)
PO1  =  0.001485 (15)
PO2  =  5.30E-5 (11)
PP1  =  1.496E-4 (26)

K =  0.82023 (37)
L =  0.13674 (17)
M =  0.03279 (12)
N =  0.00855 (6)
O =  0.001538 (16)
P =  1.496E-4 (26)


------------------------------------------------------------
Input log ft value (ec): 8.9

Log ft value (ec)    =  8.97 (33)
with log f           =  0.254 (5)
or f-value           =  1.793 (21)
and log partial T1/2 =  8.72 (33)

