--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 46-Pd-103 [5/2+] g.s.  -->  Daughter nucleus: 45-Rh-103 [3/2-] 294.965 (10) keV
This 1st forbidden non-unique transition from the electron capture decay of Pd-103 is calculated as allowed.

Transition energy: 279.7 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.13603 (37)
PL2/PK =  0.002558 (8)
PM1/PK =  0.02854 (17)
PM2/PK =  5.589E-4 (37)
PN1/PK =  0.00621 (6)
PN2/PK =  1.080E-4 (12)

L/K =  0.13859 (38)
M/K =  0.02910 (18)
N/K =  0.00632 (6)


------------------------------
Relative capture probabilities

PK  =  0.85178 (45)
PL1 =  0.11587 (25)
PL2 =  0.002179 (5)
PM1 =  0.02431 (13)
PM2 =  4.761E-4 (29)
PN1 =  0.00529 (5)
PN2 =  9.20E-5 (9)

K =  0.85178 (45)
L =  0.11805 (26)
M =  0.02479 (14)
N =  0.00538 (5)


------------------------------
Capture branch from input data

Iec =   5.8E-4 (7) %


---------------------
Capture probabilities

PK  =  0.85178 (45)
PL1  =  0.11587 (25)
PL2  =  0.002179 (5)
PM1  =  0.02431 (13)
PM2  =  4.761E-4 (29)
PN1  =  0.00529 (5)
PN2  =  9.20E-5 (9)

K =  0.85178 (45)
L =  0.11805 (26)
M =  0.02479 (14)
N =  0.00538 (5)


------------------------------------------------------------
Input log ft value (ec): 10.52

Log ft value (ec)    =  10.52 (5)
with log f           =  -0.882 (9)
or f-value           =  0.1312 (28)
and log partial T1/2 =  11.40 (5)

