--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 46-Pd-103 [5/2+] g.s.  -->  Daughter nucleus: 45-Rh-103 [5/2-] 357.40 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of Pd-103 is calculated as allowed.

Transition energy: 217.3 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1423 (5)
PL2/PK =  0.002675 (11)
PM1/PK =  0.03003 (21)
PM2/PK =  5.876E-4 (45)
PN1/PK =  0.00654 (7)
PN2/PK =  1.137E-4 (13)

L/K =  0.1450 (5)
M/K =  0.03061 (22)
N/K =  0.00665 (7)


------------------------------
Relative capture probabilities

PK  =  0.8459 (6)
PL1 =  0.12036 (36)
PL2 =  0.002262 (7)
PM1 =  0.02540 (16)
PM2 =  4.970E-4 (34)
PN1 =  0.00553 (6)
PN2 =  9.61E-5 (11)

K =  0.8459 (6)
L =  0.12262 (37)
M =  0.02589 (17)
N =  0.00563 (6)


------------------------------
Capture branch from input data

Iec =   0.0300 (9) %


---------------------
Capture probabilities

PK  =  0.8459 (6)
PL1  =  0.12036 (36)
PL2  =  0.002262 (7)
PM1  =  0.02540 (16)
PM2  =  4.970E-4 (34)
PN1  =  0.00553 (6)
PN2  =  9.61E-5 (11)

K =  0.8459 (6)
L =  0.12262 (37)
M =  0.02589 (17)
N =  0.00563 (6)


------------------------------------------------------------
Input log ft value (ec): 8.569

Log ft value (ec)    =  8.569 (18)
with log f           =  -1.121 (12)
or f-value           =  0.0757 (21)
and log partial T1/2 =  9.690 (13)

