--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 46-Pd-103 [5/2+] g.s.  -->  Daughter nucleus: 45-Rh-103 [5/2+] 536.839 (8) keV
Calculation of the allowed transition from the electron capture decay of Pd-103.

Transition energy: 37.9 (24) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.63 (14)
PL2/PK =  0.0119 (28)
PM1/PK =  0.150 (37)
PM2/PK =  0.0029 (7)
PN1/PK =  0.033 (9)
PN2/PK =  5.8E-4 (15)

L/K =  0.64 (15)
M/K =  0.153 (38)
N/K =  0.034 (9)


------------------------------
Relative capture probabilities

PK  =  0.55 (5)
PL1 =  0.343 (38)
PL2 =  0.0065 (7)
PM1 =  0.082 (11)
PM2 =  0.00161 (21)
PN1 =  0.0183 (25)
PN2 =  3.18E-4 (43)

K =  0.55 (5)
L =  0.350 (39)
M =  0.084 (11)
N =  0.0186 (25)


------------------------------
Capture branch from input data

Iec =   0.00480 (16) %


---------------------
Capture probabilities

PK  =  0.55 (5)
PL1  =  0.343 (38)
PL2  =  0.0065 (7)
PM1  =  0.082 (11)
PM2  =  0.00161 (21)
PN1  =  0.0183 (25)
PN2  =  3.18E-4 (43)

K =  0.55 (5)
L =  0.350 (39)
M =  0.084 (11)
N =  0.0186 (25)


------------------------------------------------------------
Input log ft value (ec): 7.33

Log ft value (ec)    =  7.33 (11)
with log f           =  -3.16 (11)
or f-value           =  6.9E-4 (18)
and log partial T1/2 =  10.486 (15)

