if(WIN32)
  add_compile_options(
    "$<$<CONFIG:Debug>:/Od;/Zi;/GS;/W4;/Wall;/fp:precise>"
    "$<$<CONFIG:Release>:/Ox;/QxHost;/fp:fast;/DNDEBUG;/MD>"
    /EHsc
    /MT
    /external:W0
  )
else()
  add_compile_options(
  "$<$<CONFIG:Debug>:-Wall;-Wextra;-Wpedantic;-Wshadow>"
  "$<$<CONFIG:Debug>:-Wdouble-promotion;-Wformat=2;-Wformat-truncation>"
  "$<$<CONFIG:Debug>:-Wundef;-fno-common;-Wconversion>"
  "$<$<CONFIG:Debug>:-g3;-O0;-ffunction-sections;-fdata-sections;-Wpadded>"

  "$<$<CONFIG:Release>:-O3;-DNDEBUG;-march=native;-mtune=native>"
  "$<$<CONFIG:Release>:-fvectorize;-funroll-loops>"
  )
endif()
