--------------------------------------------------------------------------------------

BetaShape
Version: 2.4 (06/2024)
Author: X. Mougeot (xavier.mougeot@cea.fr)
CEA, LIST, Laboratoire National Henri Becquerel (LNHB), Gif-sur-Yvette F-91191, France
Please cite: [2019MO35] X. Mougeot, Applied Radiation and Isotopes 154, 108884 (2019)

--------------------------------------------------------------------------------------

Parent nucleus: 50-Sn-113 [1/2+] g.s.  -->  Daughter nucleus: 49-In-113 [1/2-] 391.699 (3) keV
This 1st forbidden non-unique transition from the electron capture decay of Sn-113 is calculated as allowed.

Transition energy: 644.3 (28) keV


----------------------------------------
Ratios of relative capture probabilities

PL1/PK =  0.1305 (2)
PL2/PK =  0.00298 (13)
PM1/PK =  0.02814 (13)
PM2/PK =  6.83E-4 (28)
PN1/PK =  0.00630 (6)
PN2/PK =  1.42E-4 (5)
PO1/PK =  7.19E-4 (13)
PO2/PK =  7.143E-6 (30)

L/K =  0.13348 (8)
M/K =  0.02882 (11)
N/K =  0.00644 (5)
O/K =  7.26E-4 (13)


------------------------------
Relative capture probabilities

PK  =  0.85509 (18)
PL1 =  0.11159 (15)
PL2 =  0.00255 (11)
PM1 =  0.02406 (11)
PM2 =  5.84E-4 (24)
PN1 =  0.005388 (48)
PN2 =  1.211E-4 (44)
PO1 =  6.15E-4 (11)
PO2 =  6.108E-6 (27)

K =  0.85509 (18)
L =  0.114135 (41)
M =  0.02465 (9)
N =  0.005509 (44)
O =  6.21E-4 (11)


------------------------------
Capture branch from input data

Iec =   97.79 (8) %


---------------------
Capture probabilities

PK  =  0.85509 (18)
PL1  =  0.11159 (15)
PL2  =  0.00255 (11)
PM1  =  0.02406 (11)
PM2  =  5.84E-4 (24)
PN1  =  0.005388 (48)
PN2  =  1.211E-4 (44)
PO1  =  6.15E-4 (11)
PO2  =  6.108E-6 (27)

K =  0.85509 (18)
L =  0.114135 (41)
M =  0.02465 (9)
N =  0.005509 (44)
O =  6.21E-4 (11)


------------------------------------------------------------
Input log ft value (ec): 7.01

Log ft value (ec)    =  7.029 (7)
with log f           =  0.022 (7)
or f-value           =  1.051 (16)
and log partial T1/2 =  7.00726 (37)

